### ISSUE TITLE
BlueMenta gives blurry menu font in gtk3 applications

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/mate-themes#104]
System: Fedora 23 with mate 1.12.1
gtk2 app (caja)
![gtk2](https://cloud.githubusercontent.com/assets/3275361/12918116/a0d780d6-cf3d-11e5-8b42-ba7d6623784c.png)

gtk3 app (evolution)
![gtk3boldfont](https://cloud.githubusercontent.com/assets/3275361/12918121/a8692ea8-cf3d-11e5-932b-8368442be481.png)

**Comment by raveit65** [comment]
I do not use evolution, any other applications where you this?

**Comment by smikkelsendk** [comment]
I also see it in the toolbar buttons of gedit
![gedittoolbarbuttons](https://cloud.githubusercontent.com/assets/3275361/12919896/7267e584-cf46-11e5-81f9-05fafc179499.png)

**Comment by raveit65** [comment]
Hmm,
i do not really see a blur with gedit and BlueMenta from mate-themes- 1.12.2-1 in f23.
![gedit](https://cloud.githubusercontent.com/assets/961604/12980097/2f15c9c2-d0db-11e5-9170-5471f9306c40.png)

**Comment by raveit65** [comment]
Maybe a font issue?

**Comment by smikkelsendk** [comment]
I made a video of how the change of theme instantly makes the text non-blurry (maybe a bit hard to see due to youtube's compression). https://www.youtube.com/watch?v=ZhzWfkgvru4
I dont see any change of the FONT between themes. Do you have any hints what I could change  in the BlueMenta theme to test what could be wrong?

**Comment by smikkelsendk** [comment]
I just found that it only occurs on my computer with a radeon gfx card and not my other pc with a nvidia card. Are there some opengl acceleration involved for gtk3 applications?

**Comment by smikkelsendk** [comment]
second note: Removing /usr/share/themes/BlueMenta/gtk-3.0/ makes the problem go away. The other themes without this problem also seems to be lacking a gtk-3.0 folder.

**Comment by raveit65** [comment]
> I dont see any change of the FONT between themes

I meant that maybe your fonts cause the issue. Can you try another one?
> Do you have any hints what I could change in the BlueMenta theme to test what could be wrong?

You can grep for 'text-shadow' in gtk3 folder, but i recall that i set all to 'text-shadow= none;'
> Are there some opengl acceleration involved for gtk3 applications?

 Not in theme settings, dunno if gtk+ do some  opengl acceleration.
> second note: Removing /usr/share/themes/BlueMenta/gtk-3.0/ makes the problem go away. The other themes without this problem also seems to be lacking a gtk-3.0 folder. 
In this case you use adwaita theme for gtk3 apps. Adwaita is a default fallback if a theme don't ship gtk3 support.
Sadly (btw. lucky) i use nvidia cards for my boxes and i never saw that with integrated intel graphics from my notebook, so i can't reproduce it.
But i will check Adwaita theme the next days, maybe i find some magic there.

**Comment by raveit65** [comment]
Btw. what driver and version are you using?

**Comment by smikkelsendk** [comment]
I am using default open source radeon driver. Fedora 23 64bit
`
02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Bonaire XTX [Radeon R7 260X/360]
`
[    3.374983] [drm] radeon kernel modesetting enabled.
[    3.388881] radeon 0000:02:00.0: Invalid ROM contents
[    3.389014] radeon 0000:02:00.0: VRAM: 1024M 0x0000000000000000 - 0x000000003FFFFFFF (1024M used)
[    3.389015] radeon 0000:02:00.0: GTT: 2048M 0x0000000040000000 - 0x00000000BFFFFFFF
[    3.389201] [drm] radeon: 1024M of VRAM memory ready
[    3.389203] [drm] radeon: 2048M of GTT memory ready.
[    3.400989] [drm] radeon: dpm initialized
[    3.421765] radeon 0000:02:00.0: WB enabled
[    3.421773] radeon 0000:02:00.0: fence driver on ring 0 use gpu addr 0x0000000040000c00 and cpu addr 0xffff880c01bc5c00
[    3.421774] radeon 0000:02:00.0: fence driver on ring 1 use gpu addr 0x0000000040000c04 and cpu addr 0xffff880c01bc5c04
[    3.421776] radeon 0000:02:00.0: fence driver on ring 2 use gpu addr 0x0000000040000c08 and cpu addr 0xffff880c01bc5c08
[    3.421777] radeon 0000:02:00.0: fence driver on ring 3 use gpu addr 0x0000000040000c0c and cpu addr 0xffff880c01bc5c0c
[    3.421779] radeon 0000:02:00.0: fence driver on ring 4 use gpu addr 0x0000000040000c10 and cpu addr 0xffff880c01bc5c10
[    3.422669] radeon 0000:02:00.0: fence driver on ring 5 use gpu addr 0x0000000000076c98 and cpu addr 0xffffc90006c36c98
[    3.422951] radeon 0000:02:00.0: fence driver on ring 6 use gpu addr 0x0000000040000c18 and cpu addr 0xffff880c01bc5c18
[    3.422952] radeon 0000:02:00.0: fence driver on ring 7 use gpu addr 0x0000000040000c1c and cpu addr 0xffff880c01bc5c1c
[    3.423009] radeon 0000:02:00.0: radeon: using MSI.
[    3.423040] [drm] radeon: irq initialized.
[    4.752832] fbcon: radeondrmfb (fb0) is primary device
[    4.784454] radeon 0000:02:00.0: fb0: radeondrmfb frame buffer device
[    4.789261] [drm] Initialized radeon 2.43.0 20080528 for 0000:02:00.0 on minor 0

`

`

**Comment by smikkelsendk** [comment]
I tried to go into gtk-3.0 folder and set all occurrences of text-shadow to: text-shadow: none 
This seems to have done the trick. I still get the 3D effect browsing through the menu, but no longer have the blurry fonts

**Comment by raveit65** [comment]
Ok, looks like that the open source driver have a font-rendering problem.
Can you try the proprietary driver ?
Maybe changing font rendering settings in mate-apperarence-properties helps.
Can you provide a diff from what you have change?
Need to have it to compare it with adwaita theme

**Comment by smikkelsendk** [comment]
Here is the patch
[gtk-widgets.css.patch.txt](https://github.com/mate-desktop/mate-themes/files/128025/gtk-widgets.css.patch.txt)

**Comment by raveit65** [comment]
Well, i don't think i will change it in the theme because it is a rendering issue with radeon driver/card.
Using text-shadow is a legitime styling element which works well with intel or nvidia cards.
....but mabe it's needs only change at one place.
I suggest to file out a report against open source driver, please post the link here.

**Comment by smikkelsendk** [comment]
OK I close the issue then. Thank you for your help

**Comment by smikkelsendk** [comment]
Fixed the problem by adding the following contents to /etc/X11/xorg.conf.d/20-radeon.conf

Section "Device"
	Identifier "device0"
	Driver "radeon"
	Option "ShadowPrimary" "true"
EndSection

So apparently enabling ShadowPrimary fixes the problem.  

Here is what the manual says about it:
       Option "ShadowPrimary" "boolean"
              This option enables a so-called "shadow primary" buffer for fast
              CPU  access to pixel data, and separate scanout buffers for each
              display controller (CRTC).  This  may  improve  performance  for
              some 2D workloads, potentially at the expense of other (e.g. 3D,
              video) workloads.  Note in particular that enabling this  option
              currently disables page flipping.  The default is off.

**Comment by smikkelsendk** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=94246
