### ISSUE TITLE
[mate-themes] TraditionalOK still broken with gtk-3.20

### ISSUE THREAD

**Issue by mpan-pl** [mate-desktop/mate-themes#115]
The current TraditionalOK (both gtk3.20 and master) is still broken with gtk-3.20. Various elements (text input, comboboxes, tabs, …) are extremely high. A comparison:
Before 3.20: ![pre-3 20](https://cloud.githubusercontent.com/assets/14152189/14488528/fbfd9920-0168-11e6-8fa7-bca020429cca.png)
Now:  ![post-3 20](https://cloud.githubusercontent.com/assets/14152189/14488533/00500b98-0169-11e6-8625-68f81433688a.png)

I’ve tried to modify the CSS files, but even if I set vertical paddings of all the elements to 0, they’re still very high.

**Comment by raveit65** [comment]
Maybe you don't know it, but gtk+ forced us to rewrite all themes complete.
https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/
Don't expect that themes will look the same as with previous gtk+ versions.
This is impossible!!!!

Same a ever:
Which distro?
Which gtk+ version?
Which application do we see here?

PS: After more than 700 hours work by me and others in the last months (our personal freetime), i'm tired about themes.
I've other things to do in live as styling a old theme which i don't like and use :)
Use another one or blame gtk+ about their ideas.

**Comment by raveit65** [comment]
BTW. gnome-calculator looks like this in f24 with gtk+-3.20.2
![bildschirmfoto zu 2016-04-13 12-23-50](https://cloud.githubusercontent.com/assets/961604/14490383/d063940e-0172-11e6-8a72-829c8763f36e.png)

**Comment by mpan-pl** [comment]
First of all: I’m not complaining or whining. I treat bug reports as a tool to tell devs that something is wrong, not to criticize them. You are doing an awesome job, and — especially you girls&guys @ mate — saved uncountable users from being forced to use GNOME3 (even if we don’t use Mate environment as a whole).

I do realize what’s going around gtk 3.20, I do expect that you have an extreme amount of work caused by the issue and this is why I’ve tried first to fix this myself and provide a patch, despite I have completely no idea how the themes work. Unfortunately, I’ve failed.

Versions:
- Distro: ArchLinux 64, packages updated to the current versions
- GTK: the major things breaker — 3.20
- App: [gucharmap](https://en.wikipedia.org/wiki/GNOME_Character_Map), but affects all Gtk3 apps I have: Firefox 45.0.2, Meld 3.15.2, gconf-editor 3.0.1, gnubiff 2.2.16 and ocrfeeder 0.8.1 (not many, but I’m trying to have as few gnomish deps as possible, especially with number “3” in it).

Just about a hour ago I found one peculiarity: the offending `entry` widgets have `min-height` set to `32px`, inherited from [`gtk/theme/Adwaita/gtk-contained.css`](https://git.gnome.org/browse/gtk+/tree/gtk/theme/Adwaita/gtk-contained.css?id=85e37925f019f0232ad4b0813fc504fb7e2cf64f#n177). Overriding this seems to fix the issue. But why is Adwaita’s CSS being pulled into it, and why doesn’t this affect your applications (the entry widget has ~27px on your picture)?

**Comment by mpan-pl** [comment]
Since what’ve found suggests that the issue is related to gtk-3.20 and some changes in how selecting themes works now, and not mate-themes, I’m closing the report now. Sorry for wasting your time: I was sure the theme isn’t fully updated yet. Feel free to re-open it someone can reproduce.

**Comment by raveit65** [comment]
In another report the issue was that TOK theme wasn't installed in /usr/share/themes/
It looks like there is a different if the theme isn't in home dir in archlinux for some reasons.
see https://github.com/mate-desktop/mate-themes/issues/114

**Comment by lukefromdc** [comment]
Adwaita is the default for GTK, but unless this changed too the CSS for it should not be inherited unless the theme is somehow set up to inherit from Adwaita, as an icon theme can do. If you set a totally blank gtk.css you should get a totally broken GTK 3, with all elements zero padded and most of them with either transparent or black backgrounds, with no Adwaita elements at all inherited. NO gtk.css file at all will default to Adwaita, if an unthemed element has been changed to default as well to Adwaita that is something I have not seen before and did not encounter in porting either BlackMATE or my own UbuntuStudio_Legacy theme to GTK 3.20.

**Comment by mpan-pl** [comment]
Thanks, I’ll be tracking both threads and any new issues on the topic. But for now it seems there are too many factors involved — now it seems that `xfsettingsd` (from Xfce) adds even more to the problem, interfering with how Gtk3 selects themes. Since the theme works fine when set via `GTK_THEME` I don’t consider this to be a mate-themes issue.
