### ISSUE TITLE
Firefox submenu menuitem hover color problem with TOK (gtk3 3.20.3)

### ISSUE THREAD

**Issue by troyengel** [mate-desktop/mate-themes#116]
This only shows up in Firefox (45.0.2 / Arch), other apps like nm-applet and gtk3-demo are just fine. The best I can describe it using the latest git/master CSS:

1. Using TraditionalOk, launch Firefox from a fresh start
2. Pull down the Bookmarks menu, you'll notice that in your menu items with submenus, the '>' arrow is the correct @menu_controls_color (@theme_fg_color) as defined in the CSS, black
3. Hover over a menu item with submenu, the text and arrow change to white (normal)
4. Hover off that item, the menu text returns to normal (black) but the arrow stays white (broken)
5. Dismiss and re-open the Bookmarks menu, now all your submenu '>' arrows are white (broken)

I've tried to figure out how to fix this and am coming up blank - I know it has something to do with 'menuitem arrow {}' and related items, something has to be set to make Firefox return back to the expected @menu_controls_color but I'm not sure what.

Like the previous issue it's something screwy FF is doing with gtk3 since all the other apps using gtk3 work just fine here - the '>' arrow is definitely a different/custom graphic than the theme default too, pretty easy to see that.

**Comment by raveit65** [comment]
I hate firefox...
....and that they block gtk3-inspector.
....and that those guys hardcode a lot of settings.
result is that something which can fix in 5 min takes 5 hours, because you can on do a blind try&error themeing.
....firefox like to blame their users.

**Comment by lukefromdc** [comment]
Chrome can never be the answer to this because Google writes it to be
easily tracked. I'd love to see someone fork Firefox, keep the old extension
system that is its main advantage over Rekonq or Gnome-Web, kill the
separate theming altogether, and strip out all the bloatware and phone-home
garbage.   Some of the theming hassles probably have their origins in the 
cross-platform nature of Firefox, and others in the "Australis"
interface situation that caused so much controversy,.

**Comment by raveit65** [comment]
A quick test shows me that firefox use the the old and ugly GtkArrow,
which is complete wrong for TOK themes.
TOK themes use the symbolic-arrows from mate-icon-theme or adwaita-icon-theme.
Which shows me that something is wrong with firefox gtk3.
GtkArrow itself is pretty broken in gtk+ and i heard that they have plans to drop it.

**Comment by raveit65** [comment]
Btw. i see the same with our reference theme (Blue)-Menta.
Same with boring adwaita........
So, this isn't a theme issue. Looks like a firefox hardcoding issue.
I suggest to open a report against firefox or gtk+.

**Comment by troyengel** [comment]
That was a good clue - I think I found the right piece of source that draws it, does this help in being able to define a theme element for it (or should I say, what gtk3 drawing elements it's using)?

https://hg.mozilla.org/mozilla-central/file/tip/widget/gtk/gtk3drawing.cpp#l1566

(disclaimer: making guesses, I know little about theme things just trying to help) - if we open a bug with gtk3 or FF, I think we need to supply a bit more details on what's wrong that they can make sense of...

**Comment by raveit65** [comment]
I was able to solve all probs with GreenLaguna from git.
I will back port those settings for all themes soon.
Main issue is that the selector 'arrow' don't support any check states.
So, you need to set the state 'hover' with 'menuitem', which causes other problems, see 
https://github.com/mate-desktop/mate-themes/commit/16e273ef9c668bc96df362778544652acf880a69#diff-f34c92923dba53df82e2f263a0d3efd1R2258
Second prob with firefox is that using a transition effect breaks the background with menuitem:hover state.
This i could solved with using old style classes for < gtk+-3.19, which is the third issue in firefox.
 see https://github.com/mate-desktop/mate-themes/commit/16e273ef9c668bc96df362778544652acf880a69#diff-f34c92923dba53df82e2f263a0d3efd1R2137
and
https://github.com/mate-desktop/mate-themes/commit/16e273ef9c668bc96df362778544652acf880a69#diff-f34c92923dba53df82e2f263a0d3efd1R2179
Fourth issue is that they don't add a css name at top level, the old name does not work with 3.20
Last but not least, blocking gtk3-inspector is another issue.
This should be enough to file out a report.

PS: donation is welcome ;)

**Comment by troyengel** [comment]
I have no problem supporting MATE development :) donation just made!

**Comment by raveit65** [comment]
Thank you.
This should fix your issue ee60baf01437992bfb922fa10d5516c8d812e942
Please try out latest git master or 3.20 branch.

**Comment by troyengel** [comment]
Working great for TraditionalOk, thanks! :+1:

**Comment by raveit65** [comment]
@troyengel 
i think you will love that ;)
4018c323852a55351d1772c855f6920b2dd2a90d

**Comment by troyengel** [comment]
It's been working great, thanks! :) Quick question about another one I can tell is them doing their own thing, their... notification popup (I don't know what it's called) like when you hover over the little red X to close a tab which says "Close tab (Ctrl+W)". It's missing any sort of border and blends into the UI with a grey background - is there an easy way to add a 1px black border or whatever to it?

I can tell it's custom since it doesn't use the same yellowish color background with a slight black border that shows up in other GTK3 apps (like nm-applet) and it's fine on the actual Firefox application border X ("Close Window") - just their internal popups. :-/ If it's not easy to fix no worried, it's trivial.

**Comment by raveit65** [comment]
I have no idea about for the moment, why **tooltips** in firefox or min/max/close buttons from any window don't follow tooltips settings in themes.
But i see that problem with adwaita theme too.
Maybe we have to use old theme syntax from previous gtk+ versions for some applications, or the WM needs to be adjusted.
Btw. i need to check how this works with older gtk+ versions.

**Comment by raveit65** [comment]
Tooltips for min/max/close/menu buttons depends on WM.
My results:
marco (gtk2) --> follow gtk theme
marco (gtk3 --> follow gtk theme after this commit https://github.com/mate-desktop/marco/commit/4ab26c4
metacity (gtk3) --> don't follow gtk theme, use general settings for bg and fg color

Our themes use 'gtk-tooltips' as selector for gtk2, so i guess xfwm4 ignore this setting.
You can test this with installing marco and 'marco --replace' to use marco WM.

**Comment by raveit65** [comment]
Using old selectors fixes tooltips in firefox, done in submarine themes.
I will back port this to other themes.

**Comment by troyengel** [comment]
:+1: working great over here with the latest commits to TOK, thanks!
