### ISSUE TITLE
Close button doesn't fill the corner

### ISSUE THREAD

**Issue by anton-z-s** [mate-desktop/mate-themes#117]
The "close" button in the upper-right don't registers on maximized windows when you click at the very upper-right corner. You must precisely aim the mouse cursor directly over the X button.
One can change that behavior by switching Window Borders to Esco, but it's just ugly.
Is it done intentionally or is it just a bug (since the problem appear on MATE 1.6)?

Some users have the same problem: https://forums.linuxmint.com/viewtopic.php?p=736482#p736482

**Comment by raveit65** [comment]
Which metacity theme you're using?
...my crystal ball is dead ;)
Please post the output of 'gsettings get org.mate.Marco.general theme'

**Comment by anton-z-s** [comment]
I've tried ambiant-mate, bluementa, traditionalok and mint-x.
The problem appears on all of them.

**Comment by lukefromdc** [comment]
I could not replicate this in MATE 1.14 built over GTK 3.20 on any theme I tried, in Marco nor in Compiz

**Comment by raveit65** [comment]
OH, you're using old mate-1.6 which is not suported anymore.
Can you post the gtk+3 version? Than i can give you a link to latest package for this version.

**Comment by anton-z-s** [comment]
I'm using MATE 1.12.1 
libgtk 3.18.9-1ubuntu3

But i've also tried mate on fedora, mint and arch. The problem appears on all of them.

**Comment by lukefromdc** [comment]
All of these distros still build MATE itself with GTK2, I tested MATE built
locally with GTK 3, which is my daily use DE.

**Comment by raveit65** [comment]
hmm, i never noticed that problem in fedora or rhel/centos.
Latest version for your gtt+3 version
http://pub.mate-desktop.org/releases/themes/3.18/mate-themes-3.18.1.tar.xz
Only for better understanding.
Also with a maximize window the close button isn't at the edge of the screen with our themes.
There is a distance of 2 or 3px between button area and screen edge.
If you don't want this you need to edit the metacity-theme.xml.

**Comment by raveit65** [comment]
I'm using for myself also the latest Mate gtk3 version.
But also in a fedora 22 VM with mate-1.12 (gtk2) i can move the cursur to the screen edge or short befoe the panel begins, and i can cose the window.
So forgot what i mentioned before.
It woks here.

**Comment by raveit65** [comment]
@flexiondotorg 
Can you reproduce this with ubuntu?

**Comment by anton-z-s** [comment]
I've found the discussion on how current behavior has been made on metacity: https://bugs.launchpad.net/ubuntu/+source/light-themes/+bug/558327
Mark Shuttleworth subnitted the bug.

**Comment by raveit65** [comment]
Well, this is an old discussion, but i can't reproduce this with latest metacity version here.
The area beside close button, and top panel and screen edge is always clickable.
So, i'm still wondering why you see a different behavior.
@monsta 
@flexiondotorg 
Can you reproduce this issue?

**Comment by anton-z-s** [comment]
For me it works exactly as in this picture:
![image](https://cloud.githubusercontent.com/assets/3487683/15040377/dfebe504-12e6-11e6-9c4d-868b9a746193.png)
the area below the line is clickable, whereas the area above is not clickable.

Anyway, i've been able to solve the problem by switching to zukitre theme.

**Comment by raveit65** [comment]
Do you use a top panel?

**Comment by anton-z-s** [comment]
No, i don't.

**Comment by raveit65** [comment]
oh, i'm using a top panel, maybe this is the different.
Can you add a top panel for testing please ?

**Comment by raveit65** [comment]
Btw. in which version of zukitre you don't have the issue?

**Comment by anton-z-s** [comment]
I've tried to add a top panel. With top panel it's hard to see the bug. Maybe there is like 1px window top border and it make no difference when you use top panel.
Maybe there is not many people use MATE without top panel...


i'm using zukitre 20150516-1
with mate 1.12.1-1 on gtk 3.20.3-4

**Comment by raveit65** [comment]
Can you please upload the zukitre 20150516-1 tarball somewhere?
Latest zukitre for gtk+-3.20 doesn't contain any metacity-theme-.xml anymore.
Means no support for MATE anymore.

**Comment by anton-z-s** [comment]
sure, there you are: https://drive.google.com/file/d/0BzTZSZDoIe0NRm1BQlFOVHBkVlE/view?usp=sharing
i'm using only window border from this theme

**Comment by raveit65** [comment]
Confirmed!
I could reproduce the issue if i don't use a top panel in a VM.
For Menta themes i added a metacity-theme-2.xml file which fixes the issue for me.
https://github.com/mate-desktop/mate-themes/commit/e9e818facc47cc7502c6fceb3db36afefd8d5b4e
Can you please test it?
You can simply download the file from master branch and copy it in the metacity-1 folder of Menta themes in /usr/share/themes, and set right permissions.

Because i could see a different in settings between version 1 and 2, i guess we have a limitation of metacity-theme-1.xml files.

**Comment by anton-z-s** [comment]
This is fixed the issue for me.
Thank you for your awesome work!

**Comment by alete89** [comment]
I'm experiencing this on fresh ubuntu-mate 18.04 with mate 1.20.1 using ambiant-mate.

**Comment by monsta** [comment]
That's distro-specific theme. This repo only has upstream themes.
Please report to https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork
