### ISSUE TITLE
theme dev talk 2

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-themes#119]
##

**Comment by raveit65** [comment]
@lukefromdc 
For some reasons your fixes for wrong header-bar nodes wasn't there anymore.
I did it again with latest commit for BlackMate today, + some general adjustments for headerbars and .titlebar.

**Comment by lukefromdc** [comment]
Thanks for catching that, wil test the overall changes now

**Comment by raveit65** [comment]
I branched gtk3.22 from master today. So changes for 3.20 you should do now directly on 3.20 branch.
As always master should be in sync with 3.22 branch now. I will cherrypick your commits on master to 3.22, or you try to do it for yourself.
I don't like the merge command very much because you will always get a useless merge commit.

**Comment by lukefromdc** [comment]
So far I have not made any GTK 3.22 specific changes to any theme but
my own, but BlackMATE will need some font updates due to those changes.
This will be a brutally busy week for me so I won't be able to do it right now
but I'll get to it when I can,

**Comment by flexiondotorg** [comment]
I have emailed @lukefromdc and strongly suggest he accept my offer of thanks :-)

**Comment by lukefromdc** [comment]
Also thanks for bringing the BlackMATE work I did on master during a break in my schedule this week to the GTK 3.22 branch. This has been an incredibly busy week for me elsewhere but I got lucky and found time to fix the font and deprecated single colorstop in a gradient errors in BlackMATE.

Next question is this, best answered by the original authors of BlackMATE: were those single color gradients (now deprecated and apparently ignored) meant to do anything more than set a single color background? If not they can be removed outright, I've got them commented out and background colors set for now. Gradients between two or more explicitly specified colors still work fine.

The GTK 3.21 changes seem to be more "under the hood" than theming related this time, and the size of the finished binary builds has dropped from 48MB for my last GTK 3.20 build to 32MB for my current GTK 3.21 build, though this has not been without bug issues and especially problems with deprecated items.

**Comment by raveit65** [comment]
BlackMate is a fork from gnomishdark http://gnome-look.org/content/show.php/GnomishDark?content=147290
But last update was for gtk+-3.12, so i guess he has given up to follow gtk+ changes.
2013-03-22 i added BlackMate starting with gtk+-3.6 for 1.6 branch.
After last sync with gnomisdark for 3.12 i started to commit on it like i thought it is the best.
I guess you're feel free to do anything ;)

**Comment by raveit65** [comment]
Btw. with 1.16 release we want switch to gtk3.
But personal i don't think that all apps are gtk3 only at that point.

**Comment by raveit65** [comment]
I had a quick talk today with gtk+ dev about 'Using one color stop with linear-gradient() is deprecated'
```
<raveit65> mclasen___, hi, what is the replacement for ?
<raveit65> (gtk3-widget-factory:26696): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4454:62: Using one color stop with linear-gradient() is deprecated.
<mclasen___> using two color stops ?
<mclasen___> css doesn't allow gradients with a single color stop
<raveit65> hmm, does that look same?
<mclasen___> if you use the same color twice, yes
<raveit65> ahh, ok thanks, good hint
```
I didn't test it how that looks yet, but maybe this helps.

**Comment by raveit65** [comment]
@lukefromdc 
Maybe you like to add such a setting to BlackMate https://github.com/mate-desktop/mate-themes/commit/6b804d273a9751de21d0a681c860db3f7c0e6820
Adding a text-shadow the panel labels makes the text always readable for ftransparent panels regardless of the bg color of the the desktop wallpaper.
For the moment i'm searching for a similar shadow setting for light themes with black fg color.

**Comment by lukefromdc** [comment]
Just added that, tested it with a white panel background (BlackMATE uses white text) and it was still readable. Subtle, does not visibly show up on normal panel but fixes white on white scenario

**Comment by raveit65** [comment]
@lukefromdc 
see https://bugzilla.redhat.com/show_bug.cgi?id=1344186
This affected BlackMate too.
This is the wifi password dialog from nm-applet which have as always no own style class.
I fixed this for Menta themes.
https://github.com/mate-desktop/mate-themes/commit/fc953e225b31d4cab2d4d79b09a5278e2ea0b536
But as it is a notebook this change can affect a lot of application.
For this reason i want to test it more before i push this to other branches and themes.
@leigh123linux  ^^^^

**Comment by lukefromdc** [comment]
I've got no easy way to test this, as often at home I have no other
networks in range and thus no obvious way to call the password dialog.

Feel free to push this to BlackMATE and I will check for any effects
on other notebooks. Thing is, I normally work in my own theme so in
checking another theme I don't see everything.

**Comment by lukefromdc** [comment]
A quick test with BlueMenta didn't show any obvious problems here with
other notebooks, though I could not test the password dialog.

**Comment by raveit65** [comment]
> Feel free to push this to BlackMATE and I will check for any effects on other notebooks. Thing is, I normally work in my own theme so in checking another theme I don't see everything.

I pushed a proposal for BlackMate to master.
If you agree we can use that for 3.22/20 branches.
I'm not sure for what the padding: 1px 0px 1px 1px; is good for in notebook.
Maybe this belongs to notebook.frame.

**Comment by lukefromdc** [comment]
Just tested in in some of the other notebooks, though I cannot get the 
password dialog from here. I'll take your word on fixing that, some time
back other notebooks in nm-applet had trouble I had to resolve in my 
own theme so this is no suprrise.  I see no problems elsewhere with this
fix, feel free to push it to the other branches.

**Comment by lukefromdc** [comment]
I finally found a way to specify font-size (in a theme anyway) in such a way that GTK 3.20 and 3.21 return the same results: by using "%" units. This is a css standard, which is what GNOME is trying to move GTK towards so it should not go away anytime soon. It also supports scaling to fit user-selected fonts. This is important due to the use case of a high-dpi display, and a user setting larger fonts and a large panel height, Also for visually impaired users. Hardcoded font sizes anywhere in a theme block scaling with fonts set in mate-control-center.  This commit to UbuntuStudio_Legacy shows how to do this:

https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy/commit/aef05bb7ef42e46e78dc41c413d7f0d70d66452b

I made one error and used the wrong percentages in the panel fonts and had to fix that. It's simple: If you want 12 px(gtk 3.20)/12pt(gtk3.22) fonts when the user selects a (something) 10 font, use `font-size: 120%;` and so on.

**Comment by raveit65** [comment]
Nice finder :)

**Comment by raveit65** [comment]
Does using 'font-size: smaller' also break scaling support?

**Comment by raveit65** [comment]
Done for all themes.

**Comment by lukefromdc** [comment]
No, should that work as far as I know (but have not directly tested). What
breaks scaling support for sure is even one instance of a font hardcoded to
a particular pt/px size.
