### ISSUE TITLE
TraditionalOKtest Missing from mate-themes-3.20.5-2 

### ISSUE THREAD

**Issue by fennectech** [mate-desktop/mate-themes#120]
i recently upgraded to mate-themes-3.20.5-2 and found that the theme i use is missing.  resulting in everything getting ugly

**Comment by raveit65** [comment]
Sorry,
gtk+ forced us to a complete rewrite of a theme for gtk+-3.20. See https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/
I spent about 3 month to port the other themes, all in my **free** time.
I have a real life , so we decided to drop the theme.

**Comment by lukefromdc** [comment]
Interesting that they closed comments on that blog post. Porting my own theme and BlackMATE were boatloads of work, some of which had to be done more than once as GTK evolved. They now claim the css will be mostly stable until GTK 4.0-but they already changed how fonts in themes are interpreted in GTK 3.21. That's only a few changes be GTK 3.21 is only at 3.21.1. We shall see...

**Comment by fennectech** [comment]
strange because copying the theme from the old version of the package solved the issue   has support for it not been removed yet?  can i continue to use the olld version?   how long would it take to have the theme ported on comission?

Sent from my iPad

On May 8, 2016, at 3:43 AM, NO NAME <notifications@github.com> wrote:

Sorry,
gtk+ forced us to a complete rewrite of a theme for gtk+-3.20. See https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/
I spent about 3 month to port the other themes, all in my free time.
I have a real life , so we decided to drop the theme.

**Comment by lukefromdc** [comment]
The old version will work if you are using GTK 3.18 or earlier, I would
expect quite a lot of breakage if you are using GTK 3.20, as the selectors
totally changed.

TraditionalOKTest is still listed as being in the GTK 3.18 branch of mate-
themes though, just not in Master or GTK 3.20.

**Comment by raveit65** [comment]
@fennectech 
are you shure you're using gtk+-3.20? :smile:

**Comment by fennectech** [comment]
could you point me in the direction to find someone who could (and would be willing to if paid) port the theme for me?  i am rather attached to it    

Sent from my iPad

On May 8, 2016, at 4:36 PM, lukefromdc <notifications@github.com> wrote:

The old version will work if you are using GTK 3.18 or earlier, I would
expect quite a lot of breakage if you are using GTK 3.20, as the selectors
totally changed.

TraditionalOKTest is still listed as being in the GTK 3.18 branch of mate-
themes though, just not in Master or GTK 3.20.

**Comment by lukefromdc** [comment]
I myself do not have the time, but if you want to do this you would use
TraditionalOK as the starting point and apply the theming differnces between
it and TraditionalOKTest to the copy of TraditionalOK that will become your 
port of TraditionalOKTest.

With no online currency and no "gatekeeper" accouhts like Google et all I would
have no way of accepting payment online for any task, security requrements have 
forced me to ensure that my entire online presence cannot be verified by banking 
or identity documents.

**Comment by fennectech** [comment]
is there a gui tool that would let me make the  alterations?     and could i get it pushed into  the mate-themes

Sent from my iPad

On May 8, 2016, at 4:54 PM, lukefromdc <notifications@github.com> wrote:

I myself do not have the time, but if you want to do this you would use
TraditionalOK as the starting point and apply the theming differnces between
it and TraditionalOKTest to the copy of TraditionalOK that will become your 
port of TraditionalOKTest.

With no online currency and no "gatekeeper" accouhts like Google et all I would
have no way of accepting payment online for any task, security requrements have 
forced me to ensure that my entire online presence cannot be verified by banking 
or identity documents.

**Comment by lukefromdc** [comment]
I've never heard of such a tool
