### ISSUE TITLE
Menta 3.20: no close buttons in some dialogs

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-themes#123]
Latest build from 3.20 branch...

![no-close-1](https://cloud.githubusercontent.com/assets/5138986/15675243/0d5e5b46-2752-11e6-993a-6675b3efcfa1.png)

![no-close-2](https://cloud.githubusercontent.com/assets/5138986/15675250/153db6cc-2752-11e6-9b1b-9f201273ef35.png)

**Comment by raveit65** [comment]
fixed
4d4f479a90d272f61be7859ef16c02046fe92157

**Comment by raveit65** [comment]
...not perfect enough :)

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-themes/commit/b02c1ac565ef654068abceb6faca9781aa660d18
