### ISSUE TITLE
Blackmate 3.20/3.22: Firefox renders unreadable entry text in some websites only

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-themes#124]
I was NOT able to fix this by the usual method of adding .entry to the entry theming stanzas. Some websites render entries dark with white text, a mismatch to what Firefox does in BlacMATE (only partially applies the theme it seems) but Hushmail renders dark text on a dark entry,

Some way to either force the entries white for black text on ALL websites (best match for what Firefox does to BlackMATE) or to force the text white on all the dark entries would fix this.  This is with FF46, which does not officially support GTK 3.20 but works in most of our themes.

If none of us can fix this we could notify Firefox users that a userChrome.css file (which I could easily write) dropped into the user's profile in .mozilla/firefox/(some random number)/chrome would fix this by overriding all themes to force the entry backgrounds white and should be used.  I've yet to find a way to do this in the theme itself. Possibly Mozilla will fix this themselves when they officially support GTK 3.20 and later.

**Comment by lukefromdc** [comment]
Here's what this bug does to Hushmail in BlackMATE, Firefox 46, and GTk 3.21:

![firefox_problem](https://cloud.githubusercontent.com/assets/14036792/15809440/4074b424-2b5f-11e6-90cc-0109f9f18246.png)

**Comment by raveit65** [comment]
Writing a firefox css seems to be the only solution to fix such issues with dark themes.
You can create such a directory for it
mate-themes/desktop-themes/BlackMATE/firefox

**Comment by lukefromdc** [comment]
Firefox 47 just came out today and seems to have fixed this

**Comment by lukefromdc** [comment]
Firefox 47 was only a partial fix: it cleaned up some websites but Hushmail still has the same issue and probably requires a firefox css. Maybe 48 will fix this, until then to use Hushmail with FF 46 or 67 and BlackMATE does need a firefox css file.

**Comment by raveit65** [comment]
I noticed that tooltip text is wrong again with firefox-47.0-4.fc24.x86_64

**Comment by lukefromdc** [comment]
Tooltips are still OK in my own theme, I'll take a look at the code difference
but I can make no promises regarding Firefox due to the difficulty of working
with it.

**Comment by raveit65** [comment]
fg color is always white, so you don't see it if bg color is dark like adwaita or BlackMate.

**Comment by lukefromdc** [comment]
In testing the difficulty is this: Firefox only partially applies a theme change
from the control center. Thus I cannot test Firefox and any theme while
I've got a bunch of windows going or am waiting on a (throttled to 32.3)
download.

**Comment by lukefromdc** [comment]
Just tested Firefox 47 with GTK 3.21.2 and BlackMATE, starting up after shutting down and changing theme. Assuming the theme was applied fully tooltips were OK here: square corners, silver/grey border, opaque black background, and white text, easily readable. On my theme they get rounded corners and a transparent black background so hopefully this is not a leftover from the previous run of Firefox with my usual theme.

**Comment by raveit65** [comment]
Try anothe theme which use black fg color from us, and you will fg color is wrong.

**Comment by jbicha** [comment]
The square corners is a [Firefox bug](https://bugzilla.mozilla.org/1271523) and will be fixed in Firefox 49. Fedora has backported the [patch](http://pkgs.fedoraproject.org/cgit/rpms/firefox.git/tree/firefox-gtk3-20.patch) to 47.

**Comment by lukefromdc** [comment]
In my testing tonight, firefox is totally ignoring a  /usr/share/themes/BlackMATE/firefox/chrome/userChrome.css file, same if it is /usr/share/themes/BlackMATE/firefox/userChrome.css 
To distribute a fix for this with BlackMATE it needs to be somewhere in the named GTK theme, it can't go into say, /usr/share/mozilla (much less the users /home/.mozilla directory where it actually works) because if it worked at all it would be applied in all themes.  All dark themes are reported to have this issue with Firefox and the only fix I've seen so far is that file in /home/.mozilla/firefox<someramdomnumber>.default/chrome

**Comment by lukefromdc** [comment]
I just found that BlackMATE actually works fine in Firefox-but only if Firefox is started up with BlackMATE already selected as the theme. Then editable text is white on a dark gray background in the fields in question. Changing the theme in Firefox DOES NOT CHANGE the text color in the offending text fields, so changing from BlackMATE to a light theme will then render unreadable white text. This is a Firefox bug and cannot be fixed in any theme. Users thus need to restart Firefox when switching from a dark to a light theme until Mozilla fixes this.

**Comment by lukefromdc** [comment]
Closing as we can do nothing here other than remind users to restart Firefox on theme changes from light to dark or dark to light

**Comment by raveit65** [comment]
Agree, that a restart with the theme is needed is a really old issue with ff.
I noticed that since years with gtk2 version of ff too..........
