### ISSUE TITLE
TraditionalOk text highlight color not applied to dropdowns in "save as" dialogs

### ISSUE THREAD

**Issue by cruoploav** [mate-desktop/mate-themes#127]
With TraditionalOk, text is supposed to be highlighted in white with a blue background. The text instead remains black for dropdowns in "save as" dialogs.

The issue can be observed for example in Firefox's File->"Save Page As..." or Pluma's File->"Save As..."

This works correctly in Fedora 23 with mate-themes 3.18.2, but does not work correctly in Fedora 24 with mate-themes 3.20.8 -- reference bottom right of screen captures for each ...

**Fedora 23 / mate-themes 3.18.2 (correct):**
![f23](https://cloud.githubusercontent.com/assets/20206403/16452143/f5436dd2-3dd4-11e6-9791-3fb7f3738faa.png)

**Fedora 24 / mate-themes 3.20.8 (incorrect):**
![f24](https://cloud.githubusercontent.com/assets/20206403/16452173/18382f8a-3dd5-11e6-8f8e-1e6941a5f768.png)

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-themes/commit/d7cef9524a6aabb11562eed078859495279a6485
I will update fedora soon.
