### ISSUE TITLE
(all themes) print dialog paper depictions not appearing correctly

### ISSUE THREAD

**Issue by cruoploav** [mate-desktop/mate-themes#128]
All themes are affected (e.g. BlackMATE, Menta, TraditionalOk) ...

This affects the print dialog opened by Pluma, for example.

On the "General" tab, next to "Reverse" there is supposed to be a depiction of two numbered pieces of paper. Here's how it correctly appeared in Fedora 23 with mate-themes 3.18.2:
![f23a](https://cloud.githubusercontent.com/assets/20206403/16452926/e0cefa84-3dd8-11e6-9552-0eb8c5808b12.png)

Here it is in Fedora 24 with mate-themes 3.20.8 (notice the numbers are there, but the paper depictions are gone):
![f24a](https://cloud.githubusercontent.com/assets/20206403/16452956/03f5c6a0-3dd9-11e6-9966-243908b15854.png)

There's also an issue on the "Page Setup" tab. Here's how the paper depiction correctly appeared at the bottom of the dialog in Fedora 23 with mate-themes 3.18.2:
![f23b](https://cloud.githubusercontent.com/assets/20206403/16453010/3870f7f6-3dd9-11e6-99df-70bd915b5168.png)

Here it is in Fedora 24 with mate-themes 3.20.8 (notice the paper shadow appears to be on top of the paper):
![f24b](https://cloud.githubusercontent.com/assets/20206403/16453019/471e030c-3dd9-11e6-8e29-af55869c3a54.png)

Is this a bug in the themes? GTK?

**Comment by lukefromdc** [comment]
It works in Adwaita, I found a GTK css node named "paper" that might 
be themable. Will try it in my own theme and post the result.

**Comment by lukefromdc** [comment]
This turned out to have a simple fix at least in GTK 3.20 and 3.21, where the widget has the cssnode name "paper." Fixed it in BlackMATE for master, GTK 3.20, and GTK 3.22. 
https://github.com/mate-desktop/mate-themes/commit/2f5ee325dd5cde43d36b6c91abeac8498388dec9

The label color seems to be hardcoded black, so the background color should be set to white or near-white as sheets of paper will usually be. The border should be a darker color that shows up against the other "sheet" in the widget.

In GTK 3.18 or earlier the "paper" widget will no doubt have a different name, it will show up in GtkInspector in any case.

**Comment by raveit65** [comment]
Nice finder :)

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-themes/commit/a8ad1bb575f2d3c64f58e107beb915a112462315
I will update fedora soon.

**Comment by cruoploav** [comment]
thanks guys!

**Comment by cruoploav** [comment]
the paper depiction on the "General" tab looks perfect now, and the paper depiction on the "Page Setup" tab is much improved, but still has a small glitch (notice the shadow on the bottom and right edges is overlapping the paper):
![overlap](https://cloud.githubusercontent.com/assets/20206403/24754204/7f379666-1aa3-11e7-90dc-d46fd44ae563.png)

Mate 1.16.1

should I open a separate issue?

**Comment by raveit65** [comment]
of course....

**Comment by sc0w** [comment]
@cruoploav you have an old version

I can't reproduce this issue with TOK and gtk 3.22.9

**Comment by cruoploav** [comment]
@sc0w -- the screen capture is from BlueMenta, but the issue also appears in TraditionalOk in Fedora 25 with Mate 1.16.1, mate-themes 3.22.7, and gtk 3.22.10

You may have to zoom in to more easily see that it overlaps.
