### ISSUE TITLE
GTK3 progress bar looks odd in different themes

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/mate-themes#131]
Fedora 24 - Mate 1.14.1
When i open MATE System Monitor using BlueMenta theme, the progress bar looks a bit odd. it has an empty filling. For BlackMate there is only filling for the selected entry and it is almost invisble. 
However the High Contrast theme looks okay.

Is this as intended?

![bluementa](https://cloud.githubusercontent.com/assets/3275361/16802554/8dba8384-4901-11e6-9ad6-9fef0b964419.png)

![blackmate](https://cloud.githubusercontent.com/assets/3275361/16802556/90f0af24-4901-11e6-88d6-ae2a893f2ec5.png)

![highcontrast](https://cloud.githubusercontent.com/assets/3275361/16802558/95220692-4901-11e6-844e-6c1da4bade8c.png)

**Comment by lukefromdc** [comment]
This is NOT as intended: the only themes I have this working in are my 
own (gtk3.20/21 testing right now) and High Contrast. These are progressbars
in treeviews, upstream GTK devs changed the selectors on us repeatedly
during the 3.19 cycle. 

I never saw this before simply because I had never opened the system 
monitor while testing another theme after the last of those GTK changes.
I will now port this work from UbuntuStudio_Legacy to BlackMATE as an 
example for the maintaniers of the other themes.

**Comment by smikkelsendk** [comment]
BlueMenta Looks better now, but still it not optimal when you select an progress that is almost zero. Then it looks a bit like the selected is at 100%
![lowpercentageselected](https://cloud.githubusercontent.com/assets/3275361/16835066/1f973990-49b7-11e6-8f83-2e50e28c7730.png)

**Comment by raveit65** [comment]
damned, the trough have the same color as progressbar as progressbar unselected.

**Comment by raveit65** [comment]
@smikkelsendk 
Can you edit gtk-widget.css and replace  'treeview.view.trough:selected'  with
```
treeview.view.trough:selected {
    background-color: shade(@theme_selected_bg_color, 1.3);
    border: 1px solid rgba(0, 0, 0, 0.3);
}
```
I want to make the selected item darker than the others.
If it is OK for you i will commit.

**Comment by raveit65** [comment]
better use this :)
```
treeview.view.trough:selected {
    background-color: shade(@theme_selected_bg_color, 1.3);
    border: 1px solid rgba(0, 0, 0, 0.3);
    color: @theme_fg_color;
}
```

**Comment by smikkelsendk** [comment]
Thank you for the super quick responses, and yeah, it looks much nicer now.

**Comment by raveit65** [comment]
np, commited.
Thank you for reporting that, whole the themes must be rewritten complete for gtk+-3.20, so i missed the progressbar in treeview.
