### ISSUE TITLE
Firefox links are too dark

### ISSUE THREAD

**Issue by ilyuha21st** [mate-desktop/mate-themes#132]
Hello, problem risen when I tried to quick search through bookmarks/recent activity on my firefox 47.0. Links have color approximately equal to #0000ff, that is to dark: some letters are not recognized and looks coldly at all. Is it possible to improve user experience by making them more lighter? I use ubuntu-mate 16.04 lsb

**Comment by lukefromdc** [comment]
Which themes are affected?  With ubuntu-mate 16.04 I will assume you
are using GTK 3.18.

**Comment by ilyuha21st** [comment]
I'm little confused. Go through ‘apt-cache show ubuntu-mate-themes’ I’ve gotten:
_Package: ubuntu-mate-themes
Priority: optional
Section: universe/x11
Installed-Size: 1542
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Ubuntu MATE Team <ubuntu-mate-dev@lists.launchpad.net>
Architecture: all
Source: ubuntu-mate-artwork
Version: 16.04.6
Depends: gtk2-engines-murrine (>= 0.90.3+git20100810), ubuntu-mate-icon-themes
Filename: pool/universe/u/ubuntu-mate-artwork/ubuntu-mate-themes_16.04.6_all.deb
Size: 154086
..._
But ubuntu official resource say that The Xenial Xerus (current stable release)  has mate-themes 1.12.2+gtk3.18-1 version (and I guess that based on gtk3.18).

**Comment by monsta** [comment]
@flexiondotorg: version 1.12.2+gtk3.18-1 is quite old - can you please update it to the latest one from http://pub.mate-desktop.org/releases/themes/3.18/?

**Comment by raveit65** [comment]
Ok, you have Ubuntu-Mate-themes and mate-themes installed.
But which theme are you using?
Btw, with which theme ypu see the issue?
And please provide a screenshot.
@flexiondotorg 
Does ubuntu Xenial Xerus use firefox gtk3?

**Comment by monsta** [comment]
All Ubuntu releases have FF 47 now, so yes, it's GTK+3 version.

**Comment by ilyuha21st** [comment]
I have updated mate-themes to github master version and the same issue.

**Comment by raveit65** [comment]
Dear reporter,
What is so hard for to tell us which theme are you using ;)
Sorry, without this info your report is like a black hole and i can't help you :D

**Comment by raveit65** [comment]
PS: i will close the report if you don't give an answer, i don't have the time to play useless games.

**Comment by flexiondotorg** [comment]
I can file an SRU for the newer mate-themes.

**Comment by raveit65** [comment]
Reporter don't give us useful Info's !
Closing.
