### ISSUE TITLE
BlackMATE-Text selection highlight during file renaming is black on black-in nemo

### ISSUE THREAD

**Issue by Gnalldo** [mate-desktop/mate-themes#133]
When trying to rename a file, if I select the text for copy/paste there looks to be no highlight so I can't see what's selected. I'm using Linux Mint 18.

**Comment by raveit65** [comment]
which version of mate-themes?

**Comment by raveit65** [comment]
And where ?   :)

**Comment by Gnalldo** [comment]
Sorry, I should have been more specific. It happens in nemo. I was using the theme in cinnamon when I noticed. I double checked it's not a problem in caja.

**Comment by raveit65** [comment]
Indeed , happens here with latest 3.18.3.

**Comment by raveit65** [comment]
See, https://github.com/linuxmint/nemo/pull/1189
and https://github.com/linuxmint/nemo/commit/01ba4067ebd7fad216ed58a05b91734b3958f53f
Second commit did revert exactly those settings which fixes the issue.
Well, Linuxmint art head didn't like to hard code those settings for Navigation window.
So we need to set this in other-application.css. This will help.
```
.nemo-window .nemo-window-pane .view .entry,
.nemo-window .nemo-window-pane .view .entry:active,
.nemo-window .nemo-window-pane .view .entry:focus,
.nemo-window .nemo-window-pane .view .entry:backdrop {
    border-image: none;
    border-style: solid;
    border-width: 1px;
    border-color: #000000;
    border-radius: 3px;
    color: #000000;
    text-shadow: none;
    background-image: -gtk-gradient(linear,
                                    left top, left bottom,
                                    from       (shade(rgba(255,255,255,1), 0.86)),
                                    color-stop (0.15, shade(rgba(255,255,255,1), 0.96)),
                                    color-stop (0.50, shade(rgba(255,255,255,1), 0.98)),
                                    to         (shade(rgba(255,255,255,1), 1.00)));
}

.nemo-window .nemo-window-pane .view .entry:active,
.nemo-window .nemo-window-pane .view .entry:selected,
.nemo-window .nemo-window-pane .view .entry:focus:selected,
.nemo-window .nemo-window-pane .view .entry:backdrop:selected {
    background-color: @theme_selected_bg_color;
    color: @theme_selected_fg_color;
    text-shadow: none;
}
```
This is the same that nemo use for the desktop.
@lukefromdc 
thoughts?
@Gnalldo 
You can add those lines to /usr/shar/themes/ BlackMate/gtk-3.0/other-applications.css

**Comment by JosephMcc** [comment]
So I just tried this in MInt18 using mate-themes installed from the repos, which is 3.18.1.
Adding the following lines sorts the issue:

`NemoView .view .entry:selected {
    background-color: @selected_bg_color;
    color: @selected_fg_color;
}`

You are overriding your entry theming in NemoView .view .entry and then not supplying any theming for :selected.

**Comment by lukefromdc** [comment]
I have only worked on the GTK 3.20 and GTK 3.22 versions of BlackMATE, not the GTK 3.18 versions from which I ported them. Working on anything GTK 3.18 is a hassle now because I've got a lot of GTK 3.20 specific builds-plus a GTK 3.21/22 specific build of Caja.

**Comment by raveit65** [comment]
np, i've 3.18 running in a VM and out themes are mainly ready for 3.18, so only minor adjustments are needed like this. I will correct this.

**Comment by raveit65** [comment]
done https://github.com/mate-desktop/mate-themes/commit/ad475056140b5ea0d398c15445fa6dabe9419306
Dear reporter, thank you for reporting that and please copy those lines in
/usr/share/themes/BlackMate/gtk-3.0/other-aplications.css for the moment and reload the theme.
