### ISSUE TITLE
mate-terminal scrollbars with Ambiant-MATE have very bad contrast

### ISSUE THREAD

**Issue by arxo** [mate-desktop/mate-themes#135]
I am using the Ambiant-MATE theme from MATE 1.14.1 (from the offical ppa) with Ubuntu MATE 16.04.1. Most of the scrollbars look reasonable with this theme, except for mate-terminal, which is essentially "dark grey on dark grey", so it's very hard to see the scrollbar thumb.

From left to right: Caja, mate-terminal, Firefox
![bars](https://cloud.githubusercontent.com/assets/19519657/17461359/578fa914-5c8a-11e6-92cf-d98ad7239bd9.png)

Note: I slightly customized the theme by giving it larger left/right/bottom edges, but otherwise it is stock. Those modifications do not affect the scrollbars.

**Comment by raveit65** [comment]
Ambiant-Mate is a Ubuntu theme and not part of mate-themes.

**Comment by arxo** [comment]
Sorry, wasn't aware of that - going to repost on launchpad then.
