### ISSUE TITLE
BlueMenta GTK3 Firefox rendering issue

### ISSUE THREAD

**Issue by evitalis** [mate-desktop/mate-themes#136]
I have found two issues with the BlueMenta theme, which is the default in Fedora 24 at least, relating to Firefox.

First, when right clicking text you hover over becomes white in the menu. I see this on both Fedora 24 with Firefox 47 and Arch with Firefox 48. I will have to double check on this but it may also apply when right clicking other applications such as Network Manager, I can update on this point after some further testing but Firefox is the most obvious example.

Second, on at least Fedora 24 radio button and checkbox selections do not render. The dot is still empty along with the checkbox. I have not had opportunity to find this on Arch but see it on Fedora.

On my Fedora system I pulled the latest code from this git repo and replaced the gtk-3.0 subdirectory for BlueMenta without success. This included logging off the system and restarting the Firefox application. The Arch installation is clean with no Firefox theme changes. Fedora is an upgrade from 23 to 24 but again no Firefox or MATE theme customizations.

Let me know if any additional information is needed from either system and I will post it for review.

**Comment by raveit65** [comment]
screenshot from fedora installation?

**Comment by raveit65** [comment]
> First, when right clicking text you hover over becomes white in the menu. I see this on both Fedora 24 with Firefox 47 and Arch with Firefox 48.

This is correct but the selected menuitem bg color should be blue.
Fixed with ff 49 from stable fedora repo.

> Second, on at least Fedora 24 radio button and checkbox selections do not render. The dot is still empty along with the checkbox.

Check and radio buttons render fine here with ff 49 in menu 'view'.

Sorry, not a theme issue.
Honestly, i do not understand why your guys always filing out bugs here and not against firefox which is the real culprit and a mess with gtk3 ;)
Same for LibreOffice.

**Comment by lukefromdc** [comment]
Second this: Fireefox is almost impossible to work on and all dark themes
have trouble with it. Firefox 49 is worse than ever, creating issues even in
my own mixed dark and light theme and might force me to use a fulltime
userChrome.css file.
