### ISSUE TITLE
No padding in tabs with Menta theme

### ISSUE THREAD

**Issue by royale** [mate-desktop/mate-themes#137]
Some applications do not have padding around text in tabs making them very compact.

Example with "pavucontrol" application:

![screenshot at 2016-08-30 01-42-36](https://cloud.githubusercontent.com/assets/80380/18071437/03a81074-6e56-11e6-86a6-af948229843e.png)

I am using Mate from Debian unstable with the Menta theme:
mate-desktop                          1.14.1-1
mate-themes                           3.20.8-1

Thanks

**Comment by raveit65** [comment]
mate-themes 3.20.8-1 is not the latest package where this is fixed.
