### ISSUE TITLE
Green-Submarine 3.20.10 lightdm gtk greeter top panel has white borders

### ISSUE THREAD

**Issue by geki-yaba** [mate-desktop/mate-themes#140]
Since mate-themes-3.20.10 there are white or lightgrey borders around the top panel widget.

x11-misc/lightdm-1.19.4::gentoo  USE="gtk introspection -audit -gnome -kde -qt4 -qt5"
x11-misc/lightdm-gtk-greeter-2.0.1-r1::gentoo

**Comment by raveit65** [comment]
screenshot?

**Comment by geki-yaba** [comment]
Sure, I finally found out how to capture.

![lightdm](https://cloud.githubusercontent.com/assets/13393125/18641126/7f2ebcb6-7e9b-11e6-968f-ce4f4bd8fbfe.png)

**Comment by raveit65** [comment]
Ok, i got it.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-themes/commit/ea4b9cad7fb406bbf172f43b507432a860b177c5
Should be fixed by this commit , created with lightdm-greeter-1.8.5.
All is dark now.......

**Comment by raveit65** [comment]
for lightdm-gtk-2.0.0 you need this commit too for eliminating the separator lines.
https://github.com/mate-desktop/mate-themes/commit/6557c036d6132a2082e202d9adb39359c6b28229

**Comment by raveit65** [comment]
btw. i released 3.20.12 today
http://pub.mate-desktop.org/releases/themes/3.20/

**Comment by geki-yaba** [comment]
Thank you, looks good now.

**Comment by geki-yaba** [comment]
Actually, box-shadow does not work for #login_window.background.lightdm-gtk-greeter box.vertical

I commented out that line and some "corrupted pixel" at the edges are gone.

**Comment by lukefromdc** [comment]
I just tested todays's git master, very nice work on the calendars and the Submarine themes now have spectacular calendars

**Comment by raveit65** [comment]
> Actually, box-shadow does not work for #login_window.background.lightdm-gtk-greeter box.vertical
I commented out that line and some "corrupted pixel" at the edges of login_window are gone.

Thx, i will checked that.

**Comment by raveit65** [comment]
Yeap, it looks much better now. I guess we have no compositor in lightdm session.
https://github.com/mate-desktop/mate-themes/commit/94140a99c83aba14bdb5e5d02cdb3c0c24c380a6
Thank you
