### ISSUE TITLE
Green-Submarine 3.20.10 libreoffice menubar light text on light bg

### ISSUE THREAD

**Issue by geki-yaba** [mate-desktop/mate-themes#142]
x11-libs/gtk+-3.20.9
app-office/libreoffice-5.1.5.2

See video: http://geki.selfhost.eu/hacks/green-submarine_libreoffice_menubar.mkv

**Comment by Safari77** [comment]
It could be a bit lighter, or the gradient could be a bit different, it's ok for 1920 px wide windows, but..

![green-submarine-chrome](https://cloud.githubusercontent.com/assets/3876865/18748687/17c93130-80dc-11e6-85fd-334ed1e2d73a.png)

**Comment by raveit65** [comment]
With
```
[rave@mother ~]$ rpm -qa libreoffice-writer
libreoffice-writer-5.1.5.2-6.fc24.x86_64
[rave@mother ~]$ rpm -qa gtk3
gtk3-3.20.9-1.fc24.x86_64
[rave@mother ~]$ rpm -qa mate-themes
mate-themes-3.20.11-1.fc24.noarch
```
menubar looks like this in f24.
![bildschirmfoto zu 2016-09-24_15-59-50](https://cloud.githubusercontent.com/assets/961604/18808926/f9cbe142-826f-11e6-846c-c384005d4eb0.png)
Not perfect but there is a different, i guess libreoffice is patched in fedora for gtk+-3.20.
Problem is that libreoffice and firefox lacks of support 3.20 and gtk+ development is to fast for them.
Also it isn't possible to debug lo with gtk3-inspector.
So it is very hard to find the right style classes for a theme dev.

**Comment by geki-yaba** [comment]
Good idea, I will check fedoras source repository for gtk-3.20 patches to libreoffice.

**Comment by geki-yaba** [comment]
Ok, found it. For whatever reason, the correct way did not work for LibreOffice developer back in February. Setting context to mpMenuBarStyle in GtkSalGraphics::drawNativeControl shows the menubar themed finally! See:

https://cgit.freedesktop.org/libreoffice/core/tree/vcl/unx/gtk3/gtk3salnativewidgets-gtk.cxx?id=8f96e87c890bf8fa77463cd4b640a2312823f3ad#n1385

**Comment by geki-yaba** [comment]
LibreOffice bugreport:
https://bugs.documentfoundation.org/show_bug.cgi?id=102909

**Comment by lukefromdc** [comment]
The formula bar in Libreoffice calc and a lot of the preferences dialogs are bad too with GTK 3.22 (probably 3.20 as well) -bad enough that I had to uninstall GTK3 support and revert to Debian's GTK2 support package to get my mixed light and dark theme to work. At this point Libreoffice does not properly support GTK 3.22 and I doubt it works right in 3.20 either because that's when the big theming changes came in.

Worst case if this was never fixed for GTK 3.22 and GTK2 no longer supported would be this: remove the GTK support package so Libreoffice falls back to its default theme to make the preferences dialogs work, set custom colors for everything, then reinstall the theme support. Repeat as needed to fix anything you missed.

**Comment by geki-yaba** [comment]
Sad to see LibreOffice will not fix their gtk issue(s) ...

**Comment by geki-yaba** [comment]
The formular bar in LO Calc and the preferences dialogs are not themed but default LO lightgrey background and black text. Only things with visual artifacts are edit fields where text starts on border (without margin) and spin buttons with '+'/'-', which have no border and look scaled or such. So, I am quite happy with my patched LO.

**Comment by lukefromdc** [comment]
Yet, if I try to use Libreoffice with GTK3 integration with my mixed light and dark theme (UbuntuStuido_Legacy: otherwise dark theme with light views) I get white on white in the formula bar. Didn't used to, this has only been for maybe a month. Gave up, switched Libreoffice to GTK2 integration.

**Comment by fitojb** [comment]
> Sad to see LibreOffice will not fix their gtk issue(s) ...

Sad to attack a developer community which fixed issues on a volunteer basis...
