### ISSUE TITLE
Submarine themes, GTK 3.22: calendar text too light, barely readable.

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-themes#143]
While testing https://github.com/mate-desktop/mate-panel/pull/483, I noticed that the text in mate-panel's calendar was extremely light with both blue-submarine and green-submarine and hard to read. Darkening the text a bit would make the calendar far more usable. Using GTK 3.22 and since GTK 3.20 uses the same theme syntax I am assuming the problem exists there too.

![calendar_green_submarine_gtk3 22](https://cloud.githubusercontent.com/assets/14036792/18941923/3989e79a-85e3-11e6-810e-47e47dbfcb2e.png)

**Comment by raveit65** [comment]
Found a solution for it. I will also use a border-radius for top corners,  which is better for the bottom panel.

**Comment by Safari77** [comment]
In other themes the day numbers of months which do not belong to current month have different font, but that is not the case with Submarine themes.

**Comment by raveit65** [comment]
> In other themes the day numbers of months which do not belong to current month have different font, but that is not the case with Submarine themes.
Which theme and version?

**Comment by Safari77** [comment]
Green-Submarine 3.22.3

**Comment by raveit65** [comment]
LOL,
I meant with which other themes you see different fonts?

**Comment by Safari77** [comment]
For example Glossy theme has darker and bolder font current month's days.
![glossy](https://cloud.githubusercontent.com/assets/3876865/18951305/32c48022-864d-11e6-9638-5a17a9d04db0.png)

**Comment by raveit65** [comment]
Do you have a link to  upstream?

**Comment by Safari77** [comment]
Nope.

**Comment by raveit65** [comment]
Than i can't fix it as GtkCalendar is very limited and gtk3-inspector shows me only 'calendar' as css selector.

**Comment by raveit65** [comment]
Btw. Submarine themes use selected bg color for weekdays and weeks, so this isn't really needed.

**Comment by raveit65** [comment]
Forget what i said....i can :)
