### ISSUE TITLE
BlackMATE has unreadable inputs in Firefox

### ISSUE THREAD

**Issue by aykevl** [mate-desktop/mate-themes#144]
Many input fields have unreadable text in Firefox, using mate-themes 3.22.2 (Debian stretch/stable) and Firefox 48.0b1.
I think the cause is that many websites assume that input fields (and textareas) have a light background and a dark text content. When they style one of the two (e.g. setting the text to dark gray via `color: #333`), the text becomes unreadable due to low contrast between text and background.

Even though this is a dark theme, I think it should set input text color and background to an expected value in Firefox (black text, light background) so websites will render correctly.
Chrome does this and it looks much better.

Example in Google Docs (top left filename):
![screenshot at 2016-09-29 15-00-32](https://cloud.githubusercontent.com/assets/729697/18955254/e081afe2-8656-11e6-9784-5a4774b61827.png)

Example on a [different site](http://www.d20srd.org/extras/d20dicebag/) (Roll History). The left entries look OK, though the dark inputs are a bit out of place. The text in the right textarea is barely readable, however:
![screenshot at 2016-09-29 15-20-49](https://cloud.githubusercontent.com/assets/729697/18955580/52182ea0-8658-11e6-8cc1-6bffdd08f905.png)

Note: this has been an issue for a long time already. It also occurs in Debian jessie (mate-themes 1.9.2, Firefox 45.4).

Additionally, the scrollbars look a bit out of place (e.g. in the GitHub textarea for reporting bugs), but that does not hamper usability.

![screenshot at 2016-09-29 15-35-03](https://cloud.githubusercontent.com/assets/729697/18956071/54084c2a-865a-11e6-9f66-f2f37e77d978.png)

**Comment by raveit65** [comment]
Sorry, debian firefox bug.
I don't see that with ff-0.49 in fedora

**Comment by lukefromdc** [comment]
One other point here:if you switch themes to BlackMATE from a light
theme while Firefox is running, you get the unreadable dark text. If 
you then restart Firefox you get white text on the dark background.
If you then change themes to a light theme you now have unreadable 
white on white text. This is a Firefox bug in which a theme is only 
partially applied on theme change, forcing a Firefox restart if you
want the theme to work.

**Comment by aykevl** [comment]
@raveit65  No, the same issue happens with vanilla Firefox (downloaded directly from mozilla.org and verified the version, 49.0.1). So the Debian modifications to Firefox are not the cause.

@lukefromdc This is also not an issue with partially applied styles (without restart): I've restarted Firefox now several times (I wouldn't file an issue if that were the problem - or file it directly to Firefox).

**Comment by lukefromdc** [comment]
Some theme elements in Firefox can be themed, some cannot be. GtkInspector does not work. Firefox and Libreoffice are nearly impossible to theme and both get lots of reports of problems with dark themes. This is due to only partially using GTK. In the case of Firefox, if you use GTK_DEBUG=interactive firefox to force GtkInspector to show, you get an unnamed toplevel window and little else.

**Comment by lukefromdc** [comment]
Further point: the ONLY way to single out a theme change for Firefox only is to put in in a ~/.mozilla/firefox/<something>default/chrome/userChrome.css file usng Mozilla's syntax. I don't think Mozilla has even ported Firefox properly to GTK 3.20 yet, same thing has been reported for Libreoffice

**Comment by raveit65** [comment]
> @raveit65 No, the same issue happens with vanilla Firefox (downloaded directly from mozilla.org and verified the version, 49.0.1). So the Debian modifications to Firefox are not the cause.

All, i know is that ff is heavily patched in fedora for gt+-3.20, maybe debian missed some important patches?
Again, the problem is that ff isn't ready for gtk3 and their development is to slow for gtk+.
File out a report there or compile against gtk2 and try again ff gtk3 in 2 years again.

**Comment by aykevl** [comment]
Ok, so I understand this problem is hardly (if at all) fixable in MATE? Then I'll close this bug.
