### ISSUE TITLE
BlackMATE: Gitg source view doesn't show in monospace font

### ISSUE THREAD

**Issue by derkolja** [mate-desktop/mate-themes#145]
https://github.com/derkolja/mate-themes fixes this, but probably not in a way that you might accept. Sorry, i'm not much of a gui hacker. :)

Running an Arch Linux here.

**Comment by lukefromdc** [comment]
I don't have any font named "Hack" installed in my system. What exactly does this do?

**Comment by derkolja** [comment]
Just use any monospace font you have installed. Maybe there is a way to
reference the theme's/the user's monospace font. If I don't set it here,
gitg doesn't use monospace for diffs.

**Comment by lukefromdc** [comment]
I didn't see any adverse effects in a test on gnome-terminal or on 
Gedit (GNOME applications I have) but also am not sure where you
originally saw this.

i DO have an issue in my own UbuntuStudio_Legacy theme where I get
invisible test on mate-terminal unless it is custom set (I normally custom set 
the terminal theme as the terminal profile) so I had to warn other users to set
a custom terminal theme. Maybe this sort of thing wil work there?

Been so busy chasing other issued didn't have much time to dig into that on
my own theme

**Comment by derkolja** [comment]
I only ever saw this with gitg, the git viewer tool. There is no custom
theming involved.

**Comment by lukefromdc** [comment]
I've been using the tk based gitgui for that job, so obviously I haven't seen this issue. My main concern with this is what exactly does using "hack" as a specified font do?

**Comment by derkolja** [comment]
"Hack" is just my preferred monospace font at the moment. I suppose it
doesn't matter much which font to use here, gitg apparently just needs that
.monospace key in that gtk.3.0/gnome-applications.css file, telling it what
font to use for monospace.

**Comment by lukefromdc** [comment]
try https://github.com/mate-desktop/mate-themes/commit/362d9b55d64090336d493516f71be996b8fe6467 , which specifies simply "Monospace" as the font-family for .monospace. That's what comes up as available on my system, we want to specify something that users will already have installed. With GTK 3.22 you can't just specify "font" without getting error messages, "font-family" is used for which font you are using. There are other properties such as "font-size" as well, the old Pango syntax is no longer supported.

**Comment by derkolja** [comment]
Ah yes, I suspected just specifying a nice font wouldn't be the way to go in real life. :) 

That does fix it for me. Thanks for looking into this!

I also noticed all themes have that issue. Some of the stock arch linux themes worked for me, but none from the repo. If that is a viable fix for you, I updated the other themes as well in https://github.com/derkolja/mate-themes

**Comment by raveit65** [comment]
done for all themes!
