### ISSUE TITLE
Green-Submarine 3.20.12 mate-screensaver lock screen dialog not themed

### ISSUE THREAD

**Issue by geki-yaba** [mate-desktop/mate-themes#146]
I wonder if mate-themes or mate-screensaver project is responsible. Sorry, if I am wrong. See image:
![mate-screensaver lock dialog](https://cloud.githubusercontent.com/assets/13393125/19417549/01a47482-93b0-11e6-8b90-8ac4dd0f9e8e.png)

**Comment by raveit65** [comment]
The dialog is themed otherwise you won't see round borders.
Btw. what is wrong?

**Comment by geki-yaba** [comment]
The dialog is as light as the lightdm user dialog was before you fixed issue #140.
The dialog should have a dark background and light text with Green-Submarine.

Hmm, could it be that the lock dialog is gtk2?
Does it need the system gtk2 theme setting, instead of user-session theme?

Lightdm needs the system gtk3 theme setting.
Just wondering, because claws-mail is also gtk2 which is themed perfectly fine within user-session.

**Comment by raveit65** [comment]
The lock dialog is from mate-screensaver and i did not change the bg color like i did for lightdm.
So what you see here is correct.
Do you prefer a dark styling here?

**Comment by geki-yaba** [comment]
I would say it were consistent, but if there is a good reason to be light ...

**Comment by raveit65** [comment]
I don't think there is any reason to prefer a light or dark variant,
but in you case with a dark wallpaper you won't see the dialog very well.
Anyway, i can write some code lines for testing if i've some free time.

**Comment by geki-yaba** [comment]
On a second look at some dialogs, they actually have a light background ...
Although, I feel irritated every time seeing the light lock screen ... what the ...

Wrt the wallpaper, that is okay.

I guess, I may better have a look at how to tweak the lock dialog.
Could be added as an extra CSS one may add or not ... let's see ...

**Comment by geki-yaba** [comment]
Added a gist for the dark themed version of the lock dialog. I prefer the dark themed version, but I cannot judge, if it should be changed for the theme actually. Could be added to examples and explained in some document file?!

https://gist.github.com/geki-yaba/19262f9af9b2a6f838636e6f019e96a3

![lightdm](https://cloud.githubusercontent.com/assets/13393125/19419558/72540ede-93da-11e6-8816-ad30f30c96f9.png)

**Comment by raveit65** [comment]
Looks good, i'm fine with a dark style.
What do you think about?
https://gist.github.com/raveit65/b81b92e774274a182784006010bf3a60
Use it with 
@define-color theme_dark_dialog_bg_color #1C2723;
in gtk.css.
Of course i will adjust lightdm with bg color changes.

**Comment by geki-yaba** [comment]
Yes, looks good. Would be perfectly fine with me.

**Comment by raveit65** [comment]
done!
https://github.com/mate-desktop/mate-themes/commit/a46c7c363904f277b4aeb21ebd192d0887d3af3d
