### ISSUE TITLE
New frame in TraditionalOK/Green themes makes main menu hard to click on

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/mate-themes#148]
Debian Bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825653

The debian user says:

> Since version 3.20 of mate-themes, TraditionalOK and TraditionalGreen
> themes display a frame around some UI elements. I'm not sure it's
> intentional, since older versions didn't display this frame.
> 
> Aside of the aesthetic change, this frame has a huge (IMHO) drawback, as
> this frame is also present around the panel's main menu buttons
> (although not displayed). This makes the very top of the screen
> unclickable. This is really annoying because, when one tries to reach
> this menu, almost every time, the mouse cursor touches the top of the
> screen, and the click isn't taken into account. The mouse cursor has to
> be lowered a bit before clicking, which is really annoying.
> 
> I'm not sure it's intentional, since other MATE themes (Menta, etc)
> don't have this problem; hence the bug report.
> 
> Probably related : this new frame is now drawn around mate-terminal when
> it's maximized, but this problem is insignificant and doesn't deserve a
> bug report (but may be worth mentioning here).
> 
> Of course, if this isn't a bug but intentional behavior (which I
> strongly doubt since, as I said, other themes in the package don't
> suffer from this problem), feel free to close the bug.
> 
> Regards,

I can confirm, with traditional ok, and since mate 1.14 with gtk3, I hadn't that problem with mate 1.12 gtk2

![bugreport](https://cloud.githubusercontent.com/assets/7734191/19757719/ac0764ee-9c24-11e6-9d61-54086b914e50.png)

![bugreport cgi](https://cloud.githubusercontent.com/assets/7734191/19757747/cb7d2d0e-9c24-11e6-8532-84636c07436f.png)

![bugreport cgi](https://cloud.githubusercontent.com/assets/7734191/19757758/da0837c4-9c24-11e6-9ea0-366a1440598e.png)

On the original debian bug, there are more images

**Comment by lukefromdc** [comment]
What version of mate-themes are you using? I did not get this with mate-themes updated Oct 20 from master and GTK 3.22

**Comment by raveit65** [comment]
menubar menuitem use a padding for 1px in general. For the panel top and bottom padding are zero.
See https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/gtk-3.0/gtk-widgets.css#L2297
and
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/gtk-3.0/mate-applications.css#L128
So saying that it's hard to click on the menuitem is a great word :)
For me it's harder to hit the 1px padding on the left side of the menuitem where a click does nothing ;)
Any ways, i will remove the left padding.
Also  i will remove the border on 'frame' selector and will use .frame instead, like it was before gtk+-3.20.
For GtkNotebook there was more than a syntax change with 3.20, in result i can only set a border for the whole notebook. Removing that only from notebook header is impossible with 3.20.

**Comment by sc0w** [comment]
@raveit65 thanks, please see the difference:

traditional ok

mate 1.8

![mate 1 8 - no outlines](https://cloud.githubusercontent.com/assets/7734191/19782189/0f77ecca-9c8d-11e6-927f-0fd2db1ad103.png)

and now, latest mate-themes master branch:

![preferencessound](https://cloud.githubusercontent.com/assets/7734191/19782233/2ad5ce74-9c8d-11e6-815a-e8a37f640cca.png)

the differences:

![image3344](https://cloud.githubusercontent.com/assets/7734191/19782247/36281c6e-9c8d-11e6-9962-fd7c98d3ff3f.png)

**Comment by lukefromdc** [comment]
Are the borders around the entire windows left over from how you did the screenshots (over a dark background presumably)  or are those black window borders and square top corners actually rendered on your desktop? If every window is looking like that around the decorations that would indicate a window manager issue (marco if the default has not been changed).

The circled change is something that cannot be changed in GTK 3.20 or later other than (as stated before) removing the entire frame around the whole notebook, all the way around. An exact match of any GTK 3 version and especially newer ones to GTK2 is impossible. As an example, I prefer the GTK2 file picker's appearance in my theme  but can't match the old version entirely in GTK 3.14 or later no matter how much I try. In 3.20 or later the alternating rows can't be done so every row has to get a gradient instead.

**Comment by sc0w** [comment]
@lukefromdc you can forget the borders, is a bad capture by me xD

thanks for the info :)

@raveit65 can you apply https://github.com/mate-desktop/mate-themes/commit/fac11a041f2830a5c56b8aed75fffe2107db787a to traditional green too?

**Comment by raveit65** [comment]
Opps, i forgot TG :)
