### ISSUE TITLE
Errors in mate-applications.css

### ISSUE THREAD

**Issue by LaurentBonnaud** [mate-desktop/mate-themes#155]
Hi,

all MATE applications (and all GTK3 applications) display the following error messages:
```
$ eom
[...]
(eom:26021): Gtk-WARNING **: Theme parsing error: mate-applications.css:214:16: not a number

(eom:26021): Gtk-WARNING **: Theme parsing error: mate-applications.css:214:16: Expected a string.
```
More details here:
https://bugs.launchpad.net/ubuntu/+source/mate-themes/+bug/1652634

**Comment by raveit65** [comment]
Without telling us which theme causes this warnings the report is pretty useless :-)

**Comment by lukefromdc** [comment]
This looks like a GTK 3.20 theme with GTK 3.22-or a theme with a missing font update for GTK 3.22. The font setting code changed for 3.22

**Comment by raveit65** [comment]
No answer from reporter!

**Comment by LaurentBonnaud** [comment]
Sorry for not answering sooner, there are so many bugs out there  that it is difficult for me to answer quickly.
The problem was caused by using a MATE PPA for Ubuntu xenial on an Ubuntu yakkety system.
Purging the PPA solved the problem.

**Comment by flexiondotorg** [comment]
Still not specific enough. Which PPA did you add to Ubuntu MATE 16.10?

**Comment by LaurentBonnaud** [comment]
This PPA:

https://launchpad.net/~ubuntu-mate-dev/+archive/ubuntu/xenial-mate

**Comment by flexiondotorg** [comment]
OK, then you really went out of your way to add a PPA that only includes packages for Xenial to a Yakkety install 😉 

Not a bug.

**Comment by LaurentBonnaud** [comment]
> OK, then you really went out of your way to add a PPA that only includes packages for Xenial to a Yakkety install 😉

In fact my system had this PPA when it was xenial.  When I upgraded it to yakkety I left the PPA active in the hope to have a more recent MATE version.

> Not a bug.

Agreed.
