### ISSUE TITLE
Missing window border on some themes

### ISSUE THREAD

**Issue by direwolfie** [mate-desktop/mate-themes#158]
Hi everyone,

Window borders are missing on some of the themes:
![Something missing](http://pix.toile-libre.org/upload/original/1484376033.png)
![Theme borders missing](http://pix.toile-libre.org/upload/original/1484376394.png)
But as you can see this does not happen only to the Menta themes but also other themes.

I tried rolling back to the previous versions of the updates after this happened but with no luck. :(
Can you please advise what could be causing this? Or suggest, where can I look to investigate this issue further?

I am running Arch with Mate 1.16.1 and mate-themes 3.22.5-1.

Thanks!

**Comment by raveit65** [comment]
This happens only if something is missing in folder.
Can you compare  /usr/share/themes/BlueMenta/metacity-1/
with https://github.com/mate-desktop/mate-themes/tree/gtk3.22/desktop-themes/BlueMenta/metacity-1
?
The important files are the metacity xmls. And please check file permissions.
I used this tarball http://pub.mate-desktop.org/releases/themes/3.22/mate-themes-3.22.5.tar.xz
for fedora 25 and i don't see that here.

**Comment by direwolfie** [comment]
Thanks for the suggestion.
Permissions are fine. And all the files are there. So this is definitely not a mate-themes issue.
I guess that something probably broke with one or another Arch update... and I saw it too late to know which one.
