### ISSUE TITLE
TraditionalOK theme has tab issue

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/mate-themes#159]
My system: Fedora 25 (64bit) running MATE 1.16.1

I switched from BlueMenta to TraditionalOK theme to get rid of the menu transition effect. However I noticed that the tab area does not look right (the same issue was reported and fixed for other themes).
BlueMenta:
![bluementatabs](https://cloud.githubusercontent.com/assets/3275361/21986517/0344e5f4-dc00-11e6-99e8-692b518b123d.png)
TraditionalOK:
![traditionalok](https://cloud.githubusercontent.com/assets/3275361/21986521/04f493c2-dc00-11e6-858e-d45d15419937.png)

**Comment by lukefromdc** [comment]
That just looks like the intended styling of the tabs, the blue line is an accent to the active notebook tab.

BTW, you can edit themes locally (in your installed setup) to remove transition effects. Back up the files, then remove all the "transition" lines for starters. You are looking for lines like this:

` transition: all 400ms ease-out;`

You will have to re-do this after any theme updates, you can prevent that by copying and renaming a theme.

**Comment by raveit65** [comment]
For me the tab area looks briliant.
Only saying  'that the tab area does not look right' isn't sufficient.

**Comment by smikkelsendk** [comment]
Sorry for not being clear enough. 
I would have expected TraditionalOK theme to have more whitespace between tabs (both horizontally and vertically). I reported similar issue for BlueMenta before (https://github.com/mate-desktop/mate-themes/issues/130) that got fixed, but I can now see that it was slightly worse than TraditionalOK.

**Comment by smikkelsendk** [comment]
I have now tried changing gtk-widgets.css in TraditionalOK
The two top lines of notebook header.top.tab now looks like
`
notebook header.top tab {
    margin: 0px 0px 0px 0px;
	padding: 6px 6px 6px 6px;
`

In my opinion this makes it easier to click the individual tab and also looks more pleasing to the eye.
![traditionalok](https://cloud.githubusercontent.com/assets/3275361/22000132/d350ca3c-dc3d-11e6-84af-ed991a53066f.png)

If you think this change is in conflict with the Theme, you/I can close this issue

**Comment by raveit65** [comment]
Well, mentioned report was a problem with pavu-control and not a general problem with notebook tabs.
Personal i don't use use TOK theme as it is to boring without transitions effects, so i am complete passionless.
I can change the horizontal spacing of tabs if another developer which use that theme agree.
@sc0w 
What do you think?

PS: You can create a ~.config/gtk-3.0/gtk.css and add every selector to override theme settings as user.
Ie.
 ```
menuitem,
.menuitem {
    transition: none;
}
```

**Comment by sc0w** [comment]
I like TOK on gtk2 much more than gtk3

pluma preferences

gtk2

![plumagtk2](https://cloud.githubusercontent.com/assets/7734191/22004097/367cc604-dc59-11e6-96a6-aaac2e06a80c.png)

gtk3

![gtk3pluma](https://cloud.githubusercontent.com/assets/7734191/22004100/3c721776-dc59-11e6-95f0-b1418bf6e17d.png)

on gtk2 I like without changes, but gtk2 is the past

on gtk3 I agree with @smikkelsendk , it looks better with more whitespaces between tabs

and, one question, can we improve this like gtk2?

![detailspluma](https://cloud.githubusercontent.com/assets/7734191/22004486/299ac97e-dc5c-11e6-8428-3775e30f5e24.png)

**Comment by raveit65** [comment]
> and, one question, can we improve this like gtk2?

![detailspluma](https://cloud.githubusercontent.com/assets/7734191/22004486/299ac97e-dc5c-11e6-8428-3775e30f5e24.png)

Well, this was implemented by clearlook-phenix author, but it's stolen from adwaita in the end ;-)
Gtk-3 part of Traditional themes is forked from Clearlook-phenix.
Np, i can remove the blue stripe for active tab :-)

**Comment by raveit65** [comment]
> The two top lines of notebook header.top.tab now looks like
> `
notebook header.top tab {
    margin: 0px 0px 0px 0px;
	padding: 6px 6px 6px 6px;
> `

> In my opinion this makes it easier to click the individual tab and also looks more pleasing to the eye.
> ![traditionalok](https://cloud.githubusercontent.com/assets/3275361/22000132/d350ca3c-dc3d-11e6-84af-ed991a53066f.png)

Changing margin is a bad idea expect you like double vertical tabs borders :-)

**Comment by raveit65** [comment]
Done for gtk+-3.20/22 branches.
https://github.com/mate-desktop/mate-themes/commit/cffe88c88e748058de7917b260cf3181a5922329

**Comment by andreygursky** [comment]
Good time with compact tabs has gone. After this patch they became too big (vertically) again, which is unacceptable.

And I'm missing the blue stripe on top of the active tab.

P.S. Please use "fixes #number.of.bug" in commit message to make search for the corresponding bug reports easier. I was about to open a new bug, but have found the right one (this time).

**Comment by andreygursky** [comment]
I mean tabs like those in gnome-terminal (I don't have mate-terminal gtk3 atm.). It seems some padding is additionally appended there, which is not needed anymore.

**Comment by raveit65** [comment]
Guys can you really decide what you want?
Current poll:
2:1

I am not using it so i am really passion less and this old theme is only work for me.
Maybe someone wants to maintain it?
.... i can't hear that any more....i want this....and i want that.

**Comment by raveit65** [comment]
ps: you can hack every theme as user.
User settings belongs to
~.config/gtk-3.0/gtk.css

**Comment by andreygursky** [comment]
A little bit more or less is a matter of taste I agree. My issue is that tabs in terminal are really too big. Do you know, what css elements are used by it? These tabs are additionally stretched horizontally.

**Comment by raveit65** [comment]
In mentioned commit it's the padding setting here
https://github.com/mate-desktop/mate-themes/commit/cffe88c88e748058de7917b260cf3181a5922329#diff-3b89d6b7b0ad17249e5c6b73ad64e448R1788
notebook header.top tab {}

**Comment by sc0w** [comment]
> Maybe someone wants to maintain it?

I would like to maintain it, but my knowledge on mate-themes are very limited

**Comment by andreygursky** [comment]
@raveit65, thanks, I believe I found the missing thing and will make a PR.

@sc0w, the maintainer of TraditionalOK should be pretty conservative, since the theme's name is "traditional" (however some things seems worth to be slightly improved). Good feeling for this edge (between fix / slightly improve and improving tending to a change) is essential in my opinion. @sc0w, what do you think of not yet resolved issues, could you start with them?

**Comment by andreygursky** [comment]
Conservatism is needed only in respect to how the theme should keep looking, on the other hand one should be pretty agile to follow the upstream: there have been already 4 releases in 3.89 series. @sc0w, would you like to port TraditionalOk (and then others) to be supported there?

**Comment by lukefromdc** [comment]
When GNOME starts using GTK4 for GNOME apps, we'll need GTK4 support in themes. I have yet to be able to build GTK 3.89 hoever, because I cannot build graphene (a dependency) and nobody offers it for Debian Unstable last I checked

**Comment by andreygursky** [comment]
I mean, that not doing updates step by step as long as changes are small enough would result in a huge work afterwards nobody would even want to start with. Themes could be tested at least with gtk4-demo and gtk4-widget-factory.

I'm able to build graphene since about 02.12.2016 successfully on Debian testing. Last version I'm using is 1.5.4. Could you post, what fails for you?

**Comment by sc0w** [comment]
@andreygursky 
>  the maintainer of TraditionalOK should be pretty conservative, since the theme's name is "traditional" (however some things seems worth to be slightly improved).

I agree

> what do you think of not yet resolved issues, could you start with them?

yes, btw you can open new issue with your suggestions

**Comment by lukefromdc** [comment]
I have forgotten what went wrong since I last tried to build Graphene, might have been python issues but not sure

**Comment by smikkelsendk** [comment]
I agree that we should be conservative, so lets compare the current TraditionalOK from Fedora 25 to the version from Fedora 23.
(top: F23, bottom: F25)
![f25vsf23](https://cloud.githubusercontent.com/assets/3275361/23102488/6792eb90-f6aa-11e6-9ffa-45492831ff65.png)

I would say we are much closer to the F23 appearance, then we were before the changes (with regards to the tab spacing). However it might have been a mistake to remove the active tab indicator.

**Comment by raveit65** [comment]
For me the blue active tab indicator isn't conservative :-)
Historical tradititional themes are a fork from clearlooks gtk2 and the gtk3 part is a fork from clearlook-phenix.
And those dev added the blue active tabs which was copied from adwaita theme.
So if i am a smartass than i would say those active blue tab isn't traditional ;-)
..but again this isn't my decision any more :-)

Btw. but comparing gtk2 and gtk3 doesn't make any sense for me.
It's like comparing a normal car with a car from tesla ;-)

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-themes/pull/162

**Comment by mrnhmath** [comment]
I managed to get the GTK2 style of tabs by forking clearlooks-phenix, putting the "notebook" part from it on TraditionalOK's gtk-widgets.css and making changes from it. Will post a screenshot soon.
