### ISSUE TITLE
TraditionalOk GtkInfoBar missing borders

### ISSUE THREAD

**Issue by uoggegloo** [mate-desktop/mate-themes#161]
TraditionalOk is missing borders on the top, left, and right of GtkInfoBar. This makes the GtkInfoBar look odd in most applications, as there's only a border on the bottom, even though in most applications there's not a reason to treat the bottom differently -- see Google image search to see examples of how GtkInfoBar is typically used:
https://www.google.com/search?q=GtkInfoBar&tbm=isch

I've found the missing borders to be most noticeable in Firefox's RSS preview interface, as reported here (see bottom portion of screen capture in that bug):
https://bugzilla.mozilla.org/show_bug.cgi?id=1335474

**Comment by sc0w** [comment]
do you have some capture with the issue?

**Comment by uoggegloo** [comment]
are you asking about a screen capture? see yellow part in below screen capture:
![firefox-rss-preview-interface-gtkinfobar](https://cloud.githubusercontent.com/assets/25511597/23257973/1af46984-f994-11e6-9b8f-af7c7850b223.png)

the above is from the Firefox RSS preview interface -- the yellow box is styled with GtkInfoBar css, and has only a bottom border.

**Comment by raveit65** [comment]
Looks like (first, last, only) -child logic don't work here.
In general Infobars don't use borders but for last-child there is only the button-border set.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/gtk-3.0/gtk-widgets.css#L3763
```
infobar:last-child {
    /* only apply a border on the last infobar if
     * there's more than one packed in */
    border-bottom-width: 1px;
    border-style: solid;
}
```
You can start gtk3-inspector on ff like this.
[rave@mother ~]$ export GTK_DEBUG=interactive
[rave@mother ~]$ firefox

Than you will see that you get no infos about ff, as ff don't use GtkWidgets in favor of own gtk3 code.
Which makes it not easy to style something in ff.
But you can add the code above to css tab in inspector and change the selector in real time.
As far i know GtkInfobars are used by filemanagers normal, ie. if you start nemo as root.
So check there if you change something.
Sadly ,ff does not have a own selector any more to style only ff.
```

**Comment by raveit65** [comment]
Yes, the red area in nemo is a GtkInfoBar
![nemo](https://cloud.githubusercontent.com/assets/961604/23259627/54949350-f9ce-11e6-89a3-24d8f75e9a2f.png)

**Comment by uoggegloo** [comment]
the issue isn't specific to firefox.

i saw the CSS comment, "only apply a border on the last infobar if there's more than one packed in" -- I did notice that it's not doing what it says it should, but more than that, what it says it should do doesn't make sense to me ... i don't know why only the bottom would get a border in any case, much less does it make sense to me if the bottom only were to get a border if it was the last of multiple stacked infobars? (why should the last of a series get a bottom border while a lone infobar wouldn't?)

the only reason i would see for only the bottom to get a border is if the bottom needed a visual separation that's not applicable to the top and sides (basically if the infobar were always pressed up against some other border on the top and sides but not the bottom) -- but based upon my own observations, that is rarely (if ever) the case. most of the time i see gtkinfobar, it's in the middle of a grey area with space around it and would look best with a border all the way around it. examples include the firefox screen capture above (where it would look better with a border all the way around), and the following screen capture from a Google Image search:
![infobar png en](https://cloud.githubusercontent.com/assets/25511597/23273972/13fe8836-f9cf-11e6-97a7-105e0751e9d6.png)

the above image shows the infobar as I most often see it (in a grey area with space around it), but as I'd expect it should be (with borders all the way around, instead of only on the bottom).

i can't think of where the infobar would look bad with the border going all the way around, but there are plenty of examples where it looks silly to have the yellow box in the middle of an empty space with only a bottom border. it is my suggestion that the border should go all the way around. i think even removing the border entirely (not my first choice) would make more sense than adding only a bottom border. what do you think?

**Comment by raveit65** [comment]
The comment is from clearlook-phenix author, we copied the gtk3 part from there.
Honestly, i have no idea for what this is good for.
I agree that it looks better with a border.
If possible we need more real example where it is used.
It can be a problem if the GtkInfoBar is inside another box which have also a border, than you see double borders.
I only mention that because 'double borders' in applications was one of the biggest problems with the theme port from gtk+-3.18 to 3.20.
Well, we added to all our apps a selector at top to make it possible to style only that application.
So we can fix a possible fallout if we use a border for the infobar to fix ff.

**Comment by raveit65** [comment]
Adding this before line https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/gtk-3.0/gtk-widgets.css#L3763
helps.
```
infobar, /*middle*/
infobar:first-child,
infobar:only-child {
    border-width: 1px;
    border-style: solid;
}
```
But i am not really sure if we need here the first/last/only logic, because if we have more than 2 infobars in vertical direction, the middle infobar should be borderless at top and bottom.
So using this logic in a theme w/o having a practical example is bad, imo.

**Comment by uoggegloo** [comment]
that does look better from what i can see....

you're looking for an example of what? stacked infobars? i've never actually seen stacked infobars, although i was able to find this screen capture in google:
![numix-infobars](https://cloud.githubusercontent.com/assets/25511597/23307268/ecda6ec2-fa74-11e6-838f-5d456298fa68.png)

if you zoom-in, it's clear that, in that particular theme, borders for middle infobars aren't treated any differently.

anyway, the "problem" (matter of opinion) with full borders around stacked infobars is that the border between touching infobars would appear as double the normal border width. see html mockup demonstrating this problem:
http://codepen.io/anon/pen/ryaBoe?editors=1000

a solution is to remove only the bottom border (border-bottom: 0;), and then add a bottom-border only to the last infobar (div:last-child {border-bottom: 2px solid red;}). see mockup with this solution applied:
http://codepen.io/anon/pen/KWwPJP?editors=1000

this solution even works pretty well with infobars of different types; see mockup (based upon screen capture above (screen capture is apparently from numix theme)):
http://codepen.io/anon/pen/KWwKWz?editors=1000

note that the solution doesn't require first-child or only-child selectors, only a last-child selector.

even without the solution, leaving full borders around all of them doesn't look so bad:
http://codepen.io/anon/pen/EWaxvb?editors=1000

this way doesn't require first-child, last-child, or only-child selectors.

on the other hand, the idea of leaving top and bottom borders off entirely on middle infobars doesn't make much sense to me, because then there would be no visual distinction between infobars of the same type:
http://codepen.io/anon/pen/KWwKQg?editors=1000

doing it this way requires first-child and last-child selectors.

anyway -- back to your comments -- "It can be a problem if the GtkInfoBar is inside another box which have also a border, than you see double borders" -- i'm not really sure this is a big deal, because normal borders are generally a shade of grey, whereas infobar borders are just a darker shade of the infobar's background color. compare mockups ...
http://codepen.io/anon/pen/VpYYyL?editors=1000 (other border around borderless infobar)
http://codepen.io/anon/pen/pevvKK?editors=1000 (other border around fully bordered infobar)

the difference is barely noticeable, because the infobar border seems like a transition into the infobar background color.

**Comment by raveit65** [comment]
I found an example in gtk3-demo where i could  play a bit.
But i am really in doubt that first/last/only logic will work here with gtk+-3.22.
So i will push an easy solution with borders at all places.

**Comment by uoggegloo** [comment]
awesome -- thanks!
