### ISSUE TITLE
should gtk2 parts of themes be updated to match the gtk3 parts for consistency? (mainly padding)

### ISSUE THREAD

**Issue by kn00tcn** [mate-desktop/mate-themes#164]
in several of the themes, tooltips/input fields/menus have more padding in gtk3 than in gtk2

given that it's extremely likely that a user will have a set of applications with a mixture of gtk versions, wouldnt it make sense to bringup the gtk2 styles to match the gtk3 ones so that mixed applications will look more similar?

i was flipping through various themes both mate's & third party, i noticed gtk2 tooltips/input fields/menus are capable of having similar sizes as mate's current gtk3 themes, so it seems possible

i can look into some or all of this so i dont cause extra work for the team (do mention things i should look out for, such as 'app X uses a different selector that wont automatically pick up the generic change')

**Comment by raveit65** [comment]
I do not agree that gtk3 should look like gtk2.
Gtk3 is big chance to make look themes better because you have much more opportunities to tweak them.
Feel free to tweak gtk2 part to follow gtk3.
Sorry, gtk2 is dying

**Comment by kn00tcn** [comment]
i did not say gtk3 to look like gtk2, only gtk2 to adjust towards gtk3 in the most jarring areas (without trying to limit gtk3 or anything of course)

when various parts of mate (or the distro) moved from gtk2 to gtk3, some padding or borders increased or appeared, so what i want to do is add that same padding or border to the gtk2 version so it's one unified theme

i'm not thinking about gradients or effects yet, only the most obvious geometry or skeleton... even if it's ONLY on input fields & tooltips, it will be a great improvement, here is a screenshot of menta currently:

![kn-gtk3vsgtk2-menta](https://cloud.githubusercontent.com/assets/8087411/23697370/8732ee42-03b5-11e7-9c44-f3af7b0abbf8.png)

**Comment by raveit65** [comment]
This was not an error :-)
For me it looks better with more space, for this reason i changed that.
Feel free to adjust gtk2 to follow gtk3

**Comment by raveit65** [comment]
Btw, the issue is that deprecated gtk2 applications aren't ported to gtk3.

**Comment by kn00tcn** [comment]
yes, it does look better with more space, so i wondered why gtk2 wasnt updated to have the new ideas if it's still the same theme

some apps might never get an update, while others have a lot of work that will take a year or more (i think that's what gimp was saying), so i definitely want to follow the gtk3 parts while everyone waits for updates

i will try making some changes sometime

**Comment by mrnhmath** [comment]
ins't this defined by theme? if so e.g TOK should match the original clearlooks at the possible

**Comment by raveit65** [comment]
Why, because original clearlooks i what you like ?
I tell you something, working on themes is like painting or other arts.
It works only if you like it or you have fun with that art progress.
Feel free for stepping in if you don't agree with me.

**Comment by kn00tcn** [comment]
there are still principles based on psychology, art is not total chaos or fully subjective

interface themes have one more job beyond being pleasing, they have to avoid getting in the way or making it hard to use, so actually the larger padding in the gtk3 versions increases usability & that's why i want to do the same to gtk2 versions

if for example a separate 'menta-modern' was made with the larger padding separated from 'menta', then this thread wouldnt exist, so my point is simply unifying the 'brand' of a theme

anyway wait for me to test & make screenshots

**Comment by kn00tcn** [comment]
i've got a few of these changes going, but think i need to do a few per app fixes, also not sure which widgets are in use at times

would you like one large commit or several individual commits? (such as one for menu items padding, one for tabs padding, one for tooltips padding, etc)

**Comment by raveit65** [comment]
I like several commits to review.

**Comment by raveit65** [comment]
Mate use gtk3 since a long time.

**Comment by kn00tcn** [comment]
this wasnt about mate, this was about running other apps with a mate theme

but as you can see, i've been terribly lazy, the main thing i wanted was padding in menu items

eventually sublimetext switched to gtk3 making the modifications not very important

i've forgotten if geany has gtk3 yet (never used it after 2016), audacious is still gtk2 but not too big of a deal
