### ISSUE TITLE
XFCE: at least menta breaks inactive window backgrounds on at least pcmanfm, yumex-dnf, & edit connections list

### ISSUE THREAD

**Issue by kn00tcn** [mate-desktop/mate-themes#172]
so i grabbed the latest master zip & extracted the bluementa folder for easy editing in my /home/.lthemes/ location, this should work, right?

currently in xfce but i dont think this matters for individual apps, was flipping between f25's installed version & the master, but it seems to do it when flipping from any theme to the master one

pcmanfm, yumex-dnf, & the edit network connections list lose their white #f7f7f7 background, it turns into #c8c8c8 (also pcmanfm's horizontal divider in the side panel goes from #bfbfbf to broken #2c2c2c, actually the edit network connections seems to turn into #c3c3c3 specifically)

plus, xfce-terminal has a 1px border on the left/right/bottom of the window when it shouldnt, do i need to make a new issue or maybe i can find out how to fix this unrelated one myself & commit

otherwise i do see the new improvements such as tab containers or whatever kind of headings that xsensors uses

**Comment by raveit65** [comment]
Please post screenshots.
I am not sure if theme in home folder override installed theme in /usr/share/themes.

**Comment by raveit65** [comment]
And if you test versions from git please use the gtk+-3.22 branch, because we create tarballs from branches an not from master.

**Comment by raveit65** [comment]
> currently in xfce but i dont think this matters for individual apps, 

This is important, is it possible that we see the **backdrop** state here, which use another styling as normal windows?
Marco WM don't support this in result you don#t see that in mate-session.
Last and not least do you see that in mate-session?
Because i can't reproduce that in mate-session with latest release.
```
[rave@f25 ~]$ rpm -qa mate-themes
mate-themes-3.22.8-1.fc25.noarch
```

**Comment by raveit65** [comment]
Ok, this isn't a bug.
Installing metacity-3.22.x from https://copr.fedorainfracloud.org/coprs/yselkowitz/gnome-flashback/
gives me the same result in mate-session.
What we see here is the **backdrop** state.
Some element of  a window ie. treeviews have a darker background if there are not in the foreground.
And this doesn't look bad for me and shows that the window isn't active.
This is the idea of the **backdrop** state which is in gtk+ since 3.10.
For me the issue is more that the implementation in marco WM for it is broken.
So, please post screenshots for verifiy that we talk about the same.
And grep for :backdrop in theme css.

**Comment by kn00tcn** [comment]
i renamed the theme in the index file so it wont interfere, also i just noticed the recent mate-themes update in f25 is now causing the background issue, i happen to have a separate cloned theme from january that acts like what it was until the last few days

it doesnt seem to do it in mate, after searching & guessing, i found the line for the background (but not the horizontal divider)

```
.view text selection:backdrop,
.view:selected:backdrop,
treeview.view:backdrop {
	background-color: shade(@theme_unfocused_bg_color, 0.94);
```
![kn-menta-in-xfce-background-issue](https://cloud.githubusercontent.com/assets/8087411/24680771/434431a8-1960-11e7-88e5-4200d883ade1.png)

i do see how an inactive state is an interesting idea, just saying whatever's happening currently is wrong (since other windows like caja or thunar dont do it, other components of windows like toolbars or non tree views dont do it)

do i need another distro to install gtkinspector or a widget factory? (other than manual compiling... which will end up installing lots of deps though)

**Comment by raveit65** [comment]
It looks like there is a change in xfce WM which seems support the backdrop state now.
I didn't change anything for this in theme.
Menta themes use this settings since i added the theme 2 or 3 years ago.

**Comment by kn00tcn** [comment]
but the only changes that i've had are the themes.... & mesa, which i think started causing compton to crash on lock, so i switched back to compiz... with no background issue!

this is getting weird now, how can the compositor affect simple css? it's not acting like an artifact, it's almost like the inactive state doesnt get triggered in compiz or mate

**Comment by lukefromdc** [comment]
My guess is that would depend on whether or not the WM implements the :backdrop state or not. If I run GtkInspector on a Pluma window under compiz, then click on the desktop I do not see the backdrop state coming up

**Comment by raveit65** [comment]
I tried to say it more simple again:
marco WM --> backdrop state is broken , it is in code
compiz-reloaded WM --> no backdrop state (build depends on marco WM)
metacity --> support the backdrop state
compiz-0.9x support backdrop state
mutter --> support the backdrop state.
Other WMs aren't interested for me, you have to inform yourself.
I'd like to support the backdrop state in future as Ubuntu-MATE-17.14 comes with WMs which support the backdrop state, but this will take some time as i need to re-write the complete state in Menta theme.
For the moment create a user config css file ~.config/gtk-3.0/gtk.css  and disable the state, btw. make them equal to normal state.
```
treeview.view.progressbar,
treeview.view.progressbar:backdrop {
      color: @theme_selected_fg_color;
      border: 1px solid @progressbar_border;
      border-radius: 4px;
      background-image: linear-gradient(to left,
                                        @progressbar_background_a,
                                        @progressbar_background_b);
      box-shadow: inset 1px 1px alpha(white, 0.2), inset -1px -1px alpha(white, 0.1);
}

.view text selection:backdrop,
.view:selected:backdrop,
treeview.view:backdrop {
	background-color: @theme_selected_bg_color;
	color: @theme_selected_fg_color;;
}

label:backdrop:selected,
label selection:backdrop {
  color: @theme_selected_fg_color;
}

.cell:selected:backdrop,
.cell:selected:focus:backdrop {
	color: @theme_selected_fg_color;
}

row:selected:backdrop,
row:selected:focus:backdrop {
	color: @theme_selected_fg_color;
}

list row:selected:backdrop,
list row:selected:backdrop:hover,
list row.activatable:selected:backdrop,
list row.activatable:selected:backdrop:hover {
    padding: 2px;
    border-width: 0;
    border-style: solid;
    border-color: shade (@theme_selected_bg_color, 0.85);
    background-color: @theme_selected_bg_color;
    background-image: linear-gradient(to bottom,
                                      shade (@theme_selected_bg_color, 1.0),
                                      shade (@theme_selected_bg_color, 0.85));
    box-shadow: none;
    color: @theme_selected_fg_color;
}

.titlebar:backdrop {
    color: @theme_unfocused_fg_color;
}
```
Maybe, there are more parts where the backdrop state is pulls in but this you can correct for yourself.
Note, this is from and for BlueMenta theme.

What we need to do is.
1. fixing the backdrop state in marco VM
2. rewrite themes for it

> My guess is that would depend on whether or not the WM implements the :backdrop state or not.

Yes, this comment implemented that in metacity
https://git.gnome.org/browse/metacity/commit/?h=gnome-3-14&id=c9099b4a90932a22c86b960c8b4dc7cd1458defe
And as you can see someone tried to do this for marco.
http://git.mate-desktop.org/marco/tree/src/ui/theme.c#n6265

**Comment by raveit65** [comment]
opps
```
.view text selection:backdrop,
.view:selected:backdrop,
treeview.view:backdrop {
	background-color: @theme_base_color;
	color: @theme_text_color;
}
```
This is the right selector

**Comment by raveit65** [comment]
@kn00tcn 
Please test
https://github.com/mate-desktop/mate-themes/commit/9ae7e7efdddf15643dd6b7d9ca6a4c0928b2b781

**Comment by raveit65** [comment]
new relaeses are done  and in fedora
https://bodhi.fedoraproject.org/updates/FEDORA-2017-db9cb79398

**Comment by kn00tcn** [comment]
ok i just did xfwm4 --replace to stop using compiz, enabled your 9ae7e7e version, seems to work

the horizontal divider was black until i closed & opened the file manager, gtk is so weird when switching themes!
