### ISSUE TITLE
(all themes) print dialog paper depictions not appearing correctly

### ISSUE THREAD

**Issue by cruoploav** [mate-desktop/mate-themes#174]
the paper depictions were mostly fixed in https://github.com/mate-desktop/mate-themes/issues/128, however, a few small glitches remain ...

screen captures are from Mate 1.16.1 in Fedora 25 with mate-themes 3.22.7 and gtk 3.22.10 ...

the shadow on the bottom and right edges is overlapping the paper on the "Page Setup" tab:
![overlap](https://cloud.githubusercontent.com/assets/20206403/24755585/d27354e6-1aa8-11e7-84a8-950b4a91656c.png)

the above issue presents differently in the contrast themes, where the shadow overlaps the entire sheet:
![overlap-contrast](https://cloud.githubusercontent.com/assets/20206403/24755564/c4538c82-1aa8-11e7-8abf-98aaf61285ef.png)
![overlap-contrast-inverse](https://cloud.githubusercontent.com/assets/20206403/24755672/1becd390-1aa9-11e7-9e37-8081eaa4ffcc.png)

In addition, the contrast themes have an issue with missing paper and border colors on the "General" tab (to the right of "Reverse", where "1" and "2" appear):
![contrast-general](https://cloud.githubusercontent.com/assets/20206403/24755885/d8ad0086-1aa9-11e7-8ade-be91f2fb3d36.png)
![contrast-inverse-general](https://cloud.githubusercontent.com/assets/20206403/24755890/dc104706-1aa9-11e7-8d93-b8782a560a22.png)

**Comment by sc0w** [comment]
I can see your first capture in TOK

It can be fixed with:

`border-width: 0.4px;`

in

`printdialog.background paper`

with this result:

![paperprint](https://cloud.githubusercontent.com/assets/7734191/24756187/3214b2b2-1add-11e7-90de-8f3fcfb1b70c.png)

@raveit65 what do you think?
