### ISSUE TITLE
Menta: 3.22.9 and 3.20.18 releases badly broken by typo

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-themes#176]
The fix for https://github.com/mate-desktop/mate-themes/issues/172 introduced this typo to the gtk-widgets.css file in Menta, which effectively disables the theme by making all of the file after the typo invalid. Commit https://github.com/mate-desktop/mate-themes/commit/f44e8b0da06aa55d28d7db0ddabdfa67f5d33a89 shown below:

```
----------------- desktop-themes/Menta/gtk-3.0/gtk-widgets.css -----------------
index 7d1c6ea3..259835fb 100644
@@ -4550,7 +4550,7 @@ label selection:backdrop {
 label:disabled:selected,
 label selection:disabled,
 label:backdrop:disabled:selected,
-label selection:backdrop:disabled {{
+label selection:backdrop:disabled {
 	color: @insensitive_fg_color;
 }
```
Fixes this in master but to merge it to gtk3.22 and 3.20 would complicate merging the fix for the shadow on print dialog paper which is just before it in master. Had I spotted that before merging the paper fix locally I would have merged this first. Anyway, the tarballs are BROKEN so not only does this need to be merged into gtk3.20 and gtk3.22 quickly but new tarballs need to be released. I suspect Menta has a lot of users on Fedora, Debian Sid still has gtk3.22.6 in use and could avoid this mess entirely

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-themes/commit/e07e1a7e25e29f8798ff1ea893883f3fa9f0601b
https://github.com/mate-desktop/mate-themes/commit/eef2fc5f588ed2d41fcf3ef5841458a7e149b3c2
I cherry-picked the fix to branches. Thank you, good finder.

**Comment by raveit65** [comment]
PS: We use BlueMenta as default in fedora.

**Comment by raveit65** [comment]
3.22.10 and 3.20.19 are released.
