### ISSUE TITLE
gtk-3.22 TraditionalOK-3.22.12  caja-1.18.3 font in status bar very tiny

### ISSUE THREAD

**Issue by burdi01** [mate-desktop/mate-themes#186]
#### Expected behaviour

Xubuntu-16.4.2 - gtk-3.18.9 - caja-1.16.6 - clearlooks-phenix-6_3.14

![image](https://user-images.githubusercontent.com/9949014/27335547-1d1aedce-55cd-11e7-8aaa-917285b666df.png)

#### Actual behaviour

Slackware-Current64 - gtk-3.22.15 - caja-1.18.3 - traditionalOK-3.22.12

![image](https://user-images.githubusercontent.com/9949014/27335010-68b1ac16-55cb-11e7-9f17-62edb308f6d3.png)

#### Steps to reproduce the behaviour
Note the tiny font in the caja statusbar above.

I scanned all /usr/share/themes/TraditionalOk/* files, but I could not locate a specific setting for the statusbar font. Does one exist?

#### MATE general version
Mate 1.18

#### Package version
http://slackware.uk/msb/current/latest/x86_64/base/mate-themes-3.22.12-noarch-1_msb.txt

#### Linux Distribution
Slackware-Current64

**Comment by raveit65** [comment]
It's there https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/gtk-3.0/gtk-widgets.css#L193
If you don't like it you can create ~.config/gtk-3.0/gtk.css with your user settings.
Add
```
statusbar label,
statusbar frame {
    font-size: 100%;
}
```

**Comment by lukefromdc** [comment]
There is an issue in GTK font size reading that was not fixed until GTK 3.22-and which created new issues when it was. A font size set in points (pt) will render wrong size in GTK 3.20 and earlier, one set in % or in px will render wrong size with GTK 3.22

**Comment by burdi01** [comment]
This resolved my problem: 
```
statusbar label,
 statusbar frame {
     color: @theme_fg_color;
-    font-size: smaller;
+    font-size: 100%;
 } 
```
Why I did not find this phrase myself will for ever be a question. (;-
Thank you, Dick

**Comment by mrnhmath** [comment]
I think the full size should be the default, since it offers better readability.
