### ISSUE TITLE
Gnome accessibility themes no longer available on appearance dialog

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-themes#188]
#### Expected behaviour
When GNOME Themes Standard is installed on the system GNOME themes should be visible on Mate appearance dialog.

#### Actual behaviour
Since gnome Themes Standard 3.22.3 (available on Debian Sid and Ubuntu 17.10) GNOME themes no longer appear on the Mate appearance dialog

#### Steps to reproduce the behaviour
1) Install GNOMEE Themes last release (3.22.3), on Debian/Ubuntu for example the package gnome-accessibility-themes
2) Open the Appearance window
3) Search for theme from NighContrast theme

#### MATE general version
1.16

#### Package version
1.16.1-1

#### Linux Distribution
Debian Sid

#### Explanation
GNOME Themes Standard drops the support for the key Metacity in [the commit 0fb555d0bc1b78c7f208e7f4adcf65e35f72cfc3t](https://github.com/GNOME/gnome-themes-standard/commit/0fb555d0bc1b78c7f208e7f4adcf65e35f72cfc3)

Best regards.

Origin report https://github.com/mate-desktop/mate-control-center/issues/288

**Comment by raveit65** [comment]
Moving this report to mate-themes as it affect HighContrast theme too.
I couldn't imagine that i start write index.theme files to fix gtk+ themes in MATE......., wtf

**Comment by raveit65** [comment]
@alexarnaud
This is really another reason for an upstream report against gnome.
The HighContrast theme should be usable for all DEs.
As workaround i will add a index.theme file with a theme name **ContrastHigh**,  which will use the gtk-theme and icon-theme from **HighContrast**.
We ship already a metacity theme for HighContrast, so we can do that.
But from my point of view gnome guys are responsible that accessibility-themes are working in all DEs.

**Comment by raveit65** [comment]
For quick testing create this index.theme file.
```
[root@mother rave]# cat /usr/share/themes/ContrastHigh/index.theme 
[X-GNOME-Metatheme]
Name=High Contrast
Type=X-GNOME-Metatheme
Comment=ContrastHigh theme
Encoding=UTF-8
GtkTheme=HighContrast
IconTheme=Adwaita
MetacityTheme=HighContrast
CursorTheme=Adwaita
CursorSize=24
```
This brings back the High Contrast theme in mate-appearance-properties main theme tab.

**Comment by alexarnaud** [comment]
Le 02/07/2017 à 08:34, raveit65 a écrit :
> @alexarnaud <https://github.com/alexarnaud>
> This is really another reason for an upstream report against gnome.
> The HighContrast theme should be usable for all DEs.
> As workaround i will add a index.theme file with a theme name 
> *ContrastHigh*, which will use the gtk-theme and icon-theme from 
> *HighContrast*.

Oh, on my Debian 8.8 "Jessie" system with Mate 1.8 I already have a 
"ContrastHigh" theme, is it the same trick as in older releases ?
Thanks a lot for the very quick fix :) !

> We ship already a metacity theme for HighContrast, so we can do that.
> But from my point of view gnome guys are responsible that 
> accessibility-themes are working in all DEs.

OK, I'll will report them but I need your help for technical explanations.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by raveit65** [comment]
> Oh, on my Debian 8.8 "Jessie" system with Mate 1.8 I already have a "ContrastHigh" theme, is it the same trick as in older releases ?

Depends on mate-themes version.
We dropped the ContrastHigh theme a while ago since this is shipped with gtk+ itself, and we ship only the missing metacity theme for it.
So it looks like your mate-themes version is very old and obsolete if this folder contains a complete theme.

**Comment by alexarnaud** [comment]
Le 03/07/2017 à 10:10, raveit65 a écrit :
>     Oh, on my Debian 8.8 "Jessie" system with Mate 1.8 I already have a
>     "ContrastHigh" theme, is it the same trick as in older releases ?
> 
> Depends on mate-themes version.
> We dropped the ContrastHigh theme a while ago since this is shipped with 
> gtk+ itself, and we ship only the missing metacity theme for it.
> So it looks like your mate-themes version is very old and obsolete if 
> this folder contains a complete theme.

So your expectations for gnome-theme are to keep the Metacity Theme key 
and to reintroduce Metacity theme into it ?

Cheers :).
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by raveit65** [comment]
> So your expectations for gnome-theme are to keep the Metacity Theme key and to reintroduce Metacity theme into it ?
Yes, i mean i don't care if adwaita theme is for gnome only as we sheep enogh good own themes, but for a accessibility-theme i expected that it can be used for every DE out of box.
And they have their metacity theme in git history, so it takes 2 secs to revert the commit which have remove it.
