### ISSUE TITLE
[TraditionalOk] sliders blurry

### ISSUE THREAD

**Issue by uezedri** [mate-desktop/mate-themes#190]
Fedora 26
MATE 1.18.0
mate-themes 3.22.12-1

as pointed out by @mrnhmath in #189, the sliders in TraditionalOk are blurry. this is due to the source images being smaller than the rendered images.

**here's a screen capture illustrating the blurriness:**
![28341105-9c057d08-6be8-11e7-9b0a-70c56a9ff0f0](https://user-images.githubusercontent.com/30272697/28371861-17da6f14-6c6c-11e7-952b-1ad05d868e6f.png)

**here's the original scale-slider-vert.png (13x21):**
![scale-slider-vert](https://user-images.githubusercontent.com/30272697/28371913-4b58bdbe-6c6c-11e7-9bc1-6a767ff49505.png)

**here's a modified version of this graphic which might be used as a replacement (not merely scaled but carefully edited in GIMP to match the rendered dimensions) (16x26):**
![scale-slider-vert_modified](https://user-images.githubusercontent.com/30272697/28371931-5be7e0f6-6c6c-11e7-9aab-92c7aa8e5471.png)

I can produce modified versions of the rest of the slider images if this will be helpful.

**Comment by sc0w** [comment]
I will keep the size 13x21, the classical, the same like gtk2 in the past
