### ISSUE TITLE
[TraditionalOk] Places "Recent Documents" arrow not grayed-out when no recent documents

### ISSUE THREAD

**Issue by ogguarro** [mate-desktop/mate-themes#191]
#### MATE general version
1.18

#### Package version
mate-themes 3.22.13

#### Linux Distribution
Fedora 26

To reproduce, go to "Places"->"Recent Documents"->"Clear Recent Documents..."

The arrow next to the grayed-out "Recent Documents" menu doesn't itself get grayed-out.

**Here's how this looks in Fedora 26:**
![f26](https://user-images.githubusercontent.com/31106985/29423354-68b19900-8349-11e7-8ab9-e9d7e728c2e2.png)

**Here's how this looked (correct) in Fedora 24:**
![f24](https://user-images.githubusercontent.com/31106985/29423324-49bc4072-8349-11e7-926f-60e1fa8a1d9d.png)

**Comment by raveit65** [comment]
Thanks for reporting that. You can simply add those lines to gtk-widget.css for the moment, until we release a new version.
