### ISSUE TITLE
menu keyboard shortcut hover color has poor contrast

### ISSUE THREAD

**Issue by sliogleerr** [mate-desktop/mate-themes#192]
the keyboard shortcut color is gray normally, and is supposed to turn to white on hover, like follows (from Fedora 24 gtk2 version of mate-calc):
![f24](https://user-images.githubusercontent.com/31319519/29679699-5696f436-88d0-11e7-89f8-dd6f827613f4.png)

here's how this looks in Fedora 26 -- contrast is not good (with gtk3 mate-calc):
![f26](https://user-images.githubusercontent.com/31319519/29679708-5aab01f2-88d0-11e7-87f8-5ea52df2a754.png)

this issue affects bluementa and traditionalok, at least.

#### MATE general version
1.18

#### Package version
3.22.13-1

#### Linux Distribution
Fedora 26

**Comment by sliogleerr** [comment]
@raveit65 this issue still affects TraditionalOk in a fully updated Fedora 28

**Comment by raveit65** [comment]
weird, commit is from 2017, should be in fedora.
`rpm -qa mate-themes` ?

**Comment by sliogleerr** [comment]
@raveit65 
mate-themes-3.22.18-1.fc28.noarch

bluementa is no longer affected, but traditionalok is
