### ISSUE TITLE
Changement a partir du mate-theme 3.22.12

### ISSUE THREAD

**Issue by LinuxVieLoisir** [mate-desktop/mate-themes#196]
Hello, I am French but I will try to speak in English.

since version 3.22.12, we do not have the green present in the task manager when we choose the theme menta when we open a window, and this and the same with the theme bluementa, blue is not present.

I woud like to know if this is normal or not

best regards

**Comment by raveit65** [comment]
Yes, this is normal.
I reworked panel styling with 3.22.12 to make the themes more serious.
I dropped also transition effects for menus.

**Comment by LinuxVieLoisir** [comment]
OK, I personally find it a pity, but it's like that. Last question: but why not propose 2 different theme type ? one with the present color and the other not, the serious theme would be the default theme.

best regards
