### ISSUE TITLE
Cursor almost invisible while renaming files in Caja with Ambiant-MATE-Dark

### ISSUE THREAD

**Issue by ltcmdata** [mate-desktop/mate-themes#201]
#### Expected behaviour
The cursor should be clearly visible.

#### Actual behaviour
Cursor is almost the same color as the background, so practically invisible.

#### Steps to reproduce the behaviour
Choose Ambiant-Mate-Dark as theme. Rename a file in Caja.

#### MATE general version
1.18.0

#### Package version
mate-themes: 3.22.14-1ubuntu0

#### Linux Distribution
Ubuntu MATE 17.10

**Comment by raveit65** [comment]
Ambiant-Mate-Dark is from Ubuntu-Mate, please file out a report there.
https://github.com/ubuntu-mate
Thanks.
