### ISSUE TITLE
BlackMATE text/background color of input field (in Firefox)

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/mate-themes#202]
Fedora 26 - Mate 1.18.0

Using this simple html page:
< html >
< body >
 < form action="" >
  < input type="text" name="test"/ >
< /form > 
< /body >
< /html >

I can see that the input field in Firefox (57.0.4) has dark text and dark background at the same time using BlackMATE theme. Google Chrome does not have this problem however.

![firefox](https://user-images.githubusercontent.com/3275361/35036068-71be20fc-fb73-11e7-9128-4afd65f6a526.png)

**Comment by monsta** [comment]
@raveit65 @lukefromdc: same as https://github.com/mate-desktop/mate-themes/issues/144?

**Comment by raveit65** [comment]
@monsta 
Maybe you don't know it, but ff  and libreoffice don't use GtkWidgets in favor of their own backed Gtk3 stuff.
In result you can't use gtk3-inspector to find the right selector for this part.
And this heros don't use a specific selector like .firefox at top level which makes it possible only select firefox.
Sorry, i don't want to study thier code to find out what i should do ;-)

**Comment by smikkelsendk** [comment]
If I steal the AmbientMATE-Dark theme from Ubuntu, it seems like they have made it work with firefox. However just copying the theme causes other things to stop working (ie mate-system-monitor crashes on startup)
![ambient mate](https://user-images.githubusercontent.com/3275361/35046164-86733730-fb96-11e7-9137-4cf415cace29.png)

**Comment by lukefromdc** [comment]
I have just about given up on trying to get anything to work in Firefox other than by userchrome.css files. I can't get the necesary information and it is totally different than anything else. On top of all else, FF57 changed enough of how userchrome.css is interpreted to break some things in that as well.

FF57 now offers three themes by default however, with only one of them closely tied to the system theme. We may simply have to recommend (or later write once there is enough information) dedicated FF themes

**Comment by lukefromdc** [comment]
One more remark about FF: I'd rather have a browser that is hard to theme than one that is hard to sever from Google and other commericial data harvesters. Thus I will always oppose suggestions for distros to default to Chrome

**Comment by raveit65** [comment]
![Bildschirmfoto zu 2020-06-28 11-00-55](https://user-images.githubusercontent.com/961604/85943191-b4bada00-b92e-11ea-826a-be246b034f81.png)
I don't see that issue any more with f32 and latest firefox.
