### ISSUE TITLE
BlackMATE panel shadow overruns on windows blocking click possibilities

### ISSUE THREAD

**Issue by pols12** [mate-desktop/mate-themes#203]
#### Expected behaviour
Let the user click on bottom controls of the windows, for example to horizontal scroll.

#### Actual behaviour
The shadow of the bottom panel (task bar) spills over into the windows and the user can’t click on this area which covers horizontal scroll bar.

#### Steps to reproduce the behaviour
1. Use BlackMATE theme with a bottom panel.
1. Open a window with a horizontal scroll bar (e.g. view source code of this page)
1. Try to scroll horizontally.

#### MATE general version
Cinnamon 3.4.6

#### Package version
mate-themes 3.22.14-2

#### Linux Distribution
Debian buster (testing, v10)

**Comment by raveit65** [comment]
Time to drop cinnamon themes?

**Comment by raveit65** [comment]
> Cinnamon 3.4.6

Wrong DE!

**Comment by pols12** [comment]
Hi @raveit65 !
Indeed I use Cinnamon, but mate-themes is a Mate package, isn’t it? Where can I find support? Is there somewhere a maintainer for this package on Cinnamon?

Anyway, I don’t have this bug anymore, using Cinnamon 3.8.8 and mate-themes 3.22.14. :smile:
