### ISSUE TITLE
Bottom panels should not have a dead small line at bottom

### ISSUE THREAD

**Issue by pols12** [mate-desktop/mate-themes#204]
#### Expected behaviour
Placing my cursor at the bottom of the screen, I should be able to press buttons of bottom panel.

#### Actual behaviour
Clicking with my cursor at the bottom of the screen does nothing: I have to go some pixels higher (probably only 1 or 2px) to be able to press the button.

#### MATE general version
Cinnamon 3.4.6

#### Package version
mate-themes 3.22.14-2

#### Linux Distribution
Debian buster (testing, v10)

**Comment by raveit65** [comment]
> MATE general version

Cinnamon 3.4.6

Wrong DE......
