### ISSUE TITLE
Menta and BlueMenta Osd progressbar dark foreground on dark background

### ISSUE THREAD

**Issue by Dolsilwa** [mate-desktop/mate-themes#205]
#### Expected behaviour
Themes with dark osd background should have light widgets in foreground.

#### Actual behaviour
Menta and BlueMenta themes in Ubuntu Mate 16.10 both have dark foreground on dark background in osd progressbar with marco in MATE 1.16. This can easly be fixed with changing:

.osd progressbar,
progressbar .osd {
	border-style: none;
	background-color: @theme_selected_bg_color;
	background-image: none;
	border-radius: 0;	
}

to:

.osd .progressbar,
.osd progressbar,
progressbar .osd {
	border-style: none;
	background-color: @theme_bg_color;
	background-image: none;
	border-radius: 0;	
}

#### Steps to reproduce the behaviour
Lower volume with hotkeys for osd to pop up.

#### MATE general version
MATE 1.16

#### Package version
mate-themes 3.20.12-0ubuntu1

#### Linux Distribution
Ubuntu MATE 1.16

**Comment by monsta** [comment]
Do you see something like https://github.com/mate-desktop/mate-settings-daemon/issues/189 or something else?

**Comment by Dolsilwa** [comment]
Yes, without a fix it looks like in here: https://github.com/mate-desktop/mate-settings-daemon/issues/189
and with fix applied it looks like this: 
![zrzut ekranu w 2018-02-18 21-15-05](https://user-images.githubusercontent.com/36594353/36356362-3f6f04a8-14f1-11e8-995b-af5fae077c14.png)

**Comment by lukefromdc** [comment]
What I would not want to see is this hardcoded in such a way that themes could not change it. We need sane defaults that themes can override. That means an alpha value for the dark foreground dark enough that light colored progress bars will show no matter what the desktop background.

If the theme itself sets a dark foreground and a dark background for any widget, that is a problem with the theme. Trying to prevent this in the applications themselves quickly leads to a lot of hardcoded specs that limit what theme authors can do

**Comment by monsta** [comment]
No need for hardcoding, we can add some default values that themes can override if needed, like @lukefromdc said.

**Comment by raveit65** [comment]
Than we need to discuss about a default, because i don't agree with that statement.
> Expected behaviour
> Themes with dark osd background should have light widgets in foreground.

Where is that written?
Our themes have a perfect default.
The use theme_selected_bg_color for the progressbar.
This will work if i add the missing selector '.osd .progressbar' to all themes.
I can do the hopefully next week when i feel better.
I am ill now.

**Comment by aggioddua** [comment]
i'm sorry to hear you aren't feeling well, and wish you a swift recovery!

(it's also as good a time as any to remind you how much we appreciate your work :-))

**Comment by Dolsilwa** [comment]
> Than we need to discuss about a default, because i don't agree with that statement.

>> Expected behaviour
>> Themes with dark osd background should have light widgets in foreground.

Maybe i should clarify, i consider theme_selected_bg_color bright and perfectly fine, especially in comparison to this:

![zrzut ekranu w 2018-02-22 18-15-35](https://user-images.githubusercontent.com/36594353/36553532-de82a0a0-17fc-11e8-8f6f-70b85005e755.png)

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-themes/commit/1864715a3da965ae007b68b11f89da68ccb7e7c9
This fixes the problem in Menta themes, please test.
Trad. themes are still resistant for this fix, for some reasons....-_-
@lukefromdc @sc0w 
Any idea why doing the same doesn't bring back the theme_sected_bg_color for the progressbar?

**Comment by raveit65** [comment]
Ok, settings for trad. themes are in mate-applications.css

**Comment by raveit65** [comment]
Fix for traditional themes.
d572df1d4cc68e3ec757afa02c50301c6e392255

**Comment by raveit65** [comment]
And last but not least a fix for HCI
dbcc7bf25981e6422abcfa3daa0479c0211d408b
Submarine themes are special as the use a colored OSD, the looks good for me.

**Comment by aggioddua** [comment]
i use TraditionalOk. Personally, I prefer the old style of white progress bars (before they turned black) to the new blue style implemented in the recent commits, but that's more a matter of taste ... however, while the new darkish/dullish blue works okay on a dark background, if you then e.g. open Pluma full screen (with white background), it doesn't stand out very well at all. i think the blue needs to be brighter (as an alternative to switching back to the original white). in any case, the bar color needs to contrast well regardless of what color the background is. as the osd is dark, the progress bar needs to be quite a bit brighter in order to always stand out.

**Comment by monsta** [comment]
>  we can add some default values that themes can override if needed

Correction: I meant adding these default values to m-s-d, if that's possible. The themes would then override them if needed, or leave them as is. I recall we did so in some apps...

**Comment by raveit65** [comment]
Fixed in themes.
