### ISSUE TITLE
Ambiant-MATE and Radiant-MATE all menus bold with vala-panel-appmenu 0.7+

### ISSUE THREAD

**Issue by mdmayfield** [mate-desktop/mate-themes#206]
#### Expected behaviour
vala-panel-appmenu's new preference in v0.7+, to put the application name menu in boldface, affects only the application menu.

#### Actual behaviour
For Ambiant-MATE and Radiant-MATE themes, the entire menu becomes either plain text or boldface according to the preference checkbox. For other themes, the application menu alone is affected as expected.

---

The cause is in `Ambiant-MATE/gtk-3.0/apps/other-applications.css`, lines 78-88 (and similar spot in Radiant-MATE). Removing this styling turns the application menu alone bold and resolves the issue for vala-panel-appmenu 0.7+. This has the side effect of turning off boldface application menu in vala-panel-appmenu 0.6.

I'm not sure if vala-panel-appmenu is integrated in mate-desktop or only in ubuntu-mate, but it should be updated to 0.7 when possible to resolve https://github.com/rilian-la-te/vala-panel-appmenu/issues/208 with 0.6.

**Comment by lukefromdc** [comment]
Those two themes are not shipped with the mate-themes package. This needs to be reported against whatever package does include them (presumably an Ubuntu maintained package)

**Comment by mdmayfield** [comment]
Oops, sorry; will do.
