### ISSUE TITLE
Several MATE themes do not render vala-panel-appmenu applet correctly

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/mate-themes#207]
#### Expected behaviour

When the [vala-panel-appmenu](https://github.com/rilian-la-te/vala-panel-appmenu) Global Menu applet for MATE is added to a panel, the background of the Global Menu applet should use the same background colour as the panel.

#### Actual behaviour

When the Global Menu applet is used with the following themes the Global Menu applet background doesn't match the panel background.

  * BlackMATE
  * Blue-Submarine
  * GreenLaguna
  * Green-Submarine
  * TraditionalGreen
  * TraditionalBlue

Here is an example screenshot of the issue.

![mate-themes-gloabl-menu](https://user-images.githubusercontent.com/304639/36924652-583d52bc-1e67-11e8-8595-cc053a1e28ba.png)

#### Steps to reproduce the behaviour

  * Run the Ubuntu MATE 18.04 daily image live session in a VM
  * Right click a panel, select "Add to panel..", select "Global Application Menu" and add it.
  * Open MATE Terminal.
  * Open Appearence control center applet.
  * Select one of the affected theme listed above, focus the MATE Terminal window and look at the Global Menu.

#### MATE general version

  * 1.20

#### Package version

  * mate-themes 3.22.15-0ubuntu1

#### Linux Distribution

  * Ubuntu MATE 18.04 (daily)

#### Link to downstream report of your Distribution

  * None

**Comment by raveit65** [comment]
I would like to fix that but global menu applet doesn't correctly in my 18.04 installation.
Read my comment in https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/3#issuecomment-370253823 and followers.

**Comment by flexiondotorg** [comment]
Try `sudo apt install appmenu-gtk2-module appmenu-gtk3-module`, reboot and then add the Global Menu to a panel.

**Comment by raveit65** [comment]
Already installed.
![globalmenu](https://user-images.githubusercontent.com/961604/37429184-e3a25742-27ce-11e8-8733-556859dbeb25.png)

**Comment by flexiondotorg** [comment]
@raveit65 Can you try using MATE Tweak to switch layout to Cupertino. That includes the global menu.

**Comment by raveit65** [comment]
But the globalmenu is there, only the menu isn't moved from apps to the panel.
I think i tried Cupertino layout already,  but i can try it again.

**Comment by raveit65** [comment]
Same disappointing result with Cupertino layout.
I see the menus only in panel if the desktop has focus.
Menus from other application won't display in panel with globalmenu.
Note , the installation have latest updates from today.

**Comment by raveit65** [comment]
Hmm, 
~/.config/dconf/user was owned by root ---> fixed
What is right setting for globalmenu gsettings keys?
```
rave@ubuntu:~$ gsettings get org.mate.interface gtk-shell-shows-app-menu
true
rave@ubuntu:~$ gsettings get org.mate.interface gtk-shell-shows-menubar
true
```

**Comment by raveit65** [comment]
I notice that other folders and files were owned by root in my user accout.
I never saw that with fedora...
Ok, after deleting and re-creating user account the menus are in panel \o/

**Comment by raveit65** [comment]
@flexiondotorg @rilian-la-te
It is quite usual the themes use another background color for GtkFrame in general.
Is there a reason why vala-panel-appmenu use a a scrolledwindow and a viewport there?
This sounds really weird for me, see
![vala-panel-appmenu-gtk3-inspector](https://user-images.githubusercontent.com/961604/38025715-a2ef3632-3289-11e8-895f-8403e06938ec.png)

@sc0w 
For TOK themes i'd like to remove the gradient background for the panel at https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/gtk-3.0/mate-applications.css#L103
and for 
```
/* main menu */
/* set normal menubar button */
.mate-panel-menu-bar menubar {
    padding: 0px;
    background-image: none;
}
```
Because the background-image isn't use everywhere for the panel.

**Comment by rilian-la-te** [comment]
1. It uses scrolling, because if monitor have small resolution, then big menu will move contents of panel out of monitor. With scolling, it will just scrolls.

**Comment by flexiondotorg** [comment]
@raveit65 In case you missed it, @sc0w gave you a thumbs up to modify TOK :smile:

**Comment by raveit65** [comment]
> It uses scrolling, because if monitor have small resolution, then big menu will move contents of panel out of monitor. With scolling, it will just scrolls.

Ok, that makes sense.

**Comment by raveit65** [comment]
done.
2969b74fc7a79284547f3839948dfe5be9fe7ac9
