### ISSUE TITLE
High contrast themes show transparent zones instead of black when rendered with metacity

### ISSUE THREAD

**Issue by sthibaul** [mate-desktop/mate-themes#211]
#### Expected behaviour

The decoration buttons background should be black

#### Actual behaviour

The decoration buttons background is transparent, thus making them unreadable

#### Steps to reproduce the behaviour

Run metacity-theme-viewer and select Metacity themes then a high contrast theme (both have the issue)

#### MATE general version

1.20

#### Package version

3.22

#### Linux Distribution

Debian

#### snapshots

![metacity-theme-viewer](https://user-images.githubusercontent.com/5405051/38930596-bb80cc96-4310-11e8-89ae-8a895513b6a0.png)

I'll submit a pull request that fixes it.

**Comment by alexarnaud** [comment]
Le 18/04/2018 à 14:00, Samuel Thibault a écrit :
> 
>         Actual behaviour
> 
> The decoration buttons background is transparent, thus making them 
> unreadable

The user impact is visible on Compiz 0.9 from Canonical if you're using 
Compiz window manager and the gtk-window-decorator.

Best regards,
Alex.
