### ISSUE TITLE
TraditionalGreen and TraditionalOK issue with (tags) text field in legacy Diigo Toolbar extension

### ISSUE THREAD

**Issue by grahamperrin** [mate-desktop/mate-themes#215]
I don't know whether this is an issue with the themes, or a peculiarity with an old extension …

#### Expected behaviour

With _Default_ (and most other themes), the _Tags_ field has sufficient vertical space. An example: 

![2018-04-24 19 41 04 default](https://user-images.githubusercontent.com/192271/39207717-a3b7b128-47f8-11e8-98c4-c947e376fd06.png)

#### Actual behaviour

The field is too shallow: 

![2018-04-24 19 36 33 gtk3 traditionalgreen](https://user-images.githubusercontent.com/192271/39207960-53e914ba-47f9-11e8-9fab-469d07c1f18c.png)

#### Steps to reproduce the behaviour

1. Prefer _TraditionalGreen_
2. install [Waterfox](https://www.waterfoxproject.org/en-US/) 56.1.0
3. disable multi-process Waterfox
4. add Diigo Toolbar [5.1.0.38](https://addons.mozilla.org/addon/diigo-web-collector/versions/?page=1#version-5.1.0.38.1-signed.1-signed) 
5. sign in to Diigo
6. use the Diigo toolbar **Bookmark** button

**NB** if I recall correctly, there's the same problem with Firefox ESR on Linux. 

#### Workaround

- Prefer the _Default_ theme
- restart Waterfox.

#### Desktop environment

KDE Plasma 5 from Area 51, https://community.kde.org/FreeBSD/Setup/Area51

#### Package version

- KDE Plasma 5.12.4
- KDE Frameworks 5.45.0
- Qt 5.9.4

#### OS and browser

FreeBSD-CURRENT, Waterfox 56.1.0: 

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% date ; uname -v
Tue 24 Apr 2018 19:48:43 BST
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info waterfox | grep Version
Version        : 56.1.0_13
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~%

**Comment by alexarnaud** [comment]
Le 24/04/2018 à 21:04, Graham Perrin a écrit :
> 
>         Steps to reproduce the behaviour
> 
>  1. Prefer /TraditionalGreen/
>  2. install Waterfox <https://www.waterfoxproject.org/en-US/> 56.1.0
>  3. disable multi-process Waterfox
>  4. add Diigo Toolbar 5.1.0.38
>     <https://addons.mozilla.org/addon/diigo-web-collector/versions/?page=1#version-5.1.0.38.1-signed.1-signed>
>  5. sign in to Diigo
>  6. use the Diigo toolbar *Bookmark* button
> 
> *NB* if I recall correctly, there's the same problem with Firefox ESR on 
> Linux.
> 

Hello Graham,

Thank you for the report,

Could you provide to us steps with a more general applications ? If you 
only reproduce the issue with Diigo, the issue is there.

Best regards,
Alex.

**Comment by grahamperrin** [comment]
As far as I recall, only with Diigo. If I find any other example, I'll revisit this issue. 

Thanks for replying.
