### ISSUE TITLE
Provide old mate cursor theme

### ISSUE THREAD

**Issue by muesli4** [mate-desktop/mate-themes#221]
#### Expected behaviour
Since mate-themes 3.22.16-1 the cursor theme (named *MATE*) has been modified. I'm fine with setting a new default. But the old cursor theme should at least be provided alongside, especially with such major differences.

You could provide it as *MATE classic* or something like that.

#### Actual behaviour
The old cursor theme is gone completely.

#### Steps to reproduce the behaviour
Install mate-themes 3.22.16-1.

#### MATE general version
1.20.1

#### Package version
mate-themes-3.22.16-1

#### Linux Distribution
Arch Linux

**Comment by raveit65** [comment]
New cursor themes are needed for HIDPI support as we have to provide greater sizes than 48px.
Old cursor theme was just a copy of dmz cursor theme.
Is it sufficient for you to use dmz cursor, or should we blow up package size with a old cursor theme?

**Comment by muesli4** [comment]
I didn't know that. It's unfortunate for people that don't know it. But I guess it's fine then.
