### ISSUE TITLE
The Close, Minimize and Maximize buttons looks blur on GTK3 windows

### ISSUE THREAD

**Issue by sirkax** [mate-desktop/mate-themes#224]
Expected behaviour
When set BlueMenta or Menta Theme the Close, Minimize and Maximize buttons looks clear on Xfwm windows and i expected the same behaviour on GTK3 windows.

Actual behaviour
The Close, Minimize and Maximize buttons looks blur on GTK3 windows.

Suggestion for resolve this bug

on **/gtk-3.0/window-controls.css** 

change    
`background-size: 19px 19px;`
to 
`background-size: 20px 20px;`

**Comment by sirkax** [comment]
Ah, sorry, i use this themes on XFCE . With fix you posted , i had stil problem with buttons on gtk3 apps.
Resizing icons did not help until I change it in file above

**Comment by raveit65** [comment]
But you're are talking about windows with client-side-decorations?

**Comment by sirkax** [comment]
this is for example Pamac,  gtk3 fronted for libalpm 
before editing window-controls.css looks like this
![before](https://user-images.githubusercontent.com/39432962/40268998-81c5ecd8-5b67-11e8-982f-d5dfec7215fd.png)

and after change looks like this
![change](https://user-images.githubusercontent.com/39432962/40269003-8890bbb0-5b67-11e8-835e-d116f0e212c8.png)

**Comment by raveit65** [comment]
Yes, this is client-side-decoration (csd).

**Comment by sirkax** [comment]
Ok, I'm not good at it,  but  it helped to have the sharp buttons. Thanks

**Comment by raveit65** [comment]
It looks like that the icons aren't blurred so dramaticly under MATE with marco VM as in your screenshots with xfce.
19px
![windows-controls-19px](https://user-images.githubusercontent.com/961604/40269289-eee3de82-5b7c-11e8-84b7-d210532f9a8f.png)
20px
![windows-controls-20px](https://user-images.githubusercontent.com/961604/40269292-f5da7188-5b7c-11e8-9e0c-0e7fc40a3770.png)
But i think is see an improvement here too.

**Comment by raveit65** [comment]
Thanks for reporting the issue and your suggestion.

**Comment by sirkax** [comment]
Hmm, in my case, when i replace WM to marco, it's the same as the xf window manager
