### ISSUE TITLE
Filechooser Pathbbar Box Line Removal?

### ISSUE THREAD

**Issue by mdinslage** [mate-desktop/mate-themes#226]
Hello,

First I want to apologize in advance,  my question is about the mint-x theme for mate.  There is a github page for it, but most of the work is being done by one guy and I am having trouble getting a dialog going over there so I thought I would try here.  

The theme has been updated for 3.22.x and everything is working,  its being actively tweaked and they have merged a few of my pull request, but I do keep a custom fork that has my changes that I use personally.

I have it pretty much the way I like it except I have one last problem I can't seem to figure out.  in the Filechooser open file area, the pathbar box has a horizontal line I can't seem to get rid of.  There is no border, which is what I want, but I can't figure out how to remove that line,  here is a screenshot that better explains.  I moved down the window to better reveal the line.

![line](https://user-images.githubusercontent.com/28424337/40589848-a733aed4-61ba-11e8-97f1-939583ab5950.png)

Any help is appreciated, Thank You.

The System is using...

Mate-1.20
Gtk3-3.22.30

Here is the gtk-widgets.css code, I am putting it on pastebin because I have not pushed the changes to my github yet. 

https://pastebin.com/VMb3FUus

**Comment by raveit65** [comment]
Why not using gtk3-inspector?
This will show you the css selector.
And the filechooser is from gtk+ :), this isn't our code.

**Comment by mdinslage** [comment]
Thank You so much for pointing me to gtk3-inspector! extremely useful.   I am learning as I go with this so excuse my ignorance.  using the inspector I was able to remove the line with the code

```
filechooser #pathbarbox {
	border: none;
}
```
but upon applying it in gtk-widgets.css it doesn't work.  I am guessing there is a conflict.  But I am confused when you say filechooser is from gtk+?

Thanks again for replying :)

**Comment by raveit65** [comment]
I such a case i delete complete large code blocks in gtk-widgets.css for testing and reload the theme, to find out where the culprit line is ;)
...quick&dirty...

**Comment by mdinslage** [comment]
Well now I am confused again, that code block worked, but after changing the theme and changing back its not working now, I can put the same code in inspector and it works again.  I'll have to figure this one out, but inspector has been a life saver, so glad you pointed me toward that.

**Comment by mdinslage** [comment]
Last post, finally got it...

```
filechooser #pathbarbox {
    border: none;
}

filechooser #pathbarbox:dir(ltr) {
	border: none;

}
filechooser #pathbarbox:dir(rtl) {
	border: none;
}
```

The inspector was a life saver.
