### ISSUE TITLE
Volume applet (keyboard control) does not respect gtk theme

### ISSUE THREAD

**Issue by mesouug** [mate-desktop/mate-themes#229]
#### Expected behaviour
Volume applet (keyboard control) should have background according to gtk theme.

#### Actual behaviour
Volume applet (keyboard control) does not respect gtk theme. Appears as just black box.

#### Steps to reproduce the behaviour
Select window manager: Marco (no compositor)

#### MATE general version
1.20.1

#### Package version
not sure

#### Linux Distribution
Ubuntu 18.04

#### Link to downstream report of your Distribution

![screenshot at 2018-07-08 11-43-54](https://user-images.githubusercontent.com/7653430/42418272-3cc79ba8-82a5-11e8-9c8f-94de98ff1cd2.png)
![screenshot at 2018-07-08 11-43-39](https://user-images.githubusercontent.com/7653430/42418273-3ceb02fa-82a5-11e8-9327-55d669242257.png)

**Comment by raveit65** [comment]
I don't see any link to a downstream report :)
Btw. this code is from another package not related to mate-media
At least this isn't a bug.
How should transparency work without a compositor?

**Comment by mesouug** [comment]
It should not be transparent at all. It should look like ordinary window and respect gtk theme.
In which repo I should create issue?

**Comment by lukefromdc** [comment]
The repository involved is mate-settings-daemon, the file involved is plugins/common/msd-osd-window.c , and the window is rendered when not composted by this code, which is not themable by GTK:

```
        gtk_render_frame (context,
                          cr,
                          0,
                          0,
                          width,
                          height);
```

To follow the GTK theme would require a significant rewrite of this part an OSD that when first added to GNOME 2 worked only with compositing.
