### ISSUE TITLE
How to make the scrollbar exactly like in Ubuntu MATE 16?

### ISSUE THREAD

**Issue by gabrielbarros** [mate-desktop/mate-themes#231]
Hello. Is there any way to make the scrollbar look like in Ubuntu MATE 16? I'm using Ubuntu MATE 18.04.1 (default theme).

Maybe editing some file in /usr/share/themes/Ambiant-MATE? See the image below:

![img](https://user-images.githubusercontent.com/3298817/43738923-a4c160a0-999c-11e8-8bb2-855976f9b187.png)

**Comment by raveit65** [comment]
Ambiant-Mate theme is Ubuntu stuff https://github.com/ubuntu-mate/ubuntu-mate-artwork
But take a look at Blue/GreenSubmarine themes. They use scrollbars like you want.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/Blue-Submarine/gtk-3.0/scrollbar.css

**Comment by gabrielbarros** [comment]
Thank you. I like it.
