### ISSUE TITLE
how to disable 1-pixel panel border added in commit 8c49f552?

### ISSUE THREAD

**Issue by qralston** [mate-desktop/mate-themes#232]
Per request of @raveit65 in [FEDORA-2018-398fd67e4d](https://bodhi.fedoraproject.org/updates/FEDORA-2018-398fd67e4d):

commit 8c49f552 (included in mate-panel-1.20.3) adds a 1-pixel border on panels, even ones that are fully transparent.

I most emphatically do not want this border. I have a large, unhidden, transparent panel that I stack on the lower layer that contains only a Workplace Switcher applet. This makes it look like the Workplace Switcher is "floating" against the edge of the screen. Having the 1-pixel border destroys that effect.

The "Panel Properties" dialog box doesn't show any option to enable/disable the border, or to control whether the border follows the transparency.

How can the new 1-pixel border be disabled?

**Comment by lukefromdc** [comment]
Since themes are css files, they are not compiled source. Simply go to your preferred theme's directory and comment out or remove the four added stanzas. Alternatelty, these lines to ~/.config/gtk-3.0/gtk.css should do it (though I've not tested that here they should work):
```

PanelToplevel.horizontal.top > grid {
    border-style: none;
    border-width: 0px;
    border-color: transparent;
}
PanelToplevel.horizontal.bottom > grid {
    border-style: none;
    border-width: 0px;
    border-color: transparent;
}
PanelToplevel.vertical.left > grid {
    border-style: none;
    border-width: 0px;
    border-color: transparent;
}
PanelToplevel.vertical.right > grid {
    border-style: none;
    border-width: 0px;
    border-color: transparent;
}

```

**Comment by raveit65** [comment]
Thanks @lukefromdc for posting this solution..
Yes, adding those lines to ~/.config/gtk-3.0/gtk.css + reloading the panel with `killall mate-panel` removes the thin line.
Btw. using only the `border-style` argument is sufficient.
```
PanelToplevel.horizontal.top > grid {
    border-style: none;
}
PanelToplevel.horizontal.bottom > grid {
    border-style: none;
}
PanelToplevel.vertical.left > grid {
    border-style: none;
}
PanelToplevel.vertical.right > grid {
    border-style: none;
}
```

@qralston 
Does this makes you happy again ?

**Comment by qralston** [comment]
I can confirm that overriding in ```~/.config/gtk-3.0/gtk.css``` and reloading mate-panel overrides the change in commit 8c49f55. Thanks @lukefromdc and @raveit65 for providing this easy solution.
