### ISSUE TITLE
Traditional and Laguna theme problems with LightDM gtk greeter

### ISSUE THREAD

**Issue by HOCgTbz9** [mate-desktop/mate-themes#233]
#### Expected behaviour
Using TraditionalOk or TraditionalGreen themes should work fine with LightDM gtk greeter.

#### Actual behaviour
Using either theme results in LightDM GTK greeter panel to not show hostname or clock lightdm gtk greeter panel indicators.

#### Steps to reproduce the behaviour
1.) Select one of the "traditional" themes using lightdm gtk greeter settings application or by editing /etc/lightdm/lightdm-gtk-greeter.conf
2.) Log out and view the LightDM login screen. The clock and hostname sections aren't there

#### MATE general version
1.20.3

#### Package version
mate-themes 3.22.17-2~bpo9+1
lightdm-gtk-greeter 2.0.2-1

#### Linux Distribution
Debian 9

#### Link to downstream report of your Distribution
I didn't report downstream because I think it's an upstream issue

#### FIX
I found the issue to be resolved by copying the relevant "lightdm" section from the "other-applications.css" file from the Menta theme gtk-3.0 folder. The Menta and Submarine themes have lightdm instructions in their gtk3 other applications file while Traditional, GreenLaguna and BlackMATE do not. BlackMATE doesn't seem to have an issue, GreenLaguna renders sort of ok (the clock and hostname are visible but hard to see) and Traditional is broken as described above.
![greetergreenlaguna](https://user-images.githubusercontent.com/42723176/44633784-97e1a400-a95d-11e8-85f0-284fe421d043.png)
![greetertraditionalgreen](https://user-images.githubusercontent.com/42723176/44633786-97e1a400-a95d-11e8-9ca9-25602a37a3ee.png)
![greetertraditionalok](https://user-images.githubusercontent.com/42723176/44633787-97e1a400-a95d-11e8-9f04-bdcfb39dcaaa.png)

**Comment by HOCgTbz9** [comment]
Am I supposed to do a downstream report first? If I am I can do that

**Comment by raveit65** [comment]
No, it's Ok, issue affects all distros and it is clear to reproduce.
No need to inform downstream maintainers,.......they can sleep ;)

Indeed, GreenLaguna is easy to fix if adding adjustments from Menta theme.
With Trad themes i loose also the font-color of language-switcher-button in panel during a first test yesterday.

When i wrote the settings for Menta themes i was able to start gtk3-inspector in lightdm session to find out all the css selectors.
Sadly. i forgot how i did that as i don't use gtk-greeter any more for myself :)
Need to think about......

**Comment by HOCgTbz9** [comment]
Thanks for looking into it! I did some doodling around and was able to get gtk inspector going in lightdm 
On Debian the what I did was:
install libgtk-3-dev
add "GTK_DEBUG=interactive" into /etc/environment
log into lightdm, the inspector was there

However, in order to actually log into a session from lightdm I needed to remove the debug env variable, so I would switch to a tty and replace the previous addition in /etc/environment with GTK_DEBUG=, source the file, and restart lightdm. I hope this helps? There's also the test mode for lightdm run through xephyr but that was being a huge pain in the butt.

**Comment by monsta** [comment]
Thanks, it works :slightly_smiling_face: 

So it should be adjusted in every theme? Looks like lightdm-gtk-greeter is missing some CSS in its own code then...

**Comment by monsta** [comment]
I wonder if we really need to keep supporting version 1.8.5, because it's from [2014](https://launchpad.net/lightdm-gtk-greeter/1.8/1.8.5).

**Comment by raveit65** [comment]
It is really curious that a login manager needs extra settings by themes.
Good is that that old css selectors didn't do bad things.
So i don't do a clean up because i am lazy ;)
