### ISSUE TITLE
blackmate suggested workarounds for firefox make checkboxes and radio buttons invisible

### ISSUE THREAD

**Issue by 0xaf1f** [mate-desktop/mate-themes#237]
In the [curent blackmate README](https://github.com/mate-desktop/mate-themes/blob/8c49f552749d3532efc376006f4ec70801cf0d0d/desktop-themes/BlackMATE/README), there are suggested `userContent.css` and `userChrome.css` files to improve visibility of text in firefox. I've been using these for a wihle, but after upgrading from `52.9.0esr-1~deb9u1` to `60.2.0esr-1~deb9u2` in September, radio buttons and checkboxes no longer display on webpages. The problem goes away when using Firefox safe mode, and I narrowed the problem down to the presence of the recommended `userContent.css` and `userChrome.css` files.

#### Expected behaviour

see checkboxes and radio buttons in firefox while using blackmate with suggested firefox workarounds.

#### Actual behaviour

I don't see checkboxes and radio buttons in firefox while using blackmate with suggested firefox workarounds.

#### Steps to reproduce the behaviour

- use the latest firefox (I'm currently on Firefox ESR 60.4.0).
- create `~/.mozilla/firefox/<profile>/chrome/user{Content,Chrome}.css` as described at https://github.com/mate-desktop/mate-themes/blob/8c49f552749d3532efc376006f4ec70801cf0d0d/desktop-themes/BlackMATE/README
- open firefox and go to any site with radio buttons or check boxes.

#### MATE general version

1.16.2

#### Package version

3.22.18-1~bpo9+1 (but also tried with 3.22.11-1+deb9u1)

#### Linux Distribution

Debian Stretch

#### Link to downstream report of your Distribution

none - this seems more like a documentation bug.

**Comment by 0xaf1f** [comment]
I've come up with this change, which seems to help:

```diff
--- a/chrome/userContent.css
+++ b/chrome/userContent.css
@@ -1,4 +1,4 @@
-input, textarea, select {
+input[type=text], textarea, select {
        -moz-appearance: none !important;
        background-color: white;
        color: black;
```

**Comment by lukefromdc** [comment]
OK, I just verified this to work, so will make this change

**Comment by lukefromdc** [comment]
Commits
https://github.com/mate-desktop/mate-themes/commit/bfc54b484481be46bc8b1e89026ff8c59f3e5d73
for master and
https://github.com/mate-desktop/mate-themes/commit/f64a019669eb6f64081d48befa1fb6501ec7c572
for GTK 3.22 apply this change, so can now close this.
It works, so BlackMATE again works with currently released Firefox. Tested with Firefox 63
