### ISSUE TITLE
The menu bar in LibreOffice looks disabled after saving a document

### ISSUE THREAD

**Issue by underwit** [mate-desktop/mate-themes#239]
#### Expected behaviour

Menu bar in LibreOffice looks active after saving a document

![virtualbox_mint_mate_29_01_2019_17_35_44](https://user-images.githubusercontent.com/951257/51915548-76915200-23ec-11e9-8acf-3b99712ac331.png)

#### Actual behaviour

Menu bar with some themes looks inactive after saving a document

![virtualbox_mint_mate_29_01_2019_17_34_29](https://user-images.githubusercontent.com/951257/51915547-75f8bb80-23ec-11e9-83e1-ed3e864c976a.png)

Broken themes: TraditionalOk, TraditionalGreen
Broken apps: LibreOffice Writer, Impress, Math

#### Steps to reproduce the behaviour

1. Install mate-themes if they are not already installed
2. Choose TraditionalOk or TraditionalGreen theme
3. Start LibreOffice Writer and save document
4. After saving the menu bar will look inactive

#### MATE general version

1.20.1-2ubuntu1 for Mint
1.20.4 for ALT Linux

#### Package version

LibreOffice 1:6.0.3-0ubuntu1 for Linux Mint (VCL: gtk3)
LibreOffice 6.1.3.1 for ALT Linux (VCL: gtk3)

mate-themes 3.22.16 for Linux Mint 
mate-themes 3.22.17 for ALT Linux

#### Linux Distribution

ALT Linux workstation 8.2
Linux Mint 19

**Comment by sc0w** [comment]
Fixed with https://github.com/mate-desktop/mate-themes/commit/7d75c676f7e21eadb4cade538d045db93b35959c
