### ISSUE TITLE
TraditionalOk missing in current Fedora, Mint, and Manjaro, present in Gecko

### ISSUE THREAD

**Issue by pccobbler** [mate-desktop/mate-themes#246]
I happen to really like the following combination in Cinnamon Themes: Windows borders = TraditionalOk; Icons = gnome; Controls = BlueMenta. A few years ago, many of the distributions I tried included TraditionalOk and BlueMenta in mate-themes. However, Fedora 29, Mint 19, and Manjaro 18, all in Cinnamon, no longer include TraditionalOk in Windows borders. Mint 18 and current Gecko do include it (I don't know which Fedora version last had it).

I'm sorry if this is the wrong place for such a question, but which package can be added to obtain TraditionalOk in Windows borders? I'd like to know the answer for both Fedora and Ubuntu/Mint.

**Comment by vkareh** [comment]
Here's a screenshot of TraditionalOk window borders on Fedora 29... do you not have those options there? What's on your list?

![Screenshot at 2019-04-11 21-54-22](https://user-images.githubusercontent.com/259780/55983720-6aefc080-5ca4-11e9-836f-f30e26204079.png)

**Comment by raveit65** [comment]
You are using cinnamon?
If yes you are using the wrong desktop :)
With using MATE in fedora you have all our themes available. You need to fileout a report at cinnamom if you want that they ship mate-themes.
And yes, i know that Mate in linuxmint don't shipp mate-themes as default, and i don't like that.
But again what packages linuxmint or cinnamon ships are not in our responsible area.

> but which package can be added to obtain TraditionalOk in Windows borders?

TOK and Menta are part of mate-themes in fedora, ubuntu, debian and others.

**Comment by pccobbler** [comment]
@vkareh 

Thanks for the reply.

I don't know how to take a screenshot using Screenshot of a window that pops-down when anything else is popped-up. I know how to do it in Windows, but not in Linux.

The only entries in Fedora "Windows border" are: Adapta, Adapta-Eta, Adapta-Nokto, Adapta-Nokto-Eta, BlackMATE, BlueMenta, Menta, Mint-X, Mint-Y, and Mint-Y-Dark. Linux Mint is similar, though I'd need to swap drives to view it (I'm using a laptop in a library right now).

@raveit65 

Then you need to explain why TraditionalOk was present in previous Fedora and Mint versions, but not the current ones. I am aware that it comes from MATE, but mate-themes is commonly installed in Cinnamon, GNOME, and other desktops.

**Comment by raveit65** [comment]
Did you know that you are using cinnamon and not MATE desktop in you fedora installation?

> Then you need to explain why TraditionalOk was present in previous Fedora and Mint Cinnamon versions, but not the current ones.

Again, install MATE_Compiz spin from fedora and mate-themes is installed.
You need to as fedora cinnamon maintainer why he didn't add mate-themes to cinnamon fedora spin.
https://pagure.io/fedora-comps/blob/master/f/comps-f30.xml.in#_433
Or better ask linuxmint/cinnamon people how to use their GUI tools.
Sorry, you're asking at the wrong place.

**Comment by smurphos** [comment]
Just a quick add on note....if mate-themes is installed only window border themes in metacity-theme-3.xml format will be available in Cinnamon 3.8.x or later. Support for the older Metacity variants was dropped.

**Comment by vkareh** [comment]
@smurphos - that's a good point. @pccobbler, what window manager are you using? Also, yeah, Cinnamon and MATE are different desktop environments, so expect differences :P

**Comment by pccobbler** [comment]
Thanks to everyone who responded. smurphos explained the problem succinctly. I may need to switch to MATE.

@vkareh What window manager? I think Mint Cinnamon uses X-Windows.

**Comment by lukefromdc** [comment]
Cinnamon(the actual program by that name, not the while DE) IS a window manager, as is gnome-shell from which it was forked.
