### ISSUE TITLE
RFE: provide build themes without gtk2 support

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/mate-themes#248]
At the moment none of the mate components requires gtk2.
It would be good to have possibility build themes without gtk2 support (now themes build process requires gtk2 devel resources).

**Comment by raveit65** [comment]
Honestly, i don't know exactly why gtk2 build require was needed to build the package, maybe to get the gtk2 engines?

**Comment by raveit65** [comment]
Indeed, configure checks for gtk2 engines (hc and clearlooks) before compiling.
https://github.com/mate-desktop/mate-themes/blob/master/configure.ac#L24
```
# Check GTK+ theme engines
PKG_CHECK_MODULES(THEME_ENGINE,
 [gtk+-2.0 >= 2.0.0 dnl
gdk-pixbuf-2.0 >= 2.0.0 ])
```
Without that engines you will get such warnings during run time of eg. hexchat, claws-mail and many other applications which use gtk+2.
```
rave@mother ~]$ hexchat 

(hexchat:13000): Gtk-WARNING **: 16:15:15.070: Unable to locate theme engine in module_path: "clearlooks",
```
```
[rave@mother ~]$ hexchat 

(hexchat:13129): Gtk-WARNING **: 16:15:36.856: Unable to locate theme engine in module_path: "hcengine",
```
Well, gtk2 isn't needed to build the package but it makes sure that those engines are installed when compiling by hand.
And i don't think that it is possible to remove gtk2 from an installation without loosing a bunch of packages.
So what is the advantage of your RFE ?

**Comment by lukefromdc** [comment]
I think this is a bad idea: there will be a lot of applications using GTK2 for a very long time, and a theme that does not support GTK2 and looks much different than Adwaita in GTK3 is going to make all the GTK2 apps an ugly mismatch.

**Comment by flexiondotorg** [comment]
As discussed, GTK2 engines are required so our GTK2 themes work for GTK2 applications (Foré ample, gimp, inkscape) and also required so that Qt QPA can use hints from GTK2 themes to better integrate Qt applications look and feel.
