### ISSUE TITLE
Mouse pointer does not change when resizing columns

### ISSUE THREAD

**Issue by smithtim** [mate-desktop/mate-themes#250]
This was originally reported as a Caja issue (https://github.com/mate-desktop/caja/issues/1040), but it may involve an incomplete theme, so I am reporting it here.  Please let me know if somewhere else would be more appropriate.

#### Expected behaviour

When hovering over the edge of a resizable column, the mouse pointer changes to a horizontal resize arrow.

#### Actual behaviour

When hovering over the edge of a resizable column, the mouse pointer does not change.  The column is still resizable if you click and drag, but the mouse pointer never changes.

#### Steps to reproduce the behaviour

Hover over a resizable column, e.g. in System Monitor -> Processes.

I am using the default theme that came with MATE.  When I go to Control Center -> Appearance -> Theme -> Customize -> Pointer, it shows "Default Pointer".  If I change it to "MATE", the horizontal resize arrow starts appearing.  If I then change it back to "Default Pointer", the arrow continues to appear until I reboot, after which it stops appearing again.

#### MATE general version

1.22.1

#### Linux Distribution

NixOS 19.09

**Comment by raveit65** [comment]
I can't reproduce this with Mate 1.24 on fedora 32
And it doesn't mater if i use Mate, Mate (black) or Adwaita cursor theme.
The horizontal cursor is always there when i change back to default.
Looks like  an problem with your distro. Did you report it there?
And this is the complete wrong repo to report it.
