### ISSUE TITLE
Theme disturbances with themes v3.22.20

### ISSUE THREAD

**Issue by Mno-hime** [mate-desktop/mate-themes#255]
I updated OpenIndiana 2019.04 (MATE 1.22) with marco 1.22.2 and mate-themes 3.22.20 and there are several disturbances in MATE shipped themes. Composition is on but it affects only the tooltip problem (see below).

- TraditionalOk: Top and bottom menu scrolling arrows at some point disappear, but sometimes appear again
![arrows-in-menu](https://user-images.githubusercontent.com/4632197/59902240-f94b9580-93fd-11e9-97cf-065f74124013.png)

- Black Mate: I can't see check-boxes
![black-mate](https://user-images.githubusercontent.com/4632197/59902241-f94b9580-93fd-11e9-9472-2fb29699e1d2.png)

- With composition on, the tooltip is too big
![tooltip-traditionalok](https://user-images.githubusercontent.com/4632197/59902242-f9e42c00-93fd-11e9-81ab-04b42e731fab.png)

**Comment by Mno-hime** [comment]
Updated to the latest updates from 1.22 stream, the problem is still present for me. Any idea what goes wrong here? What does the "template wrong" label mean?

**Comment by rbuj** [comment]
```shell
$ LANG=C pkg info mate-themes
          Name: desktop/mate/mate-themes
       Summary: MATE Themes
      Category: System/Libraries
         State: Installed
     Publisher: openindiana.org
       Version: 3.22.19
        Branch: 2018.0.0.0
Packaging Date: Sat May  4 09:48:24 2019
          Size: 74.96 MB
          FMRI: pkg://openindiana.org/desktop/mate/mate-themes@3.22.19-2018.0.0.0:20190504T094824Z
   Project URL: http://www.mate-desktop.org
    Source URL: http://pub.mate-desktop.org/releases/themes/3.22/mate-themes-3.22.19.tar.xz
```
Tooltips are not displayed correctly **ONLY** in TraditionalOK and TraditionalGreen controls.

### TraditionalOK 

![Captura de pantalla a 2019-09-20 11-03-07](https://user-images.githubusercontent.com/10171411/65314864-64d90680-db97-11e9-98d5-f496ed9a19b7.png)

### Menta

![Captura de pantalla a 2019-09-20 11-06-33](https://user-images.githubusercontent.com/10171411/65315019-a79ade80-db97-11e9-9a1e-bef86479e76d.png)

**Comment by lukefromdc** [comment]
I cannot duplicate what you have observed in BlackMATE on Debian Unstable. This looks a lot like what happened in some of the major GTK 3 version transitions before 3.20, but MATE 1.22 only builds with GTK 3.22 or later.

Check to ensure the theme assets (image files) got installed in the theme directories. In BlackMATE, missing image files could cause exactly what you are seeing. If you install themes to /usr/share/themes, the image files for BlackMATE should be in /usr/share/themes/BlackMATE/gtk-3.0/assets if they are missing or elsewhere you won't see the checkboxes etc.

**Comment by Mno-hime** [comment]
Here are lists of content of mate-themes v3.22.19, and, respectively, v3.22.20:

[mate-themes_3.22.19.txt](https://github.com/mate-desktop/mate-themes/files/3638523/mate-themes_3.22.19.txt)
[mate-themes_3.22.20.txt](https://github.com/mate-desktop/mate-themes/files/3638524/mate-themes_3.22.20.txt)

Theme images seem to be where they should.

We have following version of GTK 3: `library/desktop/gtk3@3.24.10-2018.0.0.0`.

**Comment by rbuj** [comment]
I couldn't reproduce your issue with BlackMATE on oi-hipster 2019.04:
```shell
git clone https://github.com/mate-desktop/mate-themes.git
cd mate-themes/
git checkout gtk3.22
sudo cp desktop-themes/BlackMATE/gtk-3.0/gtk-widgets.css /usr/share/themes/BlackMATE/gtk-3.0/gtk-widgets.css 
```
![Screenshot at 2019-09-23 00-15-53](https://user-images.githubusercontent.com/10171411/65395200-fc0cac80-dd97-11e9-866b-21de246f0975.png)

**Comment by raveit65** [comment]
I am late to party.
See my comment at https://github.com/mate-desktop/mate-themes/pull/259#issuecomment-589967585
For the moment you can add ~/.config/gtk-3.0/gtk.css with that content to your home dir, to fix tooltip issue.
```
tooltip,
tooltip.background,
.tooltip,
.tooltip.background {
    border-radius: 2px;
}
```
This will override all themes at /usr/share/themes/
