### ISSUE TITLE
Empty space around windows

### ISSUE THREAD

**Issue by z117** [mate-desktop/mate-themes#256]
Take a window with the mouse (either by titlebar or with Alt pressed) and try to move it. A frame around the window, slightly bigger than the window itself, appears to allow you position the window. Move the frame to match a screen corner.

#### Expected behaviour
After the movement finished, the window should be placed exactly in the corner.

#### Actual behaviour
There is a wide band between screen edges and the window.

#### Steps to reproduce the behaviour
Listed above.

#### MATE general version
1.22

#### Package version
mate-themes-3.22.20-1.fc30.noarch

#### Linux Distribution

Fedora 30

#### Additional info

- I suspect this to be the consequence of the fix for https://github.com/mate-desktop/mate-themes/issues/249

- My theme is TraditionalOk.

**Comment by raveit65** [comment]
Wrong repo!

**Comment by lukefromdc** [comment]
This of course is a Marco issue, though with marco 1.23.1 from git master I was unable to duplicate this in any theme whether in my own UbuntuStudio_Legacy theme, menta, or TraditionalOK.

**Comment by z117** [comment]
So should I wait for update and then re-submit it against Marco if the problem persists?

**Comment by lukefromdc** [comment]
Distros won't get 1.23 at all and 1.24 is a long way from release. I would advise submitting it against marco 1.22 now

**Comment by z117** [comment]
OK, submitted for marco.
