### ISSUE TITLE
assertion failed in gtk_cell_renderer_get_aligned_area in Solaar tray menu with Menta themes

### ISSUE THREAD

**Issue by rathann** [mate-desktop/mate-themes#264]
#### Expected behaviour
No crash.

#### Actual behaviour
```
Gtk:ERROR:gtkcellrenderer.c:1796:gtk_cell_renderer_get_aligned_area: assertion failed: (aligned_area->x >= cell_area->x && aligned_area->x <= cell_area->x + cell_area->width)
Bail out! Gtk:ERROR:gtkcellrenderer.c:1796:gtk_cell_renderer_get_aligned_area: assertion failed: (aligned_area->x >= cell_area->x && aligned_area->x <= cell_area->x + cell_area->width)
```

#### Steps to reproduce the behaviour
1. Select BlueMenta or Menta theme in MATE
2. Run [Solaar](https://github.com/pwr-Solaar/Solaar/) on a machine with a supported Logitech USB Receiver.
3. Right-click the tray icon and select either the receiver or one of the paired devices.

#### MATE general version
1.22.2

#### Package version
3.22.20

#### Linux Distribution
Fedora 31 (also reproducible on Fedora 30)

#### Link to downstream report of your Distribution
https://bugzilla.redhat.com/show_bug.cgi?id=1754278
Also reported to [Solaar upstream](https://github.com/pwr-Solaar/Solaar/issues/578)

**Comment by raveit65** [comment]
I don't think that using a padding inside GtkTreeView or GtkCellGtkCellRenderer is a theme issue.
See rhbz report.

**Comment by raveit65** [comment]
Fixed by solaar upstream https://github.com/pwr-Solaar/Solaar/pull/643
