### ISSUE TITLE
3.22.21: desktop-themes/Menta-border missing index.theme.in?

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/mate-themes#268]
I think that in desktop-themes/Menta-border missing index.theme.in file

**Comment by kloczek** [comment]
And probably the same in desktop-themes/GreenLaguna-border

**Comment by raveit65** [comment]
No, the extra border metacity themes are only selectable via the `edit` button in mate-appearance-properties.
To avoid displaying double themes.

**Comment by raveit65** [comment]
At least you need this large border themes only when you do not run the marco compositor, which is needed to display the new invisible-border feature for better resizing a window.
So, only a few users will need these extra metacity themes.

**Comment by kloczek** [comment]
ok .

So we can close that ticket? :)

**Comment by raveit65** [comment]
When you agree :)
