### ISSUE TITLE
Except Traditional themes, mate apps unstable(they crashes)

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [mate-desktop/mate-themes#270]
#### Expected behaviour
any crash

#### Actual behaviour
$ mate-window-properties
free(): invalid pointer

#### Steps to reproduce the behaviour
1. Open terminal and write mate-window-properties etc 
2. Move cursor over the passive tab or click customize button

#### MATE general version
Version 1.24.0

#### Linux Distribution
Pisi Linux 2.2

**Comment by raveit65** [comment]
Double posting!
