### ISSUE TITLE
Traditional and Menta theme families:  theme regressions visible in Caja Places, Tree, History, and (now) Bookmarks sidebars

### ISSUE THREAD

**Issue by thesquash** [mate-desktop/mate-themes#274]
#### My notes
The thing that all of these sidebars have in common is that all of them use GtkTreeView widgets.

#### Expected behaviour
 - All tree view rows should be the same height;
 - All parts of the tree view should be visible and there should be no chopped-off portions.

#### Actual behaviour
 - On all four themes mentioned: the rows in the tree views with the longest strings of text are *double* the height of the rows with shorter-length text.
 - On the TraditionalGreen and TraditionalOk themes only: the left side of the Tree, History, and Bookmarks sidebars are chopped off by 8 pixels.

#### Steps to reproduce the behaviour
Switch to any one of *TraditionalOk*, *TraditionalGreen*, *Menta*, or *BlueMenta*.  Then open Caja, enable the side pane, and open any of the Places, Tree, History or Bookmarks sidebars.

#### MATE general version
Definitely 1.22 or later; may appear in earlier versions.

#### Package version and Linux Distribution
This is not a downstream issue; it appears in the master branch too.

**Comment by thesquash** [comment]
I believe I have discovered where the regressions occur.  (All excerpts presented here are from TraditionalOk.)

 * As for the double height of some tree view rows, this was a direct result of the addition of padding to the tops and bottoms of all tree view rows in the Caja sidebar:
`   .caja-side-pane scrolledwindow.frame treeview.view {
       padding: 3px 0px 3px 0px;
   }`

 * As for the chopping off of the left side of the sidebars, it was caused by an ill-planned attempt to mitigate the effects of overlay scrolling, no longer an issue since overlay scrolling is explicitly turned off in the Caja sidebars:
`   /* move whole the frame, to free eject button for overlay scrollbars */
   .caja-side-pane scrolledwindow.frame {
       padding: 0px;
       margin: 0px 0px 0px -8px;
   }`

I have created a pull request with the modifications made:  #275.

**Comment by sc0w** [comment]
screenshots with expected / currently behavior in traditional ok please?

**Comment by raveit65** [comment]
@sc0w 
Opps, i  thought you did agree already.
Feel free to restore settings for Traditional themes....
There are screenshots in related and merged caja PR.
