### ISSUE TITLE
No switch off for backdrop light effect of active windows for Menta theme

### ISSUE THREAD

**Issue by lucas-oliver-trondsen** [mate-desktop/mate-themes#299]
I'm referring here to the backdrop light effect of inactive windows when they become active: their background goes from dim to bright. I understand that the developers who created this light effect consider it nice. I don't consider it neither good-looking nor necessary. I find the change of background brightness very annoying. It looks as if my monitor is underpowered or has issues. Menta theme worked so well without this effect in Debian 10 (I think before version 3.22.21 of mate-themes). Since I upgraded Debian to Debian 11 and mate-themes to version 3.22.21 I had to face this extremely annoying behavior and try to disable it.

Linux is about choice and I think that no feature should be imposed upon the users without leaving them the possibility to change it. Why there isn't an option, like a switch in dconf Editor, where the user can turn on/off the backdrop light effect of active windows for Menta and for any other theme ?

#### MATE general version
MATE 1.24.1

#### Package version
mate-themes 3.22.21-1

#### Linux Distribution
Debian 11 (bullseye) 64-bit (Kernel Linux 5.10.0-9-amd64 x86_64)

**Comment by lukefromdc** [comment]
GTK 3 Themes don't have running executable code in them that can read a user preference. To make this selectable would require having two versions of the theme, one written each way with slightly different names.

**Comment by lukefromdc** [comment]
Closing as there is no way to implement this in a single version of a theme

**Comment by lucas-oliver-trondsen** [comment]
Ok, then why don't you plan to remove the backdrop light effect, since Menta theme was functioning so well without it and probably many other users are against this light effect ?

I think the most honest way to manage this problem would be to organize a poll, where all Mate contributors can show their preference: who is for and who is against the backdrop light effect. Nextcloud has a very simple poll app that can be used to quickly gather and show the poll results.

**Comment by lukefromdc** [comment]
I generally do not respond to polls on 3ed party websites or apps, presuming them to be part of the whole ad and data sale supported mess that has taken over so much of the web until proven otherwise.

Even if this site is not the case, I have never set up something like that and gwnerally do not use "web 2.0." I am not the person to do any such effort.

I would advise you to simply install an older version, or find the commit implementing the backdrop effect and revert it locally or edit out thr changes in your own machine. Putting your local changes in .config/gtk-3.0 will keep later updates from overriding them.

You could also switch to the Traditional or Yaru themes

**Comment by raveit65** [comment]
> Ok, then why don't you plan to remove the backdrop light effect, since Menta theme was functioning so well without it and probably many other users are against this light effect ?

There is no reason or plan to remove this feature. And you are the only one who don't like it.

**Comment by raveit65** [comment]
Btw, you can use mate-themes-3.22.20 from https://pub.mate-desktop.org/releases/themes/3.22/ , which doesn't have menta themes with backdrop feature.

**Comment by lucas-oliver-trondsen** [comment]
@raveit65 and @lukefromdc
Thank you for your quick reply and suggestions. I should also thank you for contributing to Mate which is the best Linux desktop environment of all. Your work is appreciated and needed. I hope you and the other contributors will keep Mate simple, classic and as far from Gnome 3 as possible.

My solution to removing the backdrop light effect from Menta was to replace the `/usr/share/themes/Menta/gtk-3.0` directory of the current Debian stable mate-themes version, 3.22.21, with the corresponding `gtk-3.0` directory from version 3.22.20, which doesn't have the backdrop effect.

As far as Nextcloud is concerned, I'm a bit surprised you haven't tried it already. It's the only complete, free and open source, gratis, **self-hosted** alternative to Dropbox. It's AGPL v3 licensed. So, you can install it on your own server to host your files and sync them with your computer. In addition, it has a suite of applications that extend its functionality, such as calendar, tasks, forms, polls, text/audio/video chat, including the only good FOSS alternative to Google docs, which is LibreOffice Online, which allows editing office documents online. I'm very much against any 3rd party apps that take control away from the user. But this is the oposite: you install Nextcloud on your own VPS and control everythinig you do with it. I'm not affiliated with Nextcloud. I'm a user in search of control over my digital life, as I think almost all Linux users are.

I was thinking maybe some Mate developer, already has Nextcloud installed and could use the Polls app to run the survey. Anyway, since you say no other users showed their discontent with the backdrop light effect, I guess I have to continue using my own modified version of Menta. If in the future other discontent users show up, maybe you decide to create a new Menta-like theme without the effect. You could just take the Menta theme from 3.22.20 and give it a new name, such as MentaClassic. By the way, where can I find other Mate compatible themes, like the Yaru theme you mentioned ?

**Comment by lukefromdc** [comment]
Yaru is in the newest mate-themes packages, you can use the directories straight from a git pull or clone if your distro is shipping an old version.

About Nextcloud: I have no landline thus no way to host it myself realistically, but many in my community sorely need to get out of the Google Drive/Google Docs habit and surely have access somewhere to a landline. I was not familiar with it simply from non-use of its commerical rivals 

On 11/26/2021 at 11:27 AM, "lucas-oliver-trondsen" ***@***.***> wrote:
>
***@***.*** and @lukefromdc
