### ISSUE TITLE
New release?🤔

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/mate-themes#312]
Any chance to release new version? 🤔 
https://github.com/mate-desktop/mate-themes/compare/v3.22.24...master shows +500 commits since last release.

**Comment by lukefromdc** [comment]
For some reason, github is listing commits from oldest to newest, so you are seeing the 500+ commits prior to the 3.22.24 release. Since 3.22.24 in August 2023 there has been only one commit:
https://github.com/mate-desktop/mate-themes/commit/dae5f044c41238c8bcb8c4c8cf51de8068cd3326

though we might want to do another release anyway so distros can pick that one up, which affects Firefox

**Comment by kloczek** [comment]
> though we might want to do another release anyway so distros can pick that one up, which affects Firefox

Pl;ease .. 😋

**Comment by cwendling** [comment]
I think there is a weird thing that happened with master vs. gtk3.22 branches: most commits have identical content, but are actually different (like if cherry-picked), which makes the branches look very different, but the actual diff is pretty small.

**Comment by kloczek** [comment]
Kind of issue is that probably like me people are looking on what os on master so even effectively there is no to many commits between last release and master it would be good (IMO) to flush all those changes to allow use by default what is on the master 🤔

**Comment by lukefromdc** [comment]
I release 3.22.24 (from master so synched the 3.22 branch as well, only to get this Travis build failure that I do NOT know now to fix, so someone else will have to fix that:

```
Original exception was:

Traceback (most recent call last):

  File "./docker-build", line 33, in <module>

    import requests

  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>

    from urllib3.contrib import pyopenssl

  File "/usr/local/lib/python3.8/dist-packages/urllib3/contrib/pyopenssl.py", line 43, in <module>

    import OpenSSL.SSL  # type: ignore[import-untyped]

  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>

    from OpenSSL import crypto, SSL

  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>

    class X509StoreFlags(object):

  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1571, in X509StoreFlags

    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY

AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

The command "./docker-build --name ${DISTRO} --config .build.yml --install" failed and exited with 1 during .
```

**Comment by kloczek** [comment]
> I released 3.22.24

You mean I released 3.22.25 😋 
Thank you 👍

**Comment by lukefromdc** [comment]
The Travis build failure that I do not know now to fix means this won't appear as a tarball for distros to pick up until someone more familiar with Travis builds than me fixes that.

**Comment by lukefromdc** [comment]
https://pub.mate-desktop.org/releases/themes/3.22/mate-themes-3.22.26.tar.xz
3.22.26 is out and ready for distros

**Comment by kloczek** [comment]
Thank you very much 👍 😄
