### ISSUE TITLE
[feature request] BlueMenta: port CSD from Zukitwo to make consistent look

### ISSUE THREAD

**Issue by rilian-la-te** [mate-desktop/mate-themes#67]
Now 3.12 CSD buttons not themed as WM buttons in BlueMenta. Zukitwo uses almost same wm theme, and has themed 3.12 buttons.

**Comment by NiceandGently** [comment]
@rilian-la-te 
see https://github.com/mate-desktop/mate-themes/commit/4647b65f79410b35b8781d18045da22e11dc1dc7
