### ISSUE TITLE
Menta: Hyperlinks are unreadable

### ISSUE THREAD

**Issue by radioactiveman** [mate-desktop/mate-themes#78]
Hi,

hyperlinks are nearly unreadable with GTK3 and the Menta theme.
An example of a GtkLinkButton can be seen in "gtk3-widget-factory" on page 1.
GTK2 uses blue instead of green which is much easier to read.

I suggest to use the same color for GTK3 to make it consistent and readable.

Thanks, especially for the early support for recent GTK3 versions. :+1:

**Comment by NiceandGently** [comment]
Which distro?
Which GTK3 version?
Which mate-themes version are you using?

**Comment by radioactiveman** [comment]
Arch Linux,
GTK 3.14.6,
mate-themes 1.9.2

**Comment by NiceandGently** [comment]
Please edit /usr/share/themes/Menta/gtk-3.0/gtk-main-common.css  , line 84, and use this color:
@define-color link_color #4E7528;
Is this a better contrast?
I don't wanna use a blue color in a green theme.

**Comment by radioactiveman** [comment]
Yes, this is a better contrast.
But the GTK2 theme should be changed as well to make the appearance consistent.

**Comment by NiceandGently** [comment]
/usr/share/themes/Menta/gtk-2.0/gtkrc  , line 16
gtk_color_scheme = "link_color:#4E7528" # Hyperlinks

OK?

**Comment by radioactiveman** [comment]
I would use #61bf00. This color is a bit brighter, looks better and is still readable.

**Comment by NiceandGently** [comment]
#61bf00 is Ok for me, i will use this color for both GTk2/3.
Thanks for reporting the issue.

**Comment by NiceandGently** [comment]
https://github.com/mate-desktop/mate-themes/commit/0c443b6ccc4adcb55046734dab2c7d1a2fa0b5f3
