### ISSUE TITLE
metacity-theme-1.xml from BlackMATE is an empty file.

### ISSUE THREAD

**Issue by darkshram** [mate-desktop/mate-themes#79]
mate-themes/desktop-themes/BlackMATE/metacity-1/metacity-theme-1.xml
 is an empty file.

**Comment by NiceandGently** [comment]
Is this a problem :)
This dummy was needed in the past when mate-control-center comes w/o metacity-2.xml support.
I need to check that all distros use m-c-c with metacity-2.xml support.
But a empty file doesn't cause any issue and m-c-c use automaticly the higest available version.
So i think i won't remove it to be save.

**Comment by darkshram** [comment]
I'm not saying to delete the file, but to put content into it. Same as it seems to have been done to GreenLaguna. Any alternative/legacy/whatever window manager looking for metacity-theme-1.xml will fail to load theme.

**Comment by infirit** [comment]
> Any alternative/legacy/whatever window manager looking for metacity-theme-1.xml will fail to load theme.

It may, can you point to an actual example?

**Comment by darkshram** [comment]
Actual example: Ubuntu 14.04.1 LTS (Trusty Tahr) packaged MATE 1.6 (and marco 1.6) in universe repository. (http://packages.ubuntu.com/source/trusty/mate-themes).

Second example: I work for an organization that mantains a custom Linux distribution for México which still uses MATE 1.6. No plans to update to 1.8 for now.

I can commit tested versions of metacity-1.xml for both BlackMATE and GeenLaguna (current metacity-1.xml does not works neither with metacity 2.3 or marco 1.6). Both work with legacy metacity-2.30 and older versions of marco and whatever looks for metacity-1.xml. Should I commit them?

**Comment by NiceandGently** [comment]
exactly for this we're using a dummy file.
Simply copying the context of the metacy-2 file to the metacity-1 don't work, there is a different between both standards.
PS: using a still unsupported mate version is insecure.

**Comment by infirit** [comment]
What is not clear to me is how it is a problem? Does it fail to load, does it cause the window borders to be wrong or is it causing problems in mate-control-center?

Marco/metacity will use the -2 version over the -1 version. However mate-control-center did not show any themes if there was only a -2 version of the theme, is that what you are seeing?

**Comment by darkshram** [comment]
Infirit: Both BlackMATE and GreenLaguna metacity themes fail to load with marco 1.6 or legacy metacity 2.30. Mate CC show a wuistion mark and no thumbnail. I have created metacity-1.xml files for both themes and fix this particular issue. Should I commit them or do I keep them for myself? I think some Ubuntu 14.04 LTS users would appreciate them.

NiceandGently: We are supporting ourselves and doing back-port of all critical/important patches. We have a similar EOL schedule and plans as RHEL and CentOS do.

**Comment by NiceandGently** [comment]
RHEL/CENTOS7 use mate-1.8 from epel repo.

**Comment by infirit** [comment]
@darkshram if you have working versions my initial reaction is sure. But I'll let @NiceandGently decide as he is the one doing most of the work keeping the themes up to date working and he'll most likely will maintain it in the future.

**Comment by darkshram** [comment]
NiceandGently: Our distro is based on a *heavily* modified & *heavily* patched blend of CentOS6/Fedora14. No systemd here. http://www.alcancelibre.org/staticpages/index.php/notas-lanzamiento-aldos-1-4
I think you should do testing on Ubuntu 14.04 LTS instead of Fedora 18. *LTS* stands for (sort of) "we will support this OS and keep offering MATE 1.6 until April 2019".

Infirit: So, let me see if I understand... there are 2 file broken (on purpose?), breaking every standard for themes I know, and that's Ok for MATE developement team. Is that correct?

I gladly will fork and commit the files if you ask. I'am attaching a screenshot to help validate.
![pantallazo](https://cloud.githubusercontent.com/assets/10327500/5673184/50a49efe-975e-11e4-9ac8-b6232c7fc394.png)

**Comment by NiceandGently** [comment]
Again, i can't reproduce the issue with mate-.1.6.x.
And i never heard that this is a prob with Ubuntu 14.04 LTS
Copying the metacity-2 to metacity-1 is not a valid solution for upstream.
I suggest to patch mate-control-center with https://github.com/mate-desktop/mate-control-center/commit/6a0ec4159139d0bb4fea0c11b790b4fc2ea774ab

**Comment by darkshram** [comment]
I modified both theme files to work perfectly with metacity-1 standard. Patching the control-center to skip the broken files is not either a solution. That would be like Oracle did with the patching of MySQL. What if someone does a parallel install with GNOME 2.x (SLED 11, SLES 11, CentOS6 RHEL6 and other LTS OS) and wants to use the same theme on both desktops? Or if someone just wants to use BlackMATE/GreenLaguna on SLED 11, SLES 11, CentOS6 RHEL6, etc.?
