### ISSUE TITLE
MATE theme Shiny: GNOME / many GTK3-based applications crash with this theme enabled on a MATE desktop

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-themes#81]
Launch a local MATE session.

Enable the Shiny theme under System->Settings->Apearance.

With MATE theme 1.9.2-1 (and also with pending-unblock-request mate-themes 1.9.3-1) most GNOME
applications crash when the Shiny theme is used for the theme of a MATE desktop.

Tested with:

  eog
  gnome-terminal
  shotwell

See:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776051

**Comment by NiceandGently** [comment]
This theme is obsolete in my eyes ;)
The gtk3 part comes from http://gnome-look.org/content/show.php?content=164764
but upstream seems to be dead.
Sorry, i don't have the time to work on an old theme which needs a complete re-work.
I suggest to remove it during package build, see what i do for fedora.
http://pkgs.fedoraproject.org/cgit/mate-themes.git/tree/mate-themes.spec?h=f21#n75
Shiny is a candidate which will follow to remove.
I often said in mate-dev that i want to remove all themes which doesn't support newest GTK3 version, but nobody agree to me.

**Comment by LeonaDKelso** [comment]
Restoration of the "Window Border" component of the "Shiny" theme requested in the following pull request: https://github.com/mate-desktop/mate-themes/pull/84
