### ISSUE TITLE
GtkScale widget for GTK2 does not show a colored frame

### ISSUE THREAD

**Issue by radioactiveman** [mate-desktop/mate-themes#82]
The GtkScale widget shows a colored frame with GTK3 but not with GTK2.

See for example the blue frame in this screenshot: https://developer.gnome.org/gtk3/stable/scales.png

I am using mate-themes 1.9.3.

**Comment by NiceandGently** [comment]
GTK2 and GTK3 theming is complete different. A lot of settings of widgets are GTK3 only.
...but which theme are you using......and what GTK3 version?

**Comment by radioactiveman** [comment]
This does not matter, it's the case for all Mate themes.
Anyway, I use Menta with GTK+ 2.24.26 and 3.14.9.

Greybird shows the frame correctly in both versions.

**Comment by NiceandGently** [comment]
This is set by the theme, ie Menta themes
```
style "murrine-scale" = "murrine-wider" {
	bg[NORMAL]	= shade (1.06, @bg_color) 
	bg[PRELIGHT]	= shade (1.2, @bg_color)  
	bg[ACTIVE]	= shade (0.85, @bg_color)
	bg[SELECTED]	= shade (1.0, @selected_bg_color)  
	bg[INSENSITIVE]	= shade (0.95, @bg_color)
	
	engine "murrine" {
		roundness	= 7
		contrast	= .8
		border_shades	= {1.0, 1.0}
		trough_shades	= {1.06, 1.16}
	}
}
```
Honestly, i don't see why this is a issue if theme theme styling is a bit different between GTK2 and GTK3.
I don't think that mate desktop is unusable for you ;)
If you don't like it edit the gtkrc file or gtk-widget.css

**Comment by radioactiveman** [comment]
Of course it is not a huge issue but it is still a bug. ;)
I just noticed that the classes for GtkScale use another style ("pixmap-scale").
Is this the cause? But with "murrine-scale" there is still no color shown.

**Comment by NiceandGently** [comment]
You're right, it's under pixmap-scale.
```
style "pixmap-scale" {
	engine "pixmap" {
	image
		{
			function	= BOX
			detail		= "trough"
			file		= "widgets/Scale/trough-horizontal.png"
			border		= { 2, 2, 0, 0 }
			stretch		= TRUE
			orientation	= HORIZONTAL
		}
	image
		{
			function	= BOX
			detail		= "trough"
			file		= "widgets/Scale/trough-vertical.png"
			border		= { 0, 0, 2, 2 }
			stretch		= TRUE
			orientation	= VERTICAL
		}
```
The images needs to be adjusted if you want to change it.

**Comment by NiceandGently** [comment]
If you like provide adjusted images and do a PR.
Sorry, i get evil skin rash when i need to open gimp for working on images......
.....i prefer coding in bits and bytes ;)

**Comment by radioactiveman** [comment]
I found only images for the grey background (e.g. /Scale/trough-horizontal.png).
The GTK3 theme shows a green fill level (GTK3 on top, below GTK2).
Must this be a separate image? Unfortunately I don't have experience to solve that alone.

![gtkscale](https://cloud.githubusercontent.com/assets/1301412/6988167/cdc4a2e8-da4e-11e4-9a12-c8d6a4885799.png)

**Comment by NiceandGently** [comment]
I think 'widgets/Scale/trough-horizontal.png' needs to be convert to green and blue for BlueMenta.

**Comment by radioactiveman** [comment]
Sure, but that's unrelated. There needs to be two colours (grey and green/blue).
Otherwise the whole GtkScale would be coloured. Do you understand the problem now? :)

**Comment by NiceandGently** [comment]
> Otherwise the whole GtkScale would be coloured. Do you understand the problem now? :)
Yes, too much work for an minor issue ;)
