### ISSUE TITLE
mate-themes needs a clean up before 1.10 release

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/mate-themes#83]
1.10 release is a great chance to remove old themes which we don't need.
- Some themes are only renamed for mate and have an installable origin theme.
- with GTK+-3.14, themes which support only a GTK2 part, use adwaita theme as fallback for GTK3 apps. This is something which we don't want.
- we have 10 themes which works well with GTK2/3, more than any other desktop.
- we don't have the manpower to create GTK3 parts for old themes.

Ok, here is my list for discussing
- Quid (the origin theme crux exists)
- Fog (the origin theme mist exists)
- Reverse (the origin theme inverted exists)
- Simply (the origin theme simple exists)
- AlaDelta (the origin theme glider exists)
- all LargePrint themes (no GTK3 support)
user can simply use font scaling in font settings to get a large theme.
- Atantla (the origin theme atlanta exists)

Open Disscussion!
@stefano-k

**Comment by monsta** [comment]
Also there's Atantla theme - renamed Atlanta from metacity-themes. It hasn't been changed for 3 years and its content is still the same as in metacity-themes (at least in Debian Jessie). Besides, this name is ugly. :)

**Comment by stefano-k** [comment]
@NiceandGently, in my opinion, we could remove the themes that you are listing.
If possible, I would like to know also the opinion of @infirit  and @flexiondotorg

**Comment by flexiondotorg** [comment]
@NiceandGently Personally I'd be happy to see GTK2 only themes that we don't have the man power to maintain be dropped from the package and relocated in `mate-themes-obsolete` repository just in case anyone out there decide to revive any of them.

**Comment by NiceandGently** [comment]
@stefano-k 
> in my opinion, we could remove the themes that you are listing.
> If possible, I would like to know also the opinion of @infirit and @flexiondotorg

I think infirit is gone, i only saw activity at blueman from him, and flexiondotorg has called him several time per mail.

@flexiondotorg 
> Personally I'd be happy to see GTK2 only themes that we don't have the man power to maintain be dropped from the package and relocated in mate-themes-obsolete repository just in case anyone out there decide to revive any of them.

Is creating a branch for that sufficient?

**Comment by monsta** [comment]
I think these themes should be compared to the corresponding metacity themes. If they prove to be identical (like in Atantla/Atlanta case I mentioned before), I don't see the point in keeping them even in another repository. Just drop them. If anyone would want to "revive" them, it would be a matter of a simple fork.

**Comment by stefano-k** [comment]
@NiceandGently @flexiondotorg I think we could simply remove them. We have always git history and tarballs to restore them in future.

**Comment by NiceandGently** [comment]
@stefano-k 
need a bit help, not shure if we need 'placeholders' and 'iconmapping' configure option after the clean up.
If i understand this correctly, than placeholder was a option for dev builds and iconmapping is default.
Honestly, i do not know what iconmapping really does and if it is needed.
After the clean up there is only one icon-theme left, highcontrast.
What do you think?

**Comment by xinxinw1** [comment]
Why was "Shiny" removed? I was still using it!

**Comment by NiceandGently** [comment]
Shiny causes issues and was unmaintained
https://github.com/mate-desktop/mate-themes/issues/81
