### ISSUE TITLE
tracker-bug: Button visible below application icon in csd applications

### ISSUE THREAD

**Issue by radioactiveman** [mate-desktop/mate-themes#85]
Hi, in applications with a GtkHeaderBar a round button is visible below the application icon.
The screenshot below shows gnome-calculator running in Xfce.

![screenshot](https://cloud.githubusercontent.com/assets/1301412/7798796/e62e05ee-02fe-11e5-8e45-85fd20c0d9fd.png)

Package: mate-themes 1.10.0
GTK: 3.16.3
Theme: Menta

**Comment by NiceandGently** [comment]
Hi,
can you please send a list which csd applications are affected?
I fixed that already for nautilus and yelp
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/Menta/gtk-3.0/window-controls.css#L161
I don't wanna install whole the gnome world here ;)
For the momment add
```
MathWindow .titlebar .right:dir(rtl) .titlebutton:first-child,
MathWindow .titlebar .left .titlebutton:first-child,
MathWindow .titlebar .right:dir(rtl) .titlebutton:first-child:hover,
MathWindow .titlebar .left .titlebutton:first-child:hover,
MathWindow .titlebar .right:dir(rtl) .titlebutton:first-child:active,
MathWindow .titlebar .left .titlebutton:first-child:active,
MathWindow .titlebar .right:dir(rtl) .titlebutton:first-child:checked,
MathWindow .titlebar .left .titlebutton:first-child:checked,
MathWindow .titlebar .right:dir(rtl) .titlebutton:first-child:backdrop,
MathWindow .titlebar .left .titlebutton:first-child:backdrop,
MathWindow .titlebar .right:dir(rtl) .titlebutton:first-child:backdrop:hover,
MathWindow .titlebar .left .titlebutton:first-child:backdrop:hover {
	background-image: none;
}
```
to window-controls.css at the end of file.

**Comment by radioactiveman** [comment]
As I am using Xfce I don't have all GNOME applications installed but here is a partial list:

* eog
* evince
* gnome-calculator
* gnome-software

Is it not possible to use a general selector?

**Comment by NiceandGently** [comment]
> As I am using Xfce I don't have all GNOME applications installed but here is a partial list:

smilyglasses ,a xfce user use mate-themes :)
> Is it not possible to use a general selector?

Nope, because some csd applications doesn' use a app specific icon.
And using symbolic-icons is not allowed anymore in mate ;)

**Comment by radioactiveman** [comment]
Well, there is a simple reason for that.
Arch Linux always ships the latest GTK3 version and you update your themes very fast to support it.
Thanks for that and keep it up. :)

**Comment by NiceandGently** [comment]
https://github.com/mate-desktop/mate-themes/commit/b1bb1805431ac1e962e60e3fe960d0c234ec6767
Unfortunately, gnome-software doesn't use a specific selector.
So i can't fix it for it.
But you can use for your own
```
.background.csd .titlebar .right:dir(rtl) .titlebutton:first-child,
.background.csd .titlebar .left .titlebutton:first-child,
.background.csd .titlebar .right:dir(rtl) .titlebutton:first-child:hover,
.background.csd .titlebar .left .titlebutton:first-child:hover,
.background.csd .titlebar .right:dir(rtl) .titlebutton:first-child:active,
.background.csd .titlebar .left .titlebutton:first-child:active,
.background.csd .titlebar .right:dir(rtl) .titlebutton:first-child:checked,
.background.csd .titlebar .left .titlebutton:first-child:checked,
.background.csd .titlebar .right:dir(rtl) .titlebutton:first-child:backdrop,
.background.csd .titlebar .left .titlebutton:first-child:backdrop,
.background.csd .titlebar .right:dir(rtl) .titlebutton:first-child:backdrop:hover,
.background.csd .titlebar .left .titlebutton:first-child:backdrop:hover {
	background-image: none;
}
```
This is a general setting which i don't wanna use  yet, until it's clear that all csd applications use a app specific icon for 'menu-close'
I will leave this report open as tracker-bug.

**Comment by NiceandGently** [comment]
more apps are added to whitelist
https://github.com/mate-desktop/mate-themes/commit/a0a9b9810065e3be7476407d458c87e5d641df8c

I checked today most csd apps and 50% of them don't use an application icon.
So, using a whitelist is currently the best way to handle it.
That maybe 2 csd apps don't use a specific selector for theming, is more a bug in this application, from my point of view.
