### ISSUE TITLE
GTK3 toolbar icons have ugly borders

### ISSUE THREAD

**Issue by jazzrz86** [mate-desktop/mate-themes#87]
Running GTK3 apps using the default Menta theme will cause toolbar buttons to have ugly borders. This does not happen in the Awaita standard theme. It looks as if the icon size is not quite right to cover the area designated by the button. This is easily replicated by running "gtk3-demo-application" (see screenshots below).

This effect is less obvious using the Traditional* themes.

Using
Mate 1.10
mate-themes-gtk3.16-1.10.1 
gtk3 3.16.3

![gtk3_buttons2](https://cloud.githubusercontent.com/assets/6050714/8078464/5b48ae02-0fa1-11e5-9267-c59b7585e45a.png)
![gtk3_buttons](https://cloud.githubusercontent.com/assets/6050714/8078491/7d756b32-0fa1-11e5-8a55-7fb5a31fbae3.png)

**Comment by NiceandGently** [comment]
Hmm,
here in fedora 22 (mate gtk3 version), gtk3-3.16.3-1.fc22.x86_64, i don't see this issue.
![menta](https://cloud.githubusercontent.com/assets/961604/8081160/f0979e70-0f72-11e5-8c97-8a1e2dc91bfe.png)
Which distro are you using?
Which icon theme?

**Comment by jazzrz86** [comment]
I am using Slackware current built from msb slackbuilds. Would you have an idea of what may cause this for me?

**Comment by willysr** [comment]
@jazzrz86 did you upgrade your gtk+3 yourself?
-current should be 3.14.12

**Comment by jazzrz86** [comment]
@willysr yes I upgraded it very carefully (according to original slackware build script) in an attempt to solve it. In any case, I have found the problem: it seems that /usr/share/themes/Default got removed. That was a hard one to pin down.

Reinstalling the package fixed it and this issue can be closed. Thanks for your help all
