### ISSUE TITLE
Gtk3: Traditional themes have black border and black inactive title bar

### ISSUE THREAD

**Issue by infirit** [mate-desktop/mate-themes#89]
I have this with Gtk3.14/mate-themes 3.14 branch and Gtk3.16 and 3.16 themes.
![traditional_black](https://cloud.githubusercontent.com/assets/3465730/8541422/6464762c-248e-11e5-803b-258098a00e8a.png)

**Comment by NiceandGently** [comment]
@infirit 
please test

**Comment by infirit** [comment]
Looks good.

**Comment by City-busz** [comment]
Metacity GTK3 is able to render these themes with variables correctly, so it's a bug in Marco. Please revert these commits: https://github.com/mate-desktop/mate-themes/commit/bb155389280a2d6deb897d00c27425e008992345 https://github.com/mate-desktop/mate-themes/commit/940191d42023ffad8231432eb36e8557903cbbce

I opened a task for Marco: https://github.com/mate-desktop/marco/issues/208

**Comment by infirit** [comment]
It is quite common to code the colors like that and if it fixes the problem, even if it is considered a workaround by some.  When the bug is found and fixed perhaps these can be reverted but for now I see no reason to.
