### ISSUE TITLE
Themes color customizing

### ISSUE THREAD

**Issue by black77** [mate-desktop/mate-themes#90]
Changing window background colour doesn't affect all applications. In openSUSE that doesn't affect Authentication window, its colour remains to be default. in Ubuntu that's also true for some apps:
http://forums.mate-desktop.org/viewtopic.php?f=2&t=3688

**Comment by NiceandGently** [comment]
I quess you try to change the colors with mate-appearance-properties.
Can you please open there a report?
Sorry i can't move the topic.
And please attach all infos in the report itself, ie. images.
Thank you

**Comment by black77** [comment]
Okay I see thank you
