### ISSUE TITLE
Different spacing with GtkFileChooserDialog and GtkFileChooserWidget

### ISSUE THREAD

**Issue by radioactiveman** [mate-desktop/mate-themes#94]
The spacing between the folder icon and the description is different with GtkFileChooserDialog and GtkFileChooserWidget. With the latter one, there seems to be no spacing at all (screenshot).

![screenshot](https://cloud.githubusercontent.com/assets/1301412/10716057/b49c8938-7b2b-11e5-9b0f-91a983661389.png)

Version information:
* GTK+ 3.18.2
* Mate-themes 1.10.5, using "Menta"
 (1.11.0 is not published yet by the way at http://pub.mate-desktop.org/releases/1.11/)

I first thought this is a general GTK+ issue, but Adwaita uses the same spacing for both widgets.
A simple test case is shown below.

```
#include <gtk/gtk.h>

// Compile with: gcc $(pkg-config --cflags --libs gtk+-3.0) -o GtkFileChooser GtkFileChooser.c

static void button1_cb (GtkWidget *widget, gpointer data)
{
    GtkWidget *dialog = gtk_file_chooser_dialog_new ("Open File", GTK_WINDOW (data),
     GTK_FILE_CHOOSER_ACTION_OPEN, "Cancel", GTK_RESPONSE_CANCEL,
     "Open", GTK_RESPONSE_ACCEPT, NULL);

    gtk_dialog_run (GTK_DIALOG (dialog));
    gtk_widget_destroy (dialog);
}

static void button2_cb (GtkWidget *widget, gpointer data)
{
    GtkWidget *window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
    GtkWidget *chooser = gtk_file_chooser_widget_new (GTK_FILE_CHOOSER_ACTION_OPEN);
    gtk_container_add (GTK_CONTAINER (window), chooser);
    gtk_widget_show_all (window);
}

int main (int argc, char *argv[])
{
    GtkWidget *window, *vbox, *button1, *button2;

    gtk_init (&argc, &argv);

    window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
    gtk_widget_set_size_request (window, 300, 200);

    vbox = gtk_box_new (GTK_ORIENTATION_VERTICAL, 5);
    gtk_widget_set_halign (vbox, GTK_ALIGN_CENTER);
    gtk_widget_set_valign (vbox, GTK_ALIGN_CENTER);

    button1 = gtk_button_new_with_label ("GtkFileChooserDialog");
    button2 = gtk_button_new_with_label ("GtkFileChooserWidget");

    gtk_container_add (GTK_CONTAINER (vbox), button1);
    gtk_container_add (GTK_CONTAINER (vbox), button2);
    gtk_container_add (GTK_CONTAINER (window), vbox);

    g_signal_connect (window, "destroy", G_CALLBACK (gtk_main_quit), NULL);
    g_signal_connect (button1, "clicked", G_CALLBACK (button1_cb), window);
    g_signal_connect (button2, "clicked", G_CALLBACK (button2_cb), NULL);

    gtk_widget_show_all (window);

    gtk_main ();

    return 0;
}

```

**Comment by raveit65** [comment]
hmm, thanks for reminder.
Looks that i've fixed it local but not pushed yet.
I'm working on new releases.....

**Comment by raveit65** [comment]
Btw. are you sure that mate-themes in arch use mate-themes-gtk3.18-1.10.5.tar.xz ?

**Comment by radioactiveman** [comment]
Arch uses the GTK+ [3.16](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/mate-themes#n4) theme version, but I built my own package for 3.18.

**Comment by raveit65** [comment]
i've released a new tarball for 1.11, please test.
I suggest to file out a report at arch for wrong version.
gtk+-3.18 has a lot of changes for themes, using tarballs for 3.16 is not sufficient.
There are 10.x tarballs for 3.18 since 2015-10-19

**Comment by radioactiveman** [comment]
Already done, version 1.11.0 for GTK+ 3.18 does neither fix the reported issue nor #95.

**Comment by raveit65** [comment]
Hmm, which application use GtkFileChooserWidget ?
With GtkFileChooserDialog i don't see this, btw. i've adjust this anoying list-row change for GtkFileChooserDialog.
.....seveal times.......sigh

**Comment by radioactiveman** [comment]
Have you tried the code from the first post? The spacing is correct in the GtkFileChooserDialog but not in the GtkFileChooserWidget. And it does not matter which application uses GtkFileChooserWidget, this is a general issue. Anyway, Audacious is an example.

**Comment by raveit65** [comment]
fixed with https://github.com/mate-desktop/mate-themes/commit/61cea2a204e014c788b947263f0adab3384a2f5c
Thank you
