### ISSUE TITLE
Wrong background color in GtkAboutDialog

### ISSUE THREAD

**Issue by radioactiveman** [mate-desktop/mate-themes#95]
The background color in the GtkAboutDialog should be white instead of grey.

Mate-themes 1.10.5, GTK+ 3.18.2, theme Menta

![screenshot](https://cloud.githubusercontent.com/assets/1301412/10716082/d600a45a-7b2c-11e5-917a-e34d7c55c1b4.png)

**Comment by raveit65** [comment]
Which calcolator is this?
Btw. are you sure that mate-themes in arch use mate-themes-gtk3.18-1.10.5.tar.xz ?

**Comment by raveit65** [comment]
I've released 	mate-themes-gtk3.18-1.11.0.tar.xz
.......hope this helps :)

**Comment by radioactiveman** [comment]
Thanks, but if you mean 1.11 should fix this bug, it does not. And the screenshot shows gnome-calculator.

**Comment by raveit65** [comment]
weird, gnome-calculator looks like this with Menta themes 1.11.0 in fedora 23 (gtk+-3.18).
![gnome-calculator](https://cloud.githubusercontent.com/assets/961604/10716930/94e7cca2-7b48-11e5-9a3b-3fe074373e1b.png)

**Comment by radioactiveman** [comment]
You have to click "Credits / Mitwirkende"... :smile:

**Comment by raveit65** [comment]
Add this to gtk-widget.css file :)
```
GtkAboutDialog.background .vertical.dialog-vbox  GtkGrid.vertical {
    background: @theme_base_color;
}
```

**Comment by radioactiveman** [comment]
Thanks, now it looks fine. :+1:

**Comment by raveit65** [comment]
Good, if you find more issues, please noticed me.
Maybe we can use this report as tracking report.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-themes/commit/478e159e654fedd89da5dd35cbe57e1f1b1db01a
If you find more i will re-open the report
