### ISSUE TITLE
Changing background window colour does'nt affect gtk-3 apps for TraditionalOk theme

### ISSUE THREAD

**Issue by zuf** [mate-desktop/mate-themes#98]
Screenshot: 

![gtk-2-3-colours](https://cloud.githubusercontent.com/assets/105518/11838359/9fb94f70-a3f7-11e5-860d-e4c2e090c3be.png)

**Comment by raveit65** [comment]
This does not work for gtk3 for the moment, see https://github.com/mate-desktop/mate-control-center/issues/170
Closes as duplicate.
